### ISSUE TITLE
The path_to_unicode implementation comes just shy of correcting short file names in Windows.

### ISSUE THREAD

**Issue by epistax** [civetweb/civetweb#1000]
At the very end of the function, wbuf2 contains the corrected path name. In the mg_stat function below, we pass the result of path_to_unicode to GetFileAttrbiutesExW. This will only work if we pass in the long-form path name.

For example, in Windows Server 2012, the %TEMP% variable is by default:
C:\Users\ADMINI~1\AppData\Local\Temp
This path, and files underneath it are rejected by GetFileAttributesExW with GetLastError returning 3 (path not found). Just prior to this attempt, we called GetLongPathNameW, which would have placed this into wbuf2:
C:\Users\Administrator\AppData\Local\Temp\....

We can tell if this was successful based on the returned long_len, and we do. However the current code also decides that if the long name and the short name aren't the same, don't use any time. It fits our case best if (1) the name fits and (2) the long and short name don't match, then use the long name. Example solution:

```
static void
path_to_unicode(const struct mg_connection *conn,
                const char *path,
                wchar_t *wbuf,
                size_t wbuf_len)
{
. . .
	if (long_len >= ARRAY_SIZE(wbuf2)) {
		/* Long name won't fit. */
		wbuf[0] = L'\0';
	} else if (fcompare(wbuf, wbuf2) != 0) {
		memcpy(wbuf, wbuf2, (long_len + 1) * sizeof(wchar_t));
	}
}
```

**Comment by bel2125** [comment]
I am not sure if I understand this issue correctly? Is this a question, RFC or do you think there is a bug?

As a design principle, we only allow long names for security reasons. This choice was made because of the pattern matching features, e.g., for hiding files, url rewriting, etc.. Imagine you use some pattern to successfully hide a file using the full (long) name, but someone figured out the short name and bypassed the hiding pattern. Thus, short names are forbidden.

You won't have any problem if the short name and the long name matches anyway. Otherwise you must always use the long names.

**Comment by epistax** [comment]
In our automated environment, we find ourselves executing inside %TEMP%. This is a short name in Windows 2012. Attempts to download files hosted from civet fail as I described above. It may be there is a better place to make this change. The intention is not to unmangle anything that came over in a URL.

For example if you are hosting in %TEMP%/here, and you have a file called %TEMP%/here/there, and you access
http://myplace/there
You'll get the Error 404 response.

This may be due to passing absolute paths into civet when not absolutely required.  I'm on triage duty right now and can't quickly answer exactly how these paths are getting to civet. That will take a bit more time. To me this is a Windows bug because they give you a path and then don't let you use it. But I don't see having an opportunity to fix it there any time soon. We could also fix this by changing %TEMP% on our windows 2012 based systems to a long-form path, but honestly I'm worried we'll just run into the same issue an a year or two and start back at the beginning again not remembering what happened.  We recently upgraded from 1.07 to 1.14 and this was a change in behavior that we didn't expect.

I'm going to poke around and see if we're using unnecessary absolute paths somewhere.

**Comment by bel2125** [comment]
> We recently upgraded from 1.07 to 1.14 and this was a change in behavior that we didn't expect.

You mean you updated CivetWeb from 1.7 to 1.14?
Earlier version of CivetWeb did not check this ShortName=LongName, so pattern matching was a problem because you always needed to take care you match the long name as well as the short name. And the short name is outside of your control (unless long name = short name).

> (This is built, statically linked into some of our applications)

Then the easiest option is you call [GetLongPathName](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getlongpathnamea) for every path you pass to mg_start(). This is what we would have done - this is what I meant with

>> Depending on how you provide this option to CivetWeb, maybe we can add some conversion from short name to full name while loading the configuration in CivetWeb.

**Comment by epistax** [comment]
Right. I keep having that problem with version numbers :)

So maybe what we need to do is try to correct the current working directory of our application. 

We thought this was potentially a bug in civietweb because the code goes far enough to figure out what the correct path is, and then tosses it. It wasn't clear to me initially that wbuf[0] = L'\0' is actually error handling but I get it now. It's likely best to keep this how it is now, I'll just point out that GetFileAttributesExW does not work with short path names and will generate a file or path not found errno anyway. 

Thanks!
