### ISSUE TITLE
set static_file_cache_control failed

### ISSUE THREAD

**Issue by duanduanzz** [civetweb/civetweb#1008]
when set "static_file_cache_control no-cache", throw an instance of ‘CivertExecption’: null context when constructing ClivertServer, Possible problem binding to port.How should i solve it?

**Comment by bel2125** [comment]
Cache control has nothing to do with ports: You need to set it as one of maybe many options when calling mg_start: https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#static_file_cache_control

What other parameters did you use?

**Comment by duanduanzz** [comment]
std::vector<std::string> options = {
    "document_root",    FLAGS_static_file_dir,  "listening_ports",
    FLAGS_server_ports, "websocket_timeout_ms", FLAGS_websocket_timeout_ms, 
    "static_file_cache_control", "no-cache"};
  server_ = make_unique<CivetServer>(options);

**Comment by duanduanzz** [comment]
std::vector<std::string> options = {
    "document_root",    FLAGS_static_file_dir,  "listening_ports",
    FLAGS_server_ports, "websocket_timeout_ms", FLAGS_websocket_timeout_ms, 
    "static_file_cache_control", "no-cache"};
using std::make_unique;
server_ = make_unique<CivetServer>(options);

when append "static-file_cache_control" option, the above instance will throw.

**Comment by bel2125** [comment]
So you are using this constructor:
https://github.com/civetweb/civetweb/blob/d87a1149e5b84049fb3d535671b4aa08e07d0624/src/CivetServer.cpp#L417

I don't know what `make_unique` does, I never used C++14 - probably it does not do anything harmful, but you have to check this on your own.


All the work in done in the C implementation, C++ is only an incomplete wrapper.
In C, mg_start fails, and C++ creates an exception from this.
https://github.com/civetweb/civetweb/blob/d87a1149e5b84049fb3d535671b4aa08e07d0624/src/CivetServer.cpp#L441

A call to `mg_start2` would give some more detailed information for the code.
For `mg_start` (and C++), you should configure an error log file: https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#error_log_file
Then you will see in more detail, what the problem was.

**Comment by bel2125** [comment]
As an alternative to the file, you could define an error log callback as well (works with C and C++).

**Comment by duanduanzz** [comment]
Of course we can close this issue, thank you very much!
