### ISSUE TITLE
MSVC Command line error D8021 : invalid numeric argument '/Wextra'

### ISSUE THREAD

**Issue by fjwbarnard** [civetweb/civetweb#1024]
CMake build with Visual Studio 2019 is failing with `Command line error D8021 : invalid numeric argument '/Wextra'` since v1.14

Seems like it is caused by change cf90b37da9432cf957f4f2e3ce837d6c73647802 since `add_c_compiler_flag(-Wextra)` has been around for a long time: https://github.com/civetweb/civetweb/blob/cb479ff645ed8dea2ecaba3bf0444829e2607002/CMakeLists.txt#L407 and VS2019 CMake build worked fine on v1.13 and lower

**Comment by bel2125** [comment]
I don't have Visual Studio 2019 locally, but AppVeyor has a VS2019 build and test environment.
I managed to get cmake for CivetWeb running there:
https://ci.appveyor.com/project/civetweb/civetweb/builds/40565977/job/14sb4kt0kph8s486

It is not exactly easy to analyze any cmake build issues with a remote CI environment, since every build run takes 6 hours until you have a result. However, it is working now.

Could you confirm the issue is gone in your local test?

**Comment by grunk** [comment]
If it can help i successfully compiled (statically) the 1.15 release on VS 2019.
The solution has been generated with cmake 3.19.1 without any problem.

**Comment by bel2125** [comment]
@grunk : Thank you.

So we have a second test environment confirming CMAKE works "in general", in addition to the test done using AppVeyor.

@fjwbarnard : Could you test with the V1.15 as well? I am not aware that we changed anything that could cause an improvement here, but I am also not aware of any changes we made that might have caused this issue in the first place. Probably the issue is solved now? Maybe it is more related to your specific build environment than to changes in CivetWeb?

**Comment by fjwbarnard** [comment]
> @grunk : Thank you.
> 
> So we have a second test environment confirming CMAKE works "in general", in addition to the test done using AppVeyor.
> 
> @fjwbarnard : Could you test with the V1.15 as well? I am not aware that we changed anything that could cause an improvement here, but I am also not aware of any changes we made that might have caused this issue in the first place. Probably the issue is solved now? Maybe it is more related to your specific build environment than to changes in CivetWeb?

Hi all,

Sorry for being so slow to respond. I am still getting the same issue as of this commit: 45c21792c9182ecd920cdb9675c8e59ab314ed0f

I am using MSVC v19.29.30133.0 with CMake 3.20.2 and the `CodeBlocks - NMake Makefiles` CMake generator. This is the error I get in the CMake build (note this is before MSVC compilation):
```
cl : Command line error D8021 : invalid numeric argument '/Wextra'
```

Kind regards,
Francois

**Comment by grunk** [comment]
As far as I know /Wextra is not a msvc flag. Maybe visual studio simply ignores it while code blocks on the other hand is a little bit more sensitive ?

**Comment by fjwbarnard** [comment]
> As far as I know /Wextra is not a msvc flag. Maybe visual studio simply ignores it while code blocks on the other hand is a little bit more sensitive ?

Indeed it isn't a MSVC flag, along with many of these other flags being set in `CMakeLists.txt` when `CIVETWEB_ENABLE_CXX` is set:
```
  add_cxx_compiler_flag(-Wall)
  add_cxx_compiler_flag(-Wextra)
  add_cxx_compiler_flag(-Wshadow)
  add_cxx_compiler_flag(-Wmissing-prototypes)
  add_cxx_compiler_flag(-Weverything)
```

The main `CMakeLists.txt` has been unchanged since v1.13 where it was still working, although the flags were skipped then because of this change not being present: https://github.com/civetweb/civetweb/commit/cf90b37da9432cf957f4f2e3ce837d6c73647802 

According to my limited knowledge of GCC/MSVC compiler flags and CMakeLists files I believe a check for `not(WINDOWS)` (or the like) should be done before adding those flags in the first place. v1.13 and before were working "by-accident" from what I can deduce now.

**Comment by bel2125** [comment]
As to my knowledge, the problem is solved.
If not, please reopen this issue.

**Comment by HimeshKana** [comment]
I still got the problem, i need to do a project for my school but they already code some part of the code and i got the same error and i think it is because the based their code for unix compiler not cl and i wondering if i can open an unix shell on vs 2022 to resolve this problem and still code with vs 2022

**Comment by bel2125** [comment]
I do not have a Visual Studio 2022 to investigate this.

The easiest way to embed civetweb into another project is to just copy the civetweb.c file and add it to the other project. The src/*.inl and include/civetweb.h file must be copied there as well. Then you don't need to care about combining different build systems of different projects. See [Embedding.md](https://github.com/civetweb/civetweb/blob/master/docs/Embedding.md#http-server-source-files). 

> ... wondering if i can open an unix shell on vs 2022  ...

I don't know VS2022, but I have a VS2017 and I can build civetweb on a Linux system using VS2017 running on Windows. This can be a "real" Linux system or WSL (Windows Subsystem for Linux running Ubuntu). But please don't ask me how to get VS+WSL running on your PC - there is some documentation from Microsoft, but if it does not work out of the box it will require some hours of searching and fiddling. The easiest way will be to add the files to project and build system that is already working for you.

If there is a general issue - e.g., the original issue is still unsolved - and someone knows a fix, I will definitely merge this fix. However, right now I don't have a Visual Studio 2022 - therefore I cannot investigate this by myself.

**Comment by MHU-valantic** [comment]
Hi,
with the following fixes a Windows CMake builds with VS2017+ should work (again).
The reason was that the check whether a compiler supports a compiler flag or not was broken. it always returned a success state
causing cmake to add compiler flags that are not supported by the Visual Studio compilers.

[0001-Fixed-Windows-compile-errors-in-cmake-build.patch.txt](https://github.com/civetweb/civetweb/files/8727734/0001-Fixed-Windows-compile-errors-in-cmake-build.patch.txt)

**Comment by fjwbarnard** [comment]
I can confirm the issue is resolved as of https://github.com/civetweb/civetweb/commit/afea23abf322fb7eba0f1bb8675e09b1039fb47d using MSVC 2019 and CMake 👍

**Comment by duguyitian** [comment]
This issue is still there with VS2022+CMake3.26. It reports: cl:D8021 Invalid numerical parameter -Wno-unused-parameter.  I have to add some check codes as workaround:

`check_cxx_compiler_flag(-Wno-unused-parameter HAS_UNUSED_PARAMETER)
if(HAS_UNUSED_PARAMETER)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unused-parameter")
endif()`

**Comment by bel2125** [comment]
Honestly, I have no idea how to fix this, if it occurs in some Visual Studio + CMake combinations ... on some systems, but it does not occur on other combination, maybe even the same but something else is different on the build machines. I am not an expert on CMake - I can do some basic stuff with it, but I cannot even reproduce the issue myself. Suggestions/pull requests welcome.

**Comment by patrikhuber** [comment]
I'm using Open3D (https://github.com/isl-org/Open3D), which uses civetweb as part of their build. While compiling the civetweb dependency, it also fails with `cl : Command line error D8021: invalid numeric argument '/Wextra'.`

I'm on latest VS2022 (17.9.5) with CMake 3.28.

The "fix" should be rather simple: MSVC simply does not support `-Wextra` (or `/Wextra`), so this flag shouldn't be used on MSVC.

**Comment by Nickrader** [comment]
Maybe wrap that in ?

`if (MSVC)`
https://github.com/civetweb/civetweb/blob/85d361d85dd3992bf5aaa04a392bc58ce655ad9d/CMakeLists.txt#L381
`endif()`

**Comment by patrikhuber** [comment]
I'm not sure if I still saw this in the latest release (0.19.0), I think the Open3D maintainers updated the 3rdparty civetweb version, which might have fixed this - but can't say for certain as I've only compiled Open3D without GUI/civetweb recently.
