### ISSUE TITLE
Example Has a problem

### ISSUE THREAD

**Issue by gsteri1** [civetweb/civetweb#1026]
Hi! Excellent project. 

I am trying to work through some of your examples and am stuck on:
https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c#L657

You have a snippet:
`	while (r > 0) {
		r_total += r;
		s = mg_send_chunk(conn, buf, r);
		if (r != s) {
			/* Send error */
			break;
		}
		r = mg_read(conn, buf, sizeof(buf));
	}`

The test for r != s should always fail because you are always sending more bytes (the length is prepended to the buffer on every send) than the receive buffer's size. 

Additionally, the example is problematic since when the read buffer is emptied, the connection is slammed shut. This results in an error on the away (client) side: curl: (18) transfer closed with outstanding read data remaining. Is there any way to keep the connection open and close it manually after I have responded to the request? Thank you!

**Comment by gsteri1** [comment]
On the second part of my "problem" it looks like there might be two causes. First, I am not setting keep_alive to "on" via the options. I add that option to the init string:  

"enable_keep_alive",
        "yes",

curl which is uploading and receiving back a json file apparently expects a content length set in the header. When both the keep-alive is allowed and the length set, the outstanding data error goes away.

**Comment by bel2125** [comment]
Regarding the first issue:

I think you are right, since `mg_send_chunk(conn, buf, r)` returns something like `r + 4 + ceil(log16(r+1))` bytes on success, but that's hard to know from outside this function. Probably redefining the return value or just checking >0 would be more appropriate.

Regarding the second issue:

As to my knowledge, the command line program "curl" does not use keep-alive. It would not make any sense for a command line program, since it downloads one url and then exits - it cannot keep alive the connection after exiting the command line program anyway.

**Comment by bel2125** [comment]
The first problem you reported has been fixed in https://github.com/civetweb/civetweb/commit/a55f5f72fc6b3a4b98b6b0be77686503552c2894 - thank you for reporting this.

I am still not sure what you mean with the second problem.
If you want to use keep-alive ... and to my knowledge this is NOT possible with the curl command line tool ... you need to set the content length of a response in the header (or, alternatively, use chunked transfer encoding). 
You SHOULD set a content length for "Connection: close", but you MUST set a content length for "Connection: keep-alive".
See the minimum example in the documentation.
https://github.com/civetweb/civetweb/blob/master/docs/Embedding.md#a-minimal-example
There is an `mg_close` API function that can be used to close the connection ... but often it is better for a server to wait for the client to close the connection. Since I don't understand what you mean with the second problem, I cannot give you a definite advice.

**Comment by bel2125** [comment]
First part of the problem solved in https://github.com/civetweb/civetweb/commit/a55f5f72fc6b3a4b98b6b0be77686503552c2894

Not enough information on the second part. Last update > 3 months ago.
It there is remaining problem that is is still relevant, please open a new issue explaining it in more detail.
