### ISSUE TITLE
Path variables in HTTP URI

### ISSUE THREAD

**Issue by dacrome** [civetweb/civetweb#1034]
Currently it is not possible to use path variables in URIs like `/user/{id}`. Any plans to support that?

**Comment by bel2125** [comment]
This is possible.
Why do you think it's not?

How do you want to use it: As Lua script, C callback, CGI script?

Did you check this part of the documentation and the examples:
https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#pattern-matching-in-configuration-options
https://github.com/civetweb/civetweb/blob/master/docs/api/mg_set_request_handler.md
https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c
https://github.com/civetweb/civetweb/tree/master/test/scriptdir
... 

Probably I can give you a more precise example when you tell more precisely what is not possible.

---

What you are trying to do may be something like this:
https://github.com/civetweb/civetweb/issues/1016

---

The pattern matching is "old" - I must work like this at least since version 1.6 from 2014.

However, the pattern matching with the pattern explained in https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#pattern-matching-in-configuration-options has some limits.

More complex patterns have already been discussed here:
https://github.com/civetweb/civetweb/issues/629

However, the problem is, any "better" pattern matching will break compatibility with code that has been in production for up to 7 years:
https://github.com/civetweb/civetweb/issues/499
Even a possible replacement code already exists since a while, but I never merged into the master, since this is a heavy compatibility break (and I don't want two interfaces for intermixing old and new patterns).
Up to now, it was always possible to register a handler for some directory URL and then do a finer matching processing the full URL inside the directory URL handler. Therefore this version 

---

Anyway: 
I would prefer if you could explain your exact needs, since I do not know what you are really missing.

**Comment by dacrome** [comment]
Hi @bel2125 

oh I am sorry, I did not found that... we are using the C++ wrapper.

I would like to do something like this:

```
ExampleHandler exampleHandler;
server.addHandler("/example/${exampleId}", exampleHandler);
```

And in the handler the path variable is pass as a parameter like

```
bool handleGet(CivetServer *server, struct mg_connection *connection, struct mg_params *params) override
{
    std::string exampleId = params->exampleId;
}
```

but now I get it. The handler processed everything starting with /example and we just have to extract the rest from the uri to get the dynamic part, right?

Of course my approval would be really nice! :)

Thanks,
David

**Comment by dacrome** [comment]
@bel2125 thanks for your great explanations and links. I read it again and #629 is what comes closest to our requirements.

But for now, we can just handle it in our http handlers...
