### ISSUE TITLE
Should mg_send_http_ok handle CORS?

### ISSUE THREAD

**Issue by macedot** [civetweb/civetweb#1044]
I've recently migrated some code to use _mg_send_http_ok_ and noticed it doesn't send CORS headers. But should it? 

I've copied what _handle_static_file_request_ does to handle CORS and port it to _mg_send_http_ok_, I'm not sure if it was the best way to accomplish that.

Cheers!

EDIT: With "handle" I mean "send the appropriate headers at the response".

EDIT2: Should it send back the **_Access-Control-Allow-Origin_** header **only if** the request contains a **_Origin_** header, as per _handle_static_file_request_ ?

**Comment by bel2125** [comment]
General idea:
---

CivetWeb can handle static files automatically, without executing any additional C code. Since no additional code is executed, all additional headers for static files need to be taken from configuration entries. A callback can send any additional header itself, also conditional if required.

This what requests for static files, `mg_send_http_ok` and `mg_send_http_err`,  do. They are all based on `mg_response_header_send` (last column):

**Header** | **static file** | **`_ok`** | **`_err`**| **`_send`**
--|--|--|--|--
connection|yes (config)|yes (config)|yes (close)|yes
date|yes|yes|yes|yes
additional config|yes|yes|yes|no
cache control|yes (config)|yes (no cache)|yes (no cache)|no
content type|yes|yes|yes (fixed)|no
content length|yes|yes|no (connection: close)|no
accept ranges|yes|no|no|no
cors|yes|no|no|no
last modified|yes|no|no|no
etag|yes|no|no|no

(There is also `mg_send_http_redirect`, but I just found it is not HTTP/2 ready and I need to fix this. It will behave like `mg_send_http_err` afterwards.)

The most general interface is `mg_response_header_start` + `mg_response_header_add` + `mg_response_header_send`. Using `mg_printf` or `mg_write` will work for HTTP/1.x but not for HTTP/2. The  `mg_response_header_start` + `mg_response_header_add` + `mg_response_header_send` combination will only send absolutely required headers: the "date" header is required (unless the server does not have a real time clock), and either the "content-length" or a "connection: close" must be present (or chunked transfer-encoding).
Using the `mg_response_header_start` + `mg_response_header_add` + `mg_response_header_send` combination will be the most flexible choice for a callback.

The other methods (`mg_send_http_ok`, ...) make some assumptions - that might me suitable or not for a particular use case.


special case: CORS in `mg_send_http_ok`
---

The section above was a general idea, but what about the special case of CORS?

Currently it does not send the CORS headers from the configuration for static files. In contrast to the other headers sent for static files but not for `mg_send_http_ok` (accept-range, last-modified, etag), it might indeed make sense to sent it. Will it also make sense for `mg_send_http_error`? Probably not.

There might still be some cases, where sending a CORS header from the configuration is not what we want. I had at least one case, where I had to copy the content of the "Origin" request header into the "Access-Control-Allow-Origin" response header, after doing some checks - instead of using a fixed value from the configuration. But this was a special case and I had to use the `mg_response_header_start` + `mg_response_header_add` + `mg_response_header_send` combination anyway.

conclusion
---

Probably `mg_send_http_ok` should send the header

> EDIT2: Should it send back the Access-Control-Allow-Origin header only if the request contains a Origin header, as per handle_static_file_request ?

Yes. Similar to static file requests.

**Comment by bel2125** [comment]
My recent modification should make the behavior consistent:

This is what is sent automatically for static files / `mg_send_http_ok` / `mg_send_http_err` / `mg_send_http_redirect` / `mg_response_header_send`.

**Header** | **static file** | **`_ok`** | **`_err`** | **`_redirect`** | **`_send`**
--|--|--|--|--|--
date|yes|yes|yes|yes|yes
connection|yes|yes|yes (close)|yes|yes
additional config|yes|yes|yes|yes|no
cache control|yes (static)|yes (no cache)|yes (no cache)|yes (according to 30x code)|no
cors|yes|yes|yes|yes|no
content type|yes|yes|yes (fixed)|depends / yes (fixed)|no
content length|yes|yes|no (due to connection: close)|yes|no
accept ranges|yes|no|no|no|no
last modified|yes|no|no|no|no
etag|yes|no|no|no|no

When using `mg_response_header_send`, any additional header can be added by calling `mg_response_header_add` before.

**Comment by bel2125** [comment]
Fixed in https://github.com/civetweb/civetweb/commit/9cbc9feb484e2eaa88ab67d0976f163afa6d3270
