### ISSUE TITLE
open_file callback listed in doc but does not exist in code

### ISSUE THREAD

**Issue by f4gkr** [civetweb/civetweb#1095]
I'm trying to implement a custom cache/file loader and was checking the callback API documented here : https://github.com/civetweb/civetweb/blob/master/docs/api/mg_callbacks.md

It is said that the mg_callbacks struct has a function pointer to open_file but this is not the case in the civetweb.h

sylvain

**Comment by bel2125** [comment]
You are right, this is still in the documentation.

This API function has been removed in version 1.13:
https://github.com/civetweb/civetweb/blob/master/RELEASE_NOTES.md#release-notes-v113
- Remove obsolete "file in memory" implementation

Already in 2017 it has been marked as obsolete and "to be deleted":
https://github.com/civetweb/civetweb/blob/master/RELEASE_NOTES.md#release-notes-v110
Mark "file in memory" feature is a candidate for deletion

Even earlier there was a request for comments
  -  "does anyone use this feature?" 
  - "is there any use case that cannot be fulfilled using handlers?" 


Since we did not have a use case that needed this, the function got a `#ifdef LEGACY` for some years and finally got removed ... except from this page of the documentation.


Using "handlers" is the "new" (since 2013) way to do this:
https://github.com/civetweb/civetweb/blob/master/RELEASE_NOTES.md#release-notes-v14

https://github.com/civetweb/civetweb/blob/4245a37b436da23e1e148fd35513732169f80b11/include/civetweb.h#L516

https://github.com/civetweb/civetweb/blob/master/docs/api/mg_set_request_handler.md

If there is something you cannot do with request handlers (there are some use cases on embedded devices without a file system), there are other callbacks.

If you tell me more about your use case, I might be able to give you a better recommendation - but from "cache/file loader" I would assume handlers might be the way to go.

**Comment by f4gkr** [comment]
Thank you very much for your detailed explanation and the time you spent
providing high quality feedback...
Ok for the feature that does not exist anymore, noted.

The use case is the following: Civetweb is used as an embedded server,
where the main app generates real time data from sensors. This data is made
available either locally or remotely through http: by streaming (using a
specific handler) or by simple web pages and a REST api (through handlers).
We have recently added webocket support too.
Now the problem: we would like the user to be able to package in a single
zip file the different resources that are needed to share the "project" he
designed (configuration + html files + css + javascript etc. etc.) with
other users.
How do we serve the pages that are contained inside the zip ? the handlers
we designed use libarchive to extract the non-web files but now comes the
issue of the static resources...
Typically I'm looking for a way to intercept the "open call" to index.html
in the root folder to serve the file that is contained in the zip. I can
use wildcards in the handlers I believe but I wanted to first read in the
zip and - if not found - then look on the local root directory.

Thanks for your views

**Comment by bel2125** [comment]
I would use handlers for everything:
https://github.com/civetweb/civetweb/blob/master/docs/Embedding.md#a-minimal-example

https://github.com/civetweb/civetweb/blob/4245a37b436da23e1e148fd35513732169f80b11/examples/rest/rest.c#L194

You can match "/" for one handler and have some specific handlers for other URLs.
Can you unpack your zip when the server starts (there is a callback for this), for example to a RAM disk?
I don't know how "embedded" (how small) your system is, and if disk space, ram space, CPU performance or network will be your bottleneck - or something completely different like getting data values from your sensors. I would go for a design that unpacks the zip at start time (to RAM) or when a new zip is downloaded (stored to flash disk) and then works with unpacked files, while the user can still work with archives. But I don't know your exact embedded device.

It is possible to use a handler to extract the file from the zip at every request - it will consume CPU at every request.

**Comment by f4gkr** [comment]
Thanks for your feedback.

This is running in a NVIDIA Jetson GPU and processing several tens of
megasamples per second. Ok for the RAM "extract once", you are right.
I'll go with a handler for "/".

Have a nice day
sylvain
