### ISSUE TITLE
Is it possible to a getsockname/getpeername on civetweb connection?

### ISSUE THREAD

**Issue by PerryWerneck** [civetweb/civetweb#1111]
I'm working in an app who needs to send the local address of the connection in the payload. I usually do this doing a getsockname() on the connected socket. Can something like this be done on civetweb? Can I get the connected socket handle on it? Or use a custom connect method?

**Comment by bel2125** [comment]
Information on a client connected to the civetweb server is stored in the `mg_request_info` structure. There you can find client IP and port.
The socket handle is not exposed directly, because (a) it is different for Windows and Linux, (b) some low level operations on the handle might break the way civetweb uses this connection (now or in future), and I can't offer support or ensure compatibility for low level operations on the socket. Nevertheless, if there is something that cannot be done with the current interface I can look if we can extend it - or provide a compiler define to still export the low level handle, with the aforementioned restrictions.

**Comment by PerryWerneck** [comment]
This issue is more related with the civetweb http client. The app receive a request and do http request to others servers to get the answer.
