### ISSUE TITLE
When init the CivetServer, pthread_create failed, error_code 22?

### ISSUE THREAD

**Issue by ericfangxu** [civetweb/civetweb#1130]
This is my code and options,

```cpp
mg_init_library(0);

const char *options[] = {"document_root",
                           ".",
                           "listening_ports",
                           "10080r,10443s",
                           "num_threads",
                           "2",
                           "request_timeout_ms",
                           "10000",
                           "error_log_file",
                           "../log/civetweb_error.log",
                           "websocket_timeout_ms",
                           "3600000",
                           "ssl_certificate",
                           "../../resource/ssl/civetweb/server.pem",
                           "ssl_protocol_version",
                           "3",
                           "ssl_cipher_list",
#ifdef USE_SSL_DH
                           "ECDHE-RSA-AES256-GCM-SHA384:DES-CBC3-SHA:AES128-SHA:AES128-GCM-SHA256",
#else
                           "DES-CBC3-SHA:AES128-SHA:AES128-GCM-SHA256",
#endif
                           "enable_auth_domain_check",
                           "no",
                           0};

std::vector<std::string> cpp_options;
for (size_t i = 0; i < (sizeof(options) / sizeof(options[0]) - 1); i++) {
  cpp_options.push_back(options[i]);
}

server_ = std::make_unique<CivetServer>(std::move(cpp_options));
```

And the error messege is:

`[error] [client ] Cannot create threads: error 0, create_thread ret: 22`

Is there something wrong with my configuration?

Thank you for helping!

**Comment by bel2125** [comment]
The configuration (`cpp_options`) looks ok, except I would always use more than 2 threads, because browsers tend to open multiple connections - except you will never have more than one client at the same time and don't have high performance requirements. But this will not cause the issue you see.

I never used the `std::make_unique` / `std::move` form - in fact I am usually using the complete C interface, not the C++ wrapper that offers only a very limited subset. I can not give you a definite answer if the way you use them is ok. Did you try it the same way it is used in the C and/or C++ example?

What system is this? The error number is system depended (for Linux 22 is "invalid argument"). For other systems, the error numbers may be defined differently.

**Comment by ericfangxu** [comment]
It run on Linux. And when I try it the same way it is used on the civetweb exe, it work well. Finally, we find that this is a problem caused by incompatibility with other components. And we solve it by adjusting the tdata|tbss.
Before,
<img width="487" alt="image" src="https://user-images.githubusercontent.com/39576811/222351321-16cd5cbc-f52c-4b91-acba-9944712df528.png">
After,
<img width="482" alt="image" src="https://user-images.githubusercontent.com/39576811/222351398-42e45eb5-5c1a-47f2-9d27-4c78a8b6eb0c.png">

Thank you very much!
