### ISSUE TITLE
mbedTLS v3.x compatibility

### ISSUE THREAD

**Issue by DL6ER** [civetweb/civetweb#1143]
### Introduction

We plan to use `civetweb` in [Pi-hole](https://github.com/pi-hole/pi-hole) as embedded webserver in our [DNS/DHCP daemon](https://github.com/pi-hole/FTL) and already have a all-in-one binary ready statically including [Mbed TLS](https://github.com/Mbed-TLS/mbedtls) for TLS support.

### The problem

While working on getting Mbed TLS included, we realized that [`mod_mbedtls.inl`](https://github.com/civetweb/civetweb/blob/master/src/mod_mbedtls.inl) is not compatible with the most recent Mbed TLS v2.x but only with the v2.x-series (v3.0.0 was released on [Jul 7, 2021](https://github.com/Mbed-TLS/mbedtls/releases/tag/v3.0.0)). A [v2.x -> v3.x migration guide](https://github.com/ARMmbed/mbedtls/blob/development/docs/3.0-migration-guide.md) is available.
The most recent v2.x-branch release ([v2.28.3](https://github.com/Mbed-TLS/mbedtls/releases/tag/v2.28.3)) is a long-term support release receiving bug- and security-fixes until end of 2024.

I have seen in other issue tickets, that Mbed TLS seems to be beneficial in many ways because of its small footprint and the ability to statically link it into the executable as well as it's easy to use in any cross-platform and cross-OS builds.

### Questions

- Can we expect that `mod_mbedtls.inl` will be upgraded to support v3.x within the next year so there is enough time to migrate projects `civetweb` to the most recent major version?
- If there are no plans to work on this, would an external contribution be accepted?
  - if so, would a breaking change in `civetweb` be accepted (`mbedtls v2.x` stops working), or
  - would the code have to be compatible with both (a lot of `#if MBEDTLS_VERSION_NUMBER > 0x03000000 ... #else .... #endif` )?

**Comment by bel2125** [comment]
Yes, mbedTLS would be beneficial for many users.

For OpenSSL we used to stay compatible with V1.0 and V1.1 by using an #ifdef.
For a while, both versions were supported in parallel. Now the V1.0 binding code is still there but no longer actively maintained. OpenSSL is shipped already with many Linux versions, and it was required to support both for a while because it was not always possible to use V1.1 instead of V1.0. In 2024 also OpenSSL V1.1 should no longer be required and probably the code can be reduced to OpenSSL V3.0 support only - but we will see.

For mbedTLS, it would not be required to have multiple versions of mbedTLS in parallel - unless there is a reason why someone could not use the new version but has to stick to the old one.

The plan is to finish a release in the next days.

Does this PR already make it compatible with mbedTLS V3? https://github.com/civetweb/civetweb/pull/1144/files

**Comment by DL6ER** [comment]
Yes, this PR makes it compatible with both V2 and V3

**Comment by bel2125** [comment]
Thank you for this patch. Merged.
