### ISSUE TITLE
Not able to register websocket with subprotocol in CivetServer class?

### ISSUE THREAD

**Issue by tzjb** [civetweb/civetweb#1179]
Hi @bel2125 ,
It seems that since this comit [d41158b](https://github.com/civetweb/civetweb/commit/d41158bb3aad3123fbcd390e148c18a9f154d313), if a client and a server are doing websocket handshake over a custom sub-protoocol, the server needs to call `mg_set_websocket_handler_with_subprotocols()` with sub-protocol explicitly specified? This is not issue when using civetweb.c, but it seems CivetServer.cpp doesn't support websocket hanlder setup with sub-protocol. Is this by design or an issue?

Thanks!

**Comment by bel2125** [comment]
By design the C++ wrapper only offers a subset of the server functionality. The client functionality and many of the more advanced or less often used features are not covered by the C++ wrapper.
Since many years I am recommending all new projects to use the C interface. New features usually are only introduced there - they are not added to the C++ interface as a default.
This is a design choice in order not to duplicate work without adding real functionality.

**Comment by bel2125** [comment]
Although, adding individual features without significant testing and maintenance effort to the C++ interface is possible and sometimes done by a contributor. The "websocket with subprotocol" as an overloaded C++ function would be possible. 
As a default, when a new feature is created, it is not automatically added to C++ as well and if no one asks for it it may be missing there for years.

**Comment by tzjb** [comment]
Thanks. I am closing this issue. Hopefully the C++ interface can include this function in the future.
