### ISSUE TITLE
C++ wrapper for websocket client

### ISSUE THREAD

**Issue by prakhars144** [civetweb/civetweb#1187]
I can see that wrapper for WS Server are implemented and mentioned in CivetServer.h

But I am unable to find any C++ wrapper for the client side. Is that part not implemented ? I am talking about C++ wrapper for **mg_connect_websocket_client**

**Comment by bel2125** [comment]
The C++ wrapper is incomplete and there is no plan to have the full functionality of the C interface in the C++ wrapper. I recommend since a long time to use the C interface, because all new features will only be added there.
The C++ wrapper offers only a small subset of the server functionality. The C interface offers much more.

**Comment by fgallegosalido** [comment]
May I ask if you are willing to accept pull requests extending/improving the C++ wrapper?

**Comment by prakhars144** [comment]
Thank you @bel2125 for the response.

I went ahead and created my own wrapper. If anyone interested, search "mg_connect_websocket_client" on github itself and you'll be able to find many sample code related to it.
