### ISSUE TITLE
sqlite3 can't bind when lsqlite3.c updated to most recent version

### ISSUE THREAD

**Issue by shawnye** [civetweb/civetweb#139]
When I update `lsqlite3.c` to most recent version and build on VS2010, there is nothing complained.

when I tried this test/page.lua, I found `sqlite3 binding` disappeared.
I study `mod_lua.inl` and new `lsqlite3.c` , it seems that their interfaces are matched, any sugguestion?
Thank your

most recent version of lsqlite3.c can be download here:
[LuaSQLite3](http://lua.sqlite.org/index.cgi/index)

**Comment by bel2125** [comment]
This is maybe because Lua 5.1 handles libraries a little different than 5.2.
Lua 5.1 loads all library into the global environment, while you should set them to a local table for Lua 5.2. When I updated from Lua 5.1 to Lua 5.2 I changed a few lines in the library loader code in order to preserve the behavior of 5.1.
For the moment I do not plan to update to 5.3 soon.

**Comment by shawnye** [comment]
It's a pitty , now I have to build an independant DLL for lsqlite3, which is bigger one , waiting for your update when you got some time:(

**Comment by shawnye** [comment]
I changed src\mod_lua.inl in line 1096:
`luaopen_lsqlite3(L);`
with  `luaL_requiref (L, "sqlite3", luaopen_lsqlite3, 1);`
call `require"sqlite3"` programmatically, this change can be successfully built with lua 5.3 ,  and sqlite3 is binded and function well.

**Comment by bel2125** [comment]
The need for an additional
`require "sqlite3"`
in the Lua scripts is an incompatibility.
This is something that can be discussed again after the next release, or later when changing from Lua 5.2 to 5.3.

In fact I am not really happy with the changes from Lua 5.2 to 5.3, since some there are some incompatibilities in the language, but I do not yet see any advantage for a web server scripting language. E.g., up to 5.2, the programmer did not need to take care if a number is an integer or a floating point number.

See also this discussion
https://groups.google.com/forum/#!topic/civetweb/Atk7N8SJj0U

**Comment by bel2125** [comment]
I made updates for sqlite3 and lsqlite yesterday. Both are the most recent versions now.
In order to have sqltite3 in the global environment with the new version, as it was with the previous version, this fix is required: https://github.com/bel2125/civetweb/commit/358f43c0d26dec612a5d0a7e49140a6c01189d21

I currently do not plan to update from Lua 5.2 to 5.3, but if you want to (why?), it I think it should work for Lua 5.3 too.

**Comment by bel2125** [comment]
@shawnye: Did you actually succeed with your Lua 5.3 integration?
I still do not really see the advantage of 5.3 over 5.2 in a web server, so I do not plan to change soon. But as far as I understood, you are already working with 5.3. Do you have any (positive or negative) experiences with it?

**Comment by bel2125** [comment]
I guess there is nothing more to do here.

**Comment by agrw** [comment]
It seems this latest fix is not in current lsqlite3.c file, can it be added?

**Comment by bel2125** [comment]
Done ... again
There is no new version of lsqlite3 available [here](http://lua.sqlite.org/index.cgi/index) - 0.9.4 still seems to be the most current one.
