### ISSUE TITLE
Support for LuaJIT and duktape

### ISSUE THREAD

**Issue by Mynock17** [civetweb/civetweb#194]
This would be a great improvement: LuaJIT for a big speed boost, duktape because we could have the same language on server- and clientside (ECMAScript).

**Comment by bel2125** [comment]
As to my knowledge, LuaJIT is not related to JavaScript/ECMAStript at all.

I did not know duktape (this one http://duktape.org/ ?) - but it looks quite interesting, also the License is compatible with CivetWeb. I will have a closer look.

Maybe we should split LuaJIT and duktape in two separate issues. Or is there a connection between them, which I currently do not see?

**Comment by Mynock17** [comment]
Oh, sorry - no there is no connection between LuaJIT and Duktape (yes: http://duktape.org).
What I mean is the possibility to choose between Lua / LuaJIT / Duktape at compile time.

**Comment by bel2125** [comment]
LuaJIT
---

I am not sure, if LuaJIT will speed up the server, because (except for websockets for Lua) every request creates a new Lua state. So every script needs to be compiled for every request. Or is there a way to save pre-compiled scripts as well, so they can be used in a new state without having to run the compiler again.

But a test might be quite simple: According to [this embedding instructions](http://luajit.org/install.html#embed), LuaJIT might already work when using the WITH_LUA_SHARED make option. It uses a shared object instead of building Lua from source. Probably the name of the SO has to be changed [here in the Makefile](https://github.com/civetweb/civetweb/blob/master/Makefile#L129). I'm currently abroad, so it will take some days until I can do this test.

If this turns out to work, I think we can just provide a build option WITH_LUAJIT_SHARED - on systems where a LuaJIT shared object is available. I don't want to add the LuaJIT sources here in the [`src/third_party`](https://github.com/civetweb/civetweb/tree/master/src/third_party) folder to allow static building with the project.


duktape
---

I did not know this library before, so I have to read [the manual](http://duktape.org/guide.html) first.

**Comment by sunsetbrew** [comment]
I would lean towards your proposal to use WITH_LUA_SHARED.  I am currently
using WITH_LUA_SHARED because we are using a Lua 5.3  with some
built-in extensions.

**Comment by bel2125** [comment]
For a major Linux distribution with `liblua` available, from my point of view it makes no sense to use `WITH_LUA` instead of `WITH_LUA_SHARED`. You should just use the Lua shared object available for the distribution, not build your own static library.
However, when I (we) started to work with CivetWeb, only `WITH_LUA` was available. I added `WITH_LUA_SHARED` some time last year but I did not change the original behavior of `WITH_LUA` to retain compatibility. There are also some other issues with the Lua embedding that should be changed, but this is not only possible without breaking compatibility. Anyway, this is another topic.

The same way liblua is used by "WITH_LUA_SHARED", a "WITH_LUAJIT_SHARED" could be added to use libluajit instead of liblua - or another parameter. There is probably no need to support liblua and libluajit mixed in the same server instance, so using LuaJIT might indeed be quite easy - though, I did not test it yet.

**Comment by sunsetbrew** [comment]
Sounds good!  Perhaps the most wonderful part of Lua is how easily it is
extended.  The power of WITH_LUA_SHARED is that it supports custom Lua
implementations.  So as long as we keep that capability, I am highly
supportive.  And by the way Bel,  thank you for your dedication to Lua. If
not for you, I may have never taken the time to learn it.

**Comment by bel2125** [comment]
A first (quick and dirty) implementation of LuaJIT [already works](https://github.com/civetweb/civetweb/commit/d50aef8b613fca5c87b90ae4d8757f54c807ef7e) - I had to do a quick backport to Lua 5.1 for it, and I have to clean up the repository later.

**Comment by bel2125** [comment]
Unfortunately LuaJIT currently only offers a Lua 5.1 C interface. CivetWeb uses Lua 5.2 as default, and some of the C libraries used in CivetWeb do not work with the Lua 5.1C API.

I added an enhancement (#195) to let the user select the Lua version (`make WITH_LUA_VERSION=501`, `WITH_LUA_VERSION=502` or `WITH_LUA_VERSION=503` for Lua 5.1, Lua 5.2 or Lua 5.3 respectively).

I also added an option `WITH_LUAJIT_SHARED=1` - it will automatically select the Lua 5.1 interface.

However, I did not backport the third party Libraries to Lua 5.1, so if CivetWeb is built with Lua 5.1 some libraries like lsqlite or the connect functions are not available in the standard build. There should be an older version of lsqlite supporting Lua 5.1, but I did not yet have a look.

This version should be good enough to test LuaJIT. I am still not sure if there is a performance gain for web server scripts at all, because still: every request creates a new Lua state ... see https://github.com/civetweb/civetweb/issues/194#issuecomment-133148289.

**Comment by malexzx** [comment]
lua_pushglobaltable used in mg_exec_lua_script available in Lua 5.2 or above. It may be ported or hided by ifdef LUA_VERSION_NUM > 501 (since it not used by now).

**Comment by bel2125** [comment]
Curiously enough, I did not get any warning `lua_pushglobaltable` would be missing. Also the resulting executable worked and displayed "Lua 5.1" from `test/page2.lua`.
Probably it took the header from the Linux include directory instead of the header in the third_party/lua-5.1.5 directory, and it did never call the function/macro, because the parameter `exports` is always `NULL`.

**Comment by Mynock17** [comment]
Probably the only way is to pool the compiled scripts ...
The same for other scripting languages (i.e. Duktape).

bel2125 wrote:
"I am not sure, if LuaJIT will speed up the server, because (except for websockets for Lua) every request creates a new Lua state. So every script needs to be compiled for every request. Or is there a way to save pre-compiled scripts as well, so they can be used in a new state without having to run the compiler again."

**Comment by bel2125** [comment]
I'm currently evaluating Duktape. It seems to work in principle, but it will take a while until all library functions are available there - I mean the equivalent of all `mg.*` functions in Lua.

Caching/pooling compiled scripts is something that should not be implemented in the web server - I am not sure if LuaJIT offers any interface to cache compiled scripts, at least I did not find any function [in the API](http://luajit.org/ext_c_api.html).

**Comment by bel2125** [comment]
Closing enhancement as already solved in version [1.8](https://github.com/civetweb/civetweb/blob/master/RELEASE_NOTES.md#release-notes-v18).
