### ISSUE TITLE
Question: How to properly handle shared data between threads?

### ISSUE THREAD

**Issue by everte** [civetweb/civetweb#208]
Hey,

Maybe this "issue" does not fit 100% here, if so feel free to close. As a C newbie, I've been extending the examples/embedded_c.c program for some time now and I'm lost on how to properly make it scale. I'm only using the websocket part from civetweb at the moment and trying to write a chat server (and webbased client).

To the point: I've been extending the following structure with many variables to track state for every websocket connection. Some examples: an userID, a nickname, a dynamic array for "groups" the user belongs to, etc.

```c
#define MAX_WS_CLIENTS (5)

struct t_ws_client {
	struct mg_connection *conn;
	int state;
} static ws_clients[MAX_WS_CLIENTS];
```

I still use the same code as in the example to handle a new connection. After authenticating the user (against a database), I have to update the ws_clients element for that connection to contain the new data.

Only very recent it hit me, I should also use the lock/mutex (the civetweb helper function ```
mg_lock_context(ctx);)``` to protect the writes to this structure element? But that leads to another consideration, if I need to use the mutex to write to this element I better protect (mutex/lock) all the times I'm reading from this data structure to make sure the reads are 'atomic'. For the simple numbers I can assume they are atomic, but for a long "string" or any other data that is more complex...

That would mean I'd have to encapsulate about half of the code into the mutex locks, since I'm reading from, or writing to this huge array for every (websocket) data handler. For the few (tens) connections my current application is handling, it won't make any practical difference, but it feels "wrong" to have so many mutexes/locks in place to be able to write to this shared data structure and have atomic reads.

I do need (I think?) to have data in this global array. For example, for "group chats" I cannot broadcast the message to all connected clients. I need to iterate the groups that every connected client belongs to (and those are in the ws_clients array/struct element) to make sure I'm only sending the message to the clients connected that belong to a certain group.

To end this long question, what would be a good way to go about this? How to design it so it would need a lot less locking (which defeats the point of having many threads). I have the feeling I'm going the wrong way about it, but unable to think about a better way (and a search engine is not helping me much without the proper terms).

Hoping to gain some (new) insights!

**Comment by bel2125** [comment]
There is no simple answer to this.
I would tend to say "you need to design your thread interaction model" - since I did this several times for years, and if you would be sitting right next to discuss with me, and we could share a piece of paper and draw some models.
I could tell you to read some articled, like "Some basics on pthreads can be found here: http://randu.org/tutorials/threads/" and many others

... probably not really helpful for you ...

In general, data exchange between different clients is often done with databases.
But you want to do something more real-time, right?

... also not helpful ...

If I would do chat rooms I would consider using one websocket url per chatroom.
I would do something like
http:// chat.com/index.xhtml as landing page
http:// chat.com/login.xhtml as a login form into one chatroom, sending a POST to
http:// chat.com/verifylogin.lua (.cgi) and from there either a redirect back to login (invalid password) 
or if the password was ok
http:// chat.com/<channelname>/index.xhtml to show the chat page and open the chat
ws:// chat.com/<channelname>/ws.lua (whatever websocket url)

If all the channels have different URLs, also have separated websocket states. You can send a message to all websocket clients connected to one URL, since this URL represents the group.

... this is probably not that helpful, since it does not address threading ...

But you may have seen I used a *.lua File for the ws:// URL.
Do you know the Lua programming language?
Some time ago, I implemented "Websockets for Lua" - it would allow you to implement a chat server in Lua. In this implementation, I solved these threading issues by adding client lists, queues, timers, etc. - one Lua interpreter state must only be called from one thread at a time. Every URL has it's own interpreter state.

... if it would be an option to write your chat server in Lua, I could tell you more ... 

Otherwise:
The Lua interpreter is written in C. You could have a look at how this interpreter is called, and what locks are use. You could do the same in your code.
However, this code may be more complex than you need for your application - it also implements some features you did not (yet) ask for, like timers. 

To come back to the very first part: the "design for the thread interaction model" I used for the "Websockets for Lua" implementation was indeed to use a lot of locks, so only one thread may access the list of all websockets and the websocket states at a time - this list is implemented in Lua and the interpreter must be called by only one thread a time. Then this model has another thread to do send timer events to the Lua interpreter state.

An alternative design for the thread interaction model would be to have one civetweb independent thread maintaining the web socket client list, handling all the client states and performing all send operations. All civetweb workers would only send messages to this thread using a message queue. Messages would be "add a new client", "receive data from this client", etc. You don't need explicit locks - all locks should be in the internal implementation of the message queue, and you should use an existing library for this queue.

The first model is really implemented, so I know it works. Within the short time thinking about the second model, I did not find any reason why it should not work, but I have not implemented it to really proof it will work.

... that's a too long answer now ... maybe I should think about a shorter one ...

**Comment by bel2125** [comment]
Shorter Answer:

CivetWeb offers server side Lua script support. This can also be used for websocket connections.
An example script can be found here: https://github.com/civetweb/civetweb/blob/master/test/websocket.lua
The corresponding client side code is here: https://github.com/civetweb/civetweb/blob/master/test/websocket.xhtml
Civetweb takes care about all threading issues in the Lua execution environment.

It would be simple to rewrite the websocket example above to realize a chat client.
Even if you finally want to realize it in C or C++, I would recommend doing a first prototype in Lua, based on this example.

**Comment by everte** [comment]
Thanks for taking time to type out a long answer, it's really appreciated!

It seems I have a lot of reading to do about threading, I'll use the document you linked as a starting pointer. Civetweb abstracted away enough from the threads that it didn't fully sink in that I'm doing evil things with the shared data currently.

I'm using a database for more permanent storage, but it seems a bit ridiculous to query my database for data that I have in the structure and can easily "cache". I cannot even think about a good database-driven solution for the group chat example.

The multiple websocket url's (and connections) is something that I'll give some thought. I'm not entirely convinced it would be a good solution for my current "problem", but it's something to think about when offering more data/features to keep a bit of separation between unrelated stuff and ultimately needing less global data (and thus locks).

I know that lua exists and that's about it. It seems like an easy solution, since most of the hard-work code has already been written by someone with knowledge :). Except that this is a hobby project for me and I love dabbling with C and picking up some bits and nibbles about the language. If I'd wanted the "easy" way something like node.js would have been more easy I guess. 

I'll definitely try looking at the lua sources to see how you implemented this (I hope it won't be to hard to grasp the big picture). 

Maybe a very basic question, but wouldn't be the most simple option for me be using the lock function you offer with civetweb (```mg_lock_context(ctx);```)? Would it be enough using this lock to lock the whole global data structure linked to the connections (so all the data associated with  ```mg_set_user_connection_data```). If this is the case, by just using the lock function you offer I could at least make the application "safe" again and I don't need to worry to much about the details (for now).

The last option with the queue sounds very interesting, but complicated. I'll have to think about that some more to let it sink in. Performance wise, I have no idea (or data) what would be the best/fastest, it sounds that this 1 thread sending all data would become a bottleneck. But that's only a gut feeling, without data to proof that and for me it's a non-issue ;). Enough to keep my brain busy for a while thinking how I could implement such a solution!

About your short answer, doing it first in lua seems only extra/double work but maybe I'm not smart enough to understand the benefits of doing (a prototype) first in lua. It's about killing some free time and learning, so I like the challenges (or headaches :P) C is giving.

**Comment by bel2125** [comment]
If you program mainly in C, Lua might also be worth a look.
Lua is good for tasks C is not, and vice versa.
E.g., think about how long it would take to write a parser for (Windows) INI files in C - in Lua it's 5 lines of code.


Yes, you could use mg_lock_context.
Usually you should use finer grained [locks](https://en.wikipedia.org/wiki/Lock_%28computer_science%29) for different resources for performance and reactivity reasons. One [giant lock](https://en.wikipedia.org/wiki/Giant_lock) is easier to implement, but e.g. the Linux "big kernel lock" has been removed later.
What I did with Lua is probably adding what Wikipedia would call a [global interpreter lock](https://en.wikipedia.org/wiki/Global_interpreter_lock).

Doing it first in Lua is not double work. One work you need to do anyway is to write the HTML page for the chat server. This is independent from using C or Lua at the server side.
Sending a message from one client to all others is like changing 5 lines in the Lua example script.
This way you can test the client side code.
Then you can still consider to write it in C - and you can be sure the client side already works.

My answers was based on the assumption, you want to get a working chat client as efficiently as possible - not on the assumption you want to enhance your C programming.
If you just want to experiment with threading, I would recommend doing this in an isolated project - only your main function creating two threads, using some locks, joining thread, detaching threads, ...

**Comment by everte** [comment]
Thanks for the answers (and your time!!), you provided me with all the information I was looking for. I don't think the current license would prohibit a beerware clausule if you'd ever be close ;).

My main interest is learning and enhancing my (C) programming knowledge. If I'd ever need to write something a bit faster and with less worries, I’ll look at Lua.

I've since added a few mg_lock_context calls where I should protect the whole data structure and I've added a mutex to the per client struct and I'm locking it whenever I'm reading or writing to it. It seems to be working, but it's rather hard to test and make sure it actually is working in a threaded situation that would cause issues. Time (and some more testing) will tell.

Once again, thanks for your time and great responses (and of course for this awesome piece of software that enables me to do cool stuff!).
