### ISSUE TITLE
Logically unreachable code

### ISSUE THREAD

**Issue by chhitz** [civetweb/civetweb#212]
The code at https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L3353 in the function `push()` is logically unreachable as all possible values of the variable `n` will lead to a `return` before this point.

Therefore the whole `do...while` loop is never run more than once and the whole timeout machanism seems non functional.

Is this intentional and can the "dead" code be removed?

**Comment by bel2125** [comment]
The code is currently unreachable, because the TODO some lines above (https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L3348) is not done yet.

Unfortunately, there is no quick fix - this needs to be reconsidered as a whole.
And since this dead code it is not causing any further problem, and it is not the most urgent TODO, I did not change this yet - but I will change it later.

**Comment by bel2125** [comment]
After some changes already done some months ago, the code is no longer unreachable.
(This issue has not been closed that time).

Unreachable code is also detected with coverity: https://scan.coverity.com/projects/5784
Currently there is no unreachable code.
