### ISSUE TITLE
wss not connecting?

### ISSUE THREAD

**Issue by CrackerHax** [civetweb/civetweb#226]
I am using websocket on the same ports as a http server. I can connect fine via ws, http and https, but when I try to connect wss nothing happens. I get a error code 1000 (normal disconnect). Is this broken or s there something special I have to do beyond ws/http/http to get wss to work?

**Comment by bel2125** [comment]
wss works for me without any special settings, and using the same port is standard.
Are you using the server or the client API? 
What version and OS? (Could you post the result of calling `civetweb -I`?)

**Comment by bel2125** [comment]
So civetweb is both, the server and the client?

**Comment by CrackerHax** [comment]
No, just the server.

**Comment by bel2125** [comment]
I added HTTPS support to the [embedded example](https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c). It also supports wss - just build it and start https://localhost:8843/websocket (tested with FireFox 42.0 on Windows).

**Comment by CrackerHax** [comment]
Like I said, https works fine. But websockets on the same port does not.

**Comment by CrackerHax** [comment]
Also I should probably mention I am using cpp

**Comment by bel2125** [comment]
With this example, I pushed [6 minutes ago](https://github.com/civetweb/civetweb/commit/851a4cda6bdb3e719db91efceb326dbdac46bdf2)?

**Comment by bel2125** [comment]
https and wss both use port 8843.
If built with https support, the example does not support ws but only wss, and only with this port.

**Comment by bel2125** [comment]
The CPP API is just wrapper around the C API, but C++ it is not always complete.
I did not add any websocket code to the C++ example yet.

**Comment by bel2125** [comment]
I am not really sure what you are doing - this is probably just a misunderstanding.

CivetWeb can have one or also more ports for http and ws. http and ws work on the same port, e.g., both can use port 80.
CivetWeb can have one or more ports for https and wss. Again https and wss work on the same port, e.g., port 443.
It is standard to combine http and ws on the same port.
It is standard to combine https and wss on the same port.
It is not possible to combine http and https on the same port.
It is not possible to combine http and wss on the same port.
It is not possible to combine https and ws on the same port.
It is not possible to combine ws and wss on the same port.
This is completely independent from C or C++, this is defined by the communication protocols.

So my example above uses https on 8843 and wss on 8843 - but no http or ws.

**Comment by bel2125** [comment]
I tested it with FireFox version 42.0 as a client, and it works well.
Both, server and client were on Windows and a localhost connection.

The example is a web page showing a counter. The counter is updated with a websocket connection.

If the page was loaded by http, it uses ws on the same port.
If the page was loaded by https, it uses wss on the same port.
The corresponding code is [here](https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c#L161).

**Comment by bel2125** [comment]
> When I try to connect to your example I get onclose: {"code":1006,"reason":"","wasClean":false}

Where do you get this. In the JavaScript onclose callback of the WebSocket object?
Is the client a browser?

**Comment by CrackerHax** [comment]
No, the client is highfidelity javascript.

"If the page was loaded by http, it uses ws on the same port.
If the page was loaded by https, it uses wss on the same port."

That's what I am doing, and like I said I am running https and wss together and https works fine but wss doesnt work.

**Comment by CrackerHax** [comment]
If you would like to post a wss server I could aim my client at it to test it.

**Comment by bel2125** [comment]
The [embedded C example](https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c) from earlier today is the wss server I used in my test on Windows.

I have not yet tried this example in Linux yet, but I used wss in Linux with a server side Lua script, and never had any problem.

**Comment by CrackerHax** [comment]
Yes I am running my civetweb server on Ubuntu 15. I am not using lua though, just c++.

**Comment by bel2125** [comment]
I have not tested today's example on Ubuntu - I will test it tomorrow.

But the combined C/Lua code in examples directory works on Ubuntu since more than a year.
I have a wss server running productive on Debian since more than a year (with Lua).

You could verify this by building the standard CivetWeb binaries out of the repository (`make WITH_LUA=1 WITH_WEBSOCKET=1`) and then start the server with the document root set to the test directory (`civetweb -document_root test -listening_ports 8443s -ssl_certificate resources/cert/server.pem`). Then just open https://localhost:8443 with FireFox. Open the websocket.xhtml example there. It will show a clock - the time is updated using wss.

**Comment by bel2125** [comment]
I tested the example on my Ubuntu 15.04 system, without any problem.

**Comment by bel2125** [comment]
I just discovered a problem which might be connected to this one with some version of the "QtWeb portable" browser.

The problem seems to be, "QtWeb" uses the [draft-hixie-thewebsocketprotocol-76](http://tools.ietf.org/html/draft-hixie-thewebsocketprotocol-76), while civetweb implements [the RFC 6455 standard Websocket protocol](http://tools.ietf.org/html/rfc6455).
The request header in the handshake according to the RFC contains
```
Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==
Sec-WebSocket-Protocol: chat, superchat
Sec-WebSocket-Version: 13
```
(example copied from [Wikipedia](https://en.wikipedia.org/wiki/WebSocket#Protocol_handshake)), while the obsolete draft uses something like
```
Sec-WebSocket-Key1: 8crO\J;4 136bp&m?b0441
Sec-WebSocket-Key2: 2746E 3218 \4/I2PmI |
```

Why do I think this might be connected to your case:
* I saw the highfidelity javascript implementation is based on Qt - maybe it uses the hixie draft instead of the RFC. I did not check this - could you confirm it?
* If you use a http proxy, it might translate ws from the hixie draft to the official standard, while this is not possible for https and wss. Are you using a proxy?
This might explain what you observed ... or it might be a completely different phenomenon.

**Comment by CrackerHax** [comment]
According to the documentation, as of QT5.3:

QWebSocket currently does not support extensions and subprotocols.

QWebSocket only supports version 13 of the WebSocket protocol, as outlined in RFC 6455.

Note: Some proxies do not understand certain HTTP headers used during a WebSocket handshake. In that case, non-secure WebSocket connections fail. The best way to mitigate against this problem is to use WebSocket over a secure connection.

Warning: To generate masks, this implementation of WebSockets uses the cryptographically insecure qrand() function. For more information about the importance of good masking, see http://w2spconf.com/2011/papers/websocket.pdf. The best measure against attacks mentioned in the document above, is to use QWebSocket over a secure connection (wss://). In general, always be careful to not have 3rd party script access to a QWebSocket in your application.

**Comment by CrackerHax** [comment]
It looks like websockets has a timeout problem. There is a code change review for QT 5.6:
https://codereview.qt-project.org/#/c/113026/

Not sure that's the problem though. 

Another problem we have is mac users who can't get wss to work at all.

**Comment by bel2125** [comment]
I cannot assess if the Qt issue above has anything to do with the wss connection problem, I'm not deep enough into Qt.

The protocol version issue (hixie vs. RFC) is just one idea - when I found QtWeb fails because of the protocol version, I thought this might be the case here as well.
Since I can not reproduce the issue, I can not really analyze it.

> Another problem we have is mac users who can't get wss to work at all.

By "Mac User" you mean "the server is running on Mac" or "the client is running on mac" or "the client is the Safari browser"? The Safari browser seems to change from the hixie protocol to RFC only with version 6.

**Comment by bel2125** [comment]
Does this problem still persist?
I think I can not do more without further information or a way to reproduce it.

**Comment by bel2125** [comment]
It's been several months since the last activity here, so the problem probably does no longer exist (I was never able to reproduce it). Thus, I am closing the issue now.

By the way: QtWeb (http://www.qtweb.net/download.html) still uses the old hixie draft and not the current RFC (tested with a download today).
