### ISSUE TITLE
helloworld is huge and not c++ style

### ISSUE THREAD

**Issue by hartsantler** [civetweb/civetweb#233]
following https://github.com/civetweb/civetweb/blob/master/docs/Embedding.md
takes me to: https://github.com/civetweb/civetweb/blob/master/examples/embedded_cpp/embedded_cpp.cpp

embedded_cpp.cpp is almost 300 lines of code, and most of it is written with C calls and data structures.

for example the first line of the `main` function is:
```c++
const char *options[] = {
	    "document_root", DOCUMENT_ROOT, "listening_ports", PORT, 0};
```

For programmers coming from c++11, the null byte `0` at the end looks like a bug.
Why not modify the constructor of CivetServer to also accept a `std::vector` of `std::string`?
I think this is much more readable.

```c++
std::vector<std::string> options = {
     std::string("document_root"), DOCUMENT_ROOT, 
     std::string("listening_ports"), PORT
};
```

Also, having more than two handlers is not really helpful in a hello world, the current example has 5 handlers.

Not Object Oriented
----------------------------
* `mg_printf` in the handler takes `mg_connection` as its first parameter, and second the html string.  It would be more object oriented to make mg_connection a class, with a method `write`
* `mg_get_request_info` could also be a method on an mg_connection class.
* `mg_read`

Other Ugliness
----------------------
* At the bottom of the main function is the main while loop, with an ugly macro.
```c++
	while (!exitNow) {
#ifdef _WIN32
		Sleep(1000);
#else
		sleep(1);
#endif
	}
```
* Above could be rewritten using c++11 features in just a couple lines
```c++
     while(! exitNow) {
        std::this_thread::sleep_for(std::chrono::milliseconds( 1000 ));
     }
```
* on line 191 there is this macro: `#define fopen_recursive fopen`, not sure i understand why this is required?

**Comment by hartsantler** [comment]
I just did a hello world for civetweb that's only 40 lines long, including the installer script that pulls the latest source from github and compiles civetweb as a static library.
https://github.com/rusthon/Rusthon/blob/master/examples/hello_civetweb.md

note that Rusthon takes input as markdown files, and will output the transpiled c++ and compile a native binary with g++.

My hello world would be even cleaner if `mg_printf` accepted `std::string` as the second parameter, it is ugly that i have to call `"hello world".c_str()`

**Comment by bel2125** [comment]
The civetweb core implementation is clean C (civetweb.c), and there is a C interface (civetweb.h). All features are accessible through the C interface, and all unit tests use the C interface.
The C interface can be wrapped in C++, but also in other languages.
I personally only use the C interface in productive code, never the C++ interface. 

When I took over civetweb, the C++ interface already existed. I do keep it for compatibility, I take care it still compiles, sometimes merge some added functions from contributors, and seldom add some small details. It's not my design, it's just constituent code, and I just keep compatibility and continuity.
Still, I consider the C++ interface an optional layer, based entirely on the official C interface.
I personally don't use this option. The plain C interface is more complete - there are no features in the C++ interface that would not be accessible from C.

The civetweb source code is also suitable for embedded systems. You can not always assume the latest compiler in this case - C++11 is currently far out of scope. Only yesterday, a contributor submitted a patch to get civetweb compile for GCC versions before 4.1.0 ([before February 2006](https://gcc.gnu.org/gcc-4.1/)). I tend to consider Visual Studio 2010 as the minimum for Windows, but will not reject patches for earlier versions. You can not even fully assume C++03 - C++11 did not even exist as an idea that time.

You are invited to create a C++11 interface - I can assist by answering questions and discussing concepts, but I'm otherwise busy with the C interface and implementation, and will not create a C++ interface on my own.

**Comment by jbmonroe** [comment]
People still write in C.  I have to agree with bel2125 in this case.  Back when I started writing code 35 years ago, we actually felt it was okay to fill in the gaps ourselves without demanding that everything be written in the language *du jour*.  I don't see anything stopping you from forking this and making it all C++ if that's to your liking.

**Comment by PhilLab** [comment]
@jbmonroe: forking is a questionable advice regarding this issue. A PR which improves the C++ interface is a much better one and it is not that hard :)

**Comment by jbmonroe** [comment]
All advice, at some level, is questionable. :D  I still think it's completely acceptable to produce C-style code here.  My suggestion was meant to be snarky!

**Comment by bel2125** [comment]
I stated my main focus is and will be the C implementation (https://github.com/civetweb/civetweb/issues/233#issuecomment-160330844). 
You added some C++ code (#234) - thank you for that.
Further improvements to the C++ code are welcome.

I think this issue can be closed now.
