### ISSUE TITLE
websocket connection closes unexpectedly

### ISSUE THREAD

**Issue by jin-eld** [civetweb/civetweb#236]
Hi,

I have a question regarding websocket connection handling.

I have a client UI application (JS based UI in a web browser) that needs to listen to events from a server application. The sever application integrates civetweb for http and ws communication; I have implemented the ws handlers and I can establish a connection from the web browser. 

I'd like to keep the websocket connection until the client closes it. I do not expect any input data from the client, I am only sending out messages from the server.

To keep things simple here I am testing directly from the Firebug console in Firefox:

var ws = new WebSocket("ws://localhost:50666/websocket");
ws.onmessage = function(e) { console.log("MESSAGE: ", e.data); }
ws.onclose = function(e) { console.log("WS CLOSED!", e); }

At first it looks fine, messages are coming in.

Then, what happens is, that after some time the websocket connection is closed without my programmatic interaction. At first I thought that Firefox may be doing this, but by looking at the TCP traffic in wireshark I could see that it is actually the server, who is initiating the connection teardown.

Why is this happening and how can I prevent it? Is it a "works as designed" situation or is it a bug in civetweb?

Kind regards,
Jin

**Comment by bel2125** [comment]
I think this could be a timeout (`websocket_timeout_ms`, default 30 seconds).
Can you verify if this happens always after about 30 seconds?

You can increase the timeout in a configuration.

Alternatively you could send a "still alive" message every some seconds. This would also allow the server to detect if the connection to the client is lost - not only if the client closes the connection, but also if there are problems with the connection between server and client.

**Comment by jin-eld** [comment]
Hi,

thanks for your response.

I did test it now... the timeout did indeed happen after my configured value, however making sure that the server sends out messages regularly did not help  - it will still time out after the configured timeout value. So to me it seems like the timeout calculation is not being reset after a message is sent out, is it a bug or do I need to call/do something additionally?

**Comment by bel2125** [comment]
It is actually intended this way - if the client does not send anything for a certain time, the server will consider it as dead. Sending something to the client from the server won't help, since the 'send' network socket call will not tell you the client actually received this message. This is why the timeout is not reset in this case.

The problem is, what happens if the client is gone without closing the connection properly? Consider the client is a smart phone, and it moves out of the radio reception area. The TCP socket will stay alive for several hours, blocking resources at the server. This is why I consider only a message received from the client as a sure sign the client is still there.

You might think now, you will not need this. In the beginning I thought so as well, and it was indeed not required in the "laboratory" tests within my LAN - however it was required in "field tests", in particular with mobile devices.

For the moment, just configure it to a huge value - I think 24 days is the current maximum, currently there is no value for "ininite" - I can add one later. Is this enough to start with?
Later on, if you encounter problems with gathering too many dead connections, think again on configuring this to a value reasonable for your application, and maybe send some "I'm still here" message every some minutes from the client to the server.

**Comment by jin-eld** [comment]
Thanks for the hints regarding a workaround, I still have some questions though.

Wouldn't there be an error when trying to send()/write() to a dead socket, I'd expect it to return -1? It's not UDP, so it should be able to detect if it actually could write out the data? I understand that you would not notice when you are not sending out anything, but iirc you should be able to when sending? I have to admit I did not try it right now, so I'm just thinking out loud.

Second option would be to use select and give up on this connection after a certain number of unsuccessful send retries (i.e. socket select for writing timed out X times -> probably dead) or something like that? Would that be an option?

**Comment by bel2125** [comment]
The socket is not really dead if it cannot reach the client for ... even an hour (depending on the operating system implementation of TCP). TCP is made to deal with some package losses - it will silently try to send them again without telling the upper level functions.
A successful `send` call just means "I've copied your buffer from the user application to an internal network buffer - (maybe) I will try to send it nor or later".

Think of FTP: You are transferring a huge file (1 MB in the age of dial-up modems), and some packages are lost or corrupted due to noise in a bad phone connection. TCP will silently re-transmit the corrupted and lost packages again, without telling the FTP program. Even if the connection breaks (up to a certain degree) and is re-established, TCP will still try hard to copy the file - even if it cannot transfer a single byte for some minutes, it will not tell the FTP program but just retry and retry and retry ... This is what you want from FTP. But it's not always what you want when creating a web application.

You cannot give up on unsuccessful send retries, since you do not need to retry 'send' in the application (HTTP-Server or FTP Server or Client), but the retries will occur in the network stack which is a part of the operating system. Depending on the operating system and even the operating system version, you have some options to fine tune this behavior of the network stack. Some by setting socket-ioctl commands, some by changing the Windows registry or Linux kernel parameters. Some parameters are per socket, others are system wide and will affect all applications running on this machine. But honestly, you don't want to go into this kind of fine tuning - if you ever have to do it, ask for extra compensation for personal suffering in addition to your normal salary before starting.

**Comment by jin-eld** [comment]
Well said :)

The "send something from client to server regularly" solution seems to work here, so I have a workaround, thank you.

And since it's not a bug, but a "works as designed" situation I am closing the issue.
