### ISSUE TITLE
HTTP GET with Range header fails on static file

### ISSUE THREAD

**Issue by rbenet-lbo** [civetweb/civetweb#244]
In handle_static_file_request() the call to mg_fopen() zeroes the contents of filep->size.
This leads to "Content-Range" header in the response having a length of 0   "xx-yy/0" and send_file_data() always sending the beginning of the file as offset gets truncated by filep->size.

**Comment by bel2125** [comment]
For the moment, I think it is best to remove the `memset` in fp_open.
Some day later I need to restructure this: mg_fopen should only open a file, while mg_stat should
only get the file status. They should not work on different members of the same structure (bad cohesion).

**Comment by gjm-lbo** [comment]
(I'm a colleague of rbenet-lbo.)

That seems like a change with potentially wide-ranging consequences. If you're completely sure it's safe, fair enough; but the workaround we've put in place in our local copy of civetweb is a smaller and (we hope) safer one: insert `filep->size = cl;` in `handle_static_file_request` after the call to `mg_fopen`.

This won't fix any other unfortunate consequences the memset in mg_fopen may cause -- but it also should be at less risk of introducing unfortunate consequences. Is there any obvious reason why it would be a bad idea for us?

Of course I agree that the Right Thing in the longer term is not to have these two things both operating on the file structure, one of which sets A and clears B while the other clears A and sets B.

**Comment by bel2125** [comment]
First maybe a little bit background before addressing the comment directly:

As you probably know, civetweb is a fork of mongoose, before it changed the license from MIT.
From this time, there are still a couple of functions that I personally consider hard to maintain - probably also a matter of taste, or a matter of code style that I'm used to.
So I started to rewrite some of these functions, to improve readability and maintainability of the code - one after one, highest priorities and lowest effort first.

The `memset` I removed for the quick fix was actually introduced by me while rewriting `is_file_in_memory` ([this commit](https://github.com/civetweb/civetweb/commit/16ce5bed9dd1f650ee43c6d08eabbbcf0891dc99) from September 2015).
It did not exist before - instead the `is_file_in_memory` function did reset the `filep->last_modified = (time_t)0;`

From my point of view, a function named `is_*` or `Get*` or `has_*` (and the like) must ***never ever*** change any data. It's probably a matter of taste, but I do consider this as an absolutely no-go.

However, introducing this `memset` has already lead to two follow up issues - #225 and this one (#244). #225 was solved by copying the "mg_stat" part of "struct mg_file" to ... well you can have a look on your own if you like. The main problem is that there actually ***is*** a "mg_stat" part of "struct mg_file" and a "mg_fopen" part of "struct mg_file". You may consider this "[stamp coupling](https://en.wikipedia.org/wiki/Coupling_%28computer_programming%29#Procedural_programming)", and my long term goal is to avoid this kind of coupling. However, refactoring this is a couple of days work, since `mg_file` is used a hundred times.

Now directly to your comment:

> That seems like a change with potentially wide-ranging consequences. If you're completely sure it's safe, fair enough; but the workaround we've put in place in our local copy of civetweb is a smaller and (we hope) safer one: insert filep->size = cl; in handle_static_file_request after the call to mg_fopen.
> Is there any obvious reason why it would be a bad idea for us?

The consequence is, I would reintroduce a state from September 2015, before the `is_file_in_memory` commit mentioned above. This was the state of the latest release as well. The `is_file_in_memory` change obviously was not tested well enough - we recently changed the build and test system to CMake (#94), and the Lua unit tests and automatic tests for Range headers are not ported to the new framework yet.

Your fix is not bad, and if you do not see any other problems in the tests it's perfectly fine to use it. I currently do not know of any problem your fix will cause - I'm just not sure if there is another hidden problem from the `is_file_in_memory` refactoring.

That's why my approach was - step 1: back on solid ground (the last release), step 2: improve the continuous integration test, step 3: refactor mg_fopen and mg_stat completely, to get rid of the stamp coupling, step 4: do some additional manual tests
Of course, this will take a while.

Help would be welcome here, in particular with the tests.

**Comment by bel2125** [comment]
I just had a second look: The proposed fix #225 would solve your case as well, and all other possible bad consequences of the `is_file_in_memory` change.
The only disadvantage of the proposed fix is, mg_stat is called more often than actually required - maybe a minor performance loss, but not a functional issue.

**Comment by gjm-lbo** [comment]
Sounds very sensible. We've replaced our local change with the same one you made in #225. Thanks!

**Comment by bel2125** [comment]
Is there anything else I can do to help now, or should we close this issue?

**Comment by gjm-lbo** [comment]
Closing is OK with me. If you need explicit confirmation from rbenet-lbo I'll prod him.

**Comment by bel2125** [comment]
I don't *need* explicit confirmation from the submitter - I just *prefer* to have it, as a confirmation that:
1) the submitter and the one who solved it understood the issue in the same way, 
2) the solution did solve the original problem,
3) it did not introduce any undesirable side effects in the real situation, which might be different than some isolated test case used to work on the issue

You said you are a colleague of rbenet-lbo - so you know the issue and have the same use case. 
If you say it works, that's perfectly fine for me.
