### ISSUE TITLE
Question: Has anyone implemented JWT (JSON web tokens) with in civetweb framework yet?

### ISSUE THREAD

**Issue by oldmancoyote** [civetweb/civetweb#253]
Has anyone implemented JWT (JSON web tokens) using the [JWS draft spec](http://tools.ietf.org/html/draft-jones-json-web-signature-04) within the civetweb framework yet?

JWT is a hot topic these days and one of my requirements in the near future is to use JWT.

**Comment by bel2125** [comment]
Do you mean [JSON Web Signature (JWS) - RFC 7515](https://tools.ietf.org/html/rfc7515)
or [JSON Web Token (JWT) - RFC 7519](https://tools.ietf.org/html/rfc7519) ?
Probably encrypted ([JSON Web Encryption (JWE) - RFC 7516](https://tools.ietf.org/html/rfc7516))?

**Comment by oldmancoyote** [comment]
I'll receive an incoming JWT (RFC-7519). But will that be in the form of a JWS (JSON web signature, RFC-7515) or a JWE (JSON web encryption, RFC-7516)? Will it contain an algorithm header parameter value or an encryption algorithm member – will the it be signed or not?

I suspect it will be encrypted and not signed but signed might come into play so I'll have to design for both flavors.

**Comment by bel2125** [comment]
I did not read the full RFC now, just the [Wikipedia page](https://en.wikipedia.org/wiki/JSON_Web_Token).

If I understood it correctly, JWT is just standard JSON and some base64 encoding.
Using JSON and encoding/decoding base64 is of course possible with CivetWeb.
The Wikipedia also mentions there would be a Lua implementation, so maybe it already works as a Lua server page.
Currently I do not know enough about JWT to tell exactly what it takes to claim "it support JWT".

**Comment by oldmancoyote** [comment]
The source is present so I might contribute back into master sometime in the future, for JWT/JWS/JWE.

**Comment by joshpassenger** [comment]
Did you manage to get anything going for JWT parsing and verification as I am about to implement this

**Comment by petrstehlik** [comment]
@joshpassenger I am currently using [libjwt](https://github.com/benmcollins/libjwt) which is a C implementation of JWT but I don't like the fact it requires Jansson to work.

**Comment by oldmancoyote** [comment]
Sorry, but I've been tasked elsewhere so I have not been unable to put JWT functionality into the library at this time.

**Comment by joshpassenger** [comment]
I'm not sure this specialised functionality belongs in civet anyway as it
would drag in a JSON parsing dependency as well.

The previous response was very helpful =)

**Comment by oldmancoyote** [comment]
An update to this (my) development:

Instead of implementing JSON Web Tokens into the code base, I'll be adding in just the "Basic Authentication Scheme" ([RFC-2617](https://tools.ietf.org/html/rfc2617)), which is essentially adding in the header type "Authorization" into the websocket handshake request, such as the example below:

`
Authorization:` Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==`

The 'QW...' would be a previously obtained token. I'm not sure if this would be useful for other users of this library. I can patch it in, if you believe it to be useful.

**Comment by bel2125** [comment]
I think it would be a good idea to patch in basic authorization after the next release - I plan to do this in the next days. 

However, basic auth should only be used over HTTPS, not HTTP, because the password is transmitted in "plain text" (actually base64, but that's a simple translation in both directions). Best is probably to make it configurable (forbid, allow for HTTPS only, allow for HTTP and HTTPS).

**Comment by bel2125** [comment]
This issue was orphaned for a while - basically since I did the 1.9 release December 30/January 4th.
The only topic left here was to add an API function for basic http authentication.
A similar API already exists for digest authentication: https://github.com/civetweb/civetweb/issues/426#issuecomment-326788340

But I think we should close this issue now, and not track the basic HTTP auth topics here.
