### ISSUE TITLE
Version 1.8 release date?

### ISSUE THREAD

**Issue by IanLee1521** [civetweb/civetweb#265]
Can there be a new version released? Looks like there are ~ 650 commits since the 1.7 release: https://github.com/civetweb/civetweb/compare/v1.7...master

Thanks!

**Comment by bel2125** [comment]
I originally planned to do a release after the following changes:

- Establish the CMake build (#94). <br>Well, the main C components already build with CMake, the third party components do not, and the unit tests for OS-X are also not working. But I don't know enough from CMake, OS-X and Travis to get this fixed up by myself. Although it's not fully completed, it's probably good enough as an intermediate result for a release.
- Rewriting mg_upload (#180) is finished, the tests are good up to now. This has to be part of a new release.
- Different Lua Versions, LuaJit and Duktape (#194/#195) should be tested more intensively.
- A big problem is OS-X: I don't have a Mac, and the Travis/CMake build for this system never got finished. So I do not know if the current version even compiles for Mac Systems. If it does, there is still absolutely no test. <br>In this situation, I can not release a version for OS-X.
Probably we need to discuss the OS-X release on the mailing list.


Of course, I can not fix everything in one version:

- The issues with somewhat higher effort #179, #199, #243 will have to wait for the next release.
- Some code restructuring and TODOs can also be postponed


There must not be any major open issue for a release:

- #263 just turned out, there could be a cyclic memory leak. If this is the case, it must be fixed and tested before a release.

**Comment by PhilLab** [comment]
:+1: Unfortunately I don't own a Mac so I can't help with that issue. I'm looking forward to 1.8

**Comment by kainjow** [comment]
I think the Mac issues are resolved now.

**Comment by bel2125** [comment]
Thank's a lot.
I probably should re-assess all open issues, and check again which ones are mandatory for a 1.8 release.

**Comment by bel2125** [comment]
It took a while to finish some important features, but the new release is available NOW:

https://github.com/civetweb/civetweb/releases/tag/v1.8

(Commit: https://github.com/civetweb/civetweb/commit/016535194f6dba8e534b6eec6b9d433e6fb0a9b2)

**Comment by kainjow** [comment]
Congrats :)

**Comment by IanLee1521** [comment]
Congratulations! Thanks!

/cc @cyrush
