### ISSUE TITLE
Embedding in c or c++ convenience url redirect?

### ISSUE THREAD

**Issue by kangjoni76** [civetweb/civetweb#268]
how to perform simple relative or absolute url redirect ? I saw in mod_lua.inl:lsp_redirect function was using some private mg_connection structure and then modify mg_request_info.local_uri member then lately was calling private handle_request function, and there was mg_get_request_info function. But something like mg_set_request_info function is missing. how to redirect some handler handleGet page to some another URL properly? thanks

**Comment by bel2125** [comment]
I would recommend to reply with a [redirection](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection).

```
HTTP/1.1 308 Permanent Redirect
Location: http://example.com/new

```
(or 301, 302, 303, 307, ... whatever is most suitable).

This tells the client to ask again with the URL you prefer.
This is the most flexible way to do it - the target URL might even be on a different server.

There are a couple of other ways, all of them less flexible - depending on what EXACTLY you want to do.
E.g. if your targets are all static files on the same host machine, you could use mg_send_file, ...

**Comment by kangjoni76** [comment]
My target is dynamic web if possible. I want make login form if username and password was match then I could redirect in server side logic here. 

My code like these
...
class Handler: public CivetHandler
{
	Handler(){}
	~Handler(){}
	 bool handleGet(CivetServer * ,struct mg_connection *conn)
    { 
  
      mg_printf(conn,"HTTP/1.1 303 See Other\r\n"
                "Location: http://localhost/redir\r\n");
        return 1;
    }
};

class HandlerRedir:public CivetHandler
{
	HandlerRedir(){}
	~HandlerRedir(){}
    bool handleGet(CivetServer * , struct mg_connection *conn)
    { 
        mg_printf(conn,
		          "HTTP/1.1 200 OK\r\nContent-Type: "
		          "text/html; charset=utf-8\r\n");
        mg_printf(conn,
		          "this url redir..");
        return 1;
    }
    
};
...

and my main handler looks like 
...
	const char * options[]={
        "document_root", ".", "listening_ports", "80"
        ,0};
    CivetServer server(options);
    Handler hdr;   
    server.addHandler("",hdr);
	HandlerRedir redir;
	server.addHandler("/redir",redir);
	getch();
...

this command produces
...
curl -I http://localhost 

HTTP/1.1 403 Forbidden
Cache-Control: no-cache, no-store, must-revalidate, private, max-age=0
Pragma: no-cache
Expires: 0
Date: Sat, 05 Mar 2016 02:03:23 GMT
Connection: close
...

no redirection though..

**Comment by bel2125** [comment]
I did not have the time to reproduce this yet.
But you could try the following:

After every HTTP response header, you need to add an extra `\r\n`:
```
mg_printf(conn,"HTTP/1.1 303 See Other\r\n"
                "Location: http://localhost/redir\r\n\r\n");
```
```
mg_printf(conn,
                  "HTTP/1.1 200 OK\r\nContent-Type: "
                  "text/html; charset=utf-8\r\n\r\n");
```

I never used `curl -I http://localhost` but `curl -I http://localhost/` (with an extra `/`) at the end.
This should not really cause an error, since the server should automatically redirect you to add the extra `/` - but just to exclude that please try with the `/`.

Maybe the 403 is a `Directory listing denied`. 
Please add "error_log_file", "somefile.log" to your configuration - you will find more error information in the log file.

I never tried a `server.addHandler("",hdr);` with an empty string.
If you still get a `Directory listing denied` after the changes above, the handler was not called.
The pattern matching is currently .. not ideal (see #179). 
The root should be `server.addHandler("**/$",hdr);` or `server.addHandler("**$",hdr);`

**Comment by kangjoni76** [comment]
thanks working now.
