### ISSUE TITLE
Crash when call mg_start twice with ssl enable

### ISSUE THREAD

**Issue by ocean69** [civetweb/civetweb#270]
when first call mg_start with ssl enable failed because of port inuse or may be other reason.
free_context will free ssl_mutexes. 
when next time mg_start called, 
	if (mg_atomic_inc(&cryptolib_users) > 1) {
		return 1;
	}
will let initialize_ssl return without alloc new memory for ssl_mutexes.

**Comment by bel2125** [comment]
Could you give some "steps to reproduce"?
Do you have an error log file?

Probably there is one path in the code, where the reference counting for SSI initialization does not work yet. In order to find this path, I would need to know more details. If the first SSL initialization was successful, SSL remains initialized until `uninitialize_ssl` is called. Actually `uninitialize_ssl` should uninitialize SSL and decrement `cryptolib_users`, so the condition you cited above (the `(mg_atomic_inc(&cryptolib_users) > 1)`) should be false again. So please send some additional information, so I can have a closer look.

I think that's yet another reason to add an extra `mg_init_library` function to CivetWeb, just as discussed in this thread: https://groups.google.com/forum/#!topic/civetweb/GUBn10LZXzw 
(There is another issue discussed in this google mailing list thread regarding memory leaks, which is not related to the github issue here).
This would avoid the need for fragile, maintenance-unfriendly reference counting of SSL initialization.

**Comment by ocean69** [comment]
if first Call mg_start use a port that in use.mg_start will return at civetweb.c line 12642- line 12645
	if (!set_gpass_option(ctx) ||
#if !defined(NO_SSL)
	    !set_ssl_option(ctx) ||
#endif
	    !set_ports_option(ctx) ||
#if !defined(_WIN32)
	    !set_uid_option(ctx) ||
#endif
	    !set_acl_option(ctx)) {
		free_context(ctx);
		pthread_setspecific(sTlsKey, NULL);
		return NULL;
	}
so uninitialize_ssl never be called.

**Comment by ocean69** [comment]
set_ports_option return 0.
