### ISSUE TITLE
Build error in public_server tests

### ISSUE THREAD

**Issue by jd-boyd** [civetweb/civetweb#276]
Starting with 54c6b089174c704c5d4a09e94d7537ba87ea6cf7 I get this build error:
```
In file included from /home/jdboyd/work/civetweb/test/civetweb_check.h:38:0,
                 from /home/jdboyd/work/civetweb/test/public_server.h:24,
                 from /home/jdboyd/work/civetweb/test/public_server.c:33:
/home/jdboyd/work/civetweb/test/public_server.c: In function ‘test_request_handlers’:
/home/jdboyd/work/cwb/third_party/include/check.h:476:20: error: conversion to ‘intmax_t {aka long int}’ from ‘size_t {aka long unsigned int}’ may change the sign of the result [-Werror=sign-conversion]
   intmax_t _ck_y = (Y); \
                    ^
/home/jdboyd/work/cwb/third_party/include/check.h:557:32: note: in expansion of macro ‘_ck_assert_int’
 #define ck_assert_int_ge(X, Y) _ck_assert_int(X, >=, Y)
                                ^
/home/jdboyd/work/civetweb/test/public_server.c:1082:2: note: in expansion of macro ‘ck_assert_int_ge’
  ck_assert_int_ge(i, strlen(expected_cgi_result));
  ^
/home/jdboyd/work/cwb/third_party/include/check.h:476:20: error: conversion to ‘intmax_t {aka long int}’ from ‘size_t {aka long unsigned int}’ may change the sign of the result [-Werror=sign-conversion]
   intmax_t _ck_y = (Y); \
                    ^
/home/jdboyd/work/cwb/third_party/include/check.h:492:32: note: in expansion of macro ‘_ck_assert_int’
 #define ck_assert_int_eq(X, Y) _ck_assert_int(X, ==, Y)
                                ^
/home/jdboyd/work/civetweb/test/public_server.c:1089:2: note: in expansion of macro ‘ck_assert_int_eq’
  ck_assert_int_eq(i, strlen(expected_cgi_result));
  ^
cc1: all warnings being treated as errors
```

This is on Ubuntu 15.10, AMD, compiled with GCC 5.2.1.

**Comment by bel2125** [comment]
If I add a new test, It usually does not work in the first attempt: https://travis-ci.org/civetweb/civetweb/jobs/116504327
Since I can not test all 128 configurations manually with all different compilers, I usually just try it, let the tests run and fix it in the next step.
You already fixed it for me this time - thank you.

**Comment by jd-boyd** [comment]
> Since I can not test all 128 configurations manually with all different compilers, I usually just try it, let the tests run and fix it in the next step.

My projects don't have as many configurations, but I still let travisci (and appveyor in progress) test the variations.  I do that by using pull requests for my own work so that I can see the test results before merging the work.

**Comment by bel2125** [comment]
So you use an additional branch/fork for these tests, or is there a way to do that on the local PC?

I'm using Travis, Appveyor and CMake only since a couple of months. I did not make the test setup myself (see #94), and there are still some open topics - e.g. I don't know to set up a travis build and test for MacOS and the [appveyor tests](https://ci.appveyor.com/project/civetweb/civetweb/history) fail since quite a while, and I'm not really sure how to interpret the [error log](https://ci.appveyor.com/project/civetweb/civetweb/build/398/job/kaq96h6pkm6bpup0).
So if there would be a way to debug such builds locally instead of try and error, this would certainly be helpful.

**Comment by jd-boyd** [comment]
Here is how I work on my own public github projects.

I would summarize it by saying that I treat my own work on my own github projects like I would treat another contributors work or like you treated my work on your project.

I start a branch to make my changes. I make the changes and do whatever testing I'm going to do locally (say test two versions of the language, but not all supported).  I then push the branch up to github and make a pull request from the branch.  This serves two purpose.  First, it causes travis and any other ci systems to run the more complete tests, second if anyone cared enough to be following the project, it would give them a chance to comment on my own work, which has happened when I was making changes in response to a request.  When I am satisfied, I merge it via github.

I didn't always do it that way, but getting the results of travisci running the tests before I placed the work on master provided the motivation I needed to follow that discipline.

BTW, I do appreciate the change to using CMake.

I think the only way to debug travisci's osx problem and appveyors windows problem locally would be to have a mac locally and have windows locally.  

Since the OSX testing is disabled, I can't say anything about it currently, but for the windows testing, I'll take a look at those logs.  On the surface, the failed job seems to build and just has test failures.  However, of the two jobs that run, the only difference is 32bit windows versus 64bit windows, so there seems to be a problem with 64bit windows somewhere.  I don't see yet if it is in a library or in civetweb itself.  If you don't mind, I'll start a new issue about the windows builds.

**Comment by bel2125** [comment]
I did not create a clone of civetweb/civetweb to do the development work, since this would be bel2125/civetweb - but bel2125/civetweb already exists as a link to civetweb/civetweb since this was the original name before creating the civetweb organization on github.
I don't want to do anything that might break this link.
I could use another account and take the bel2125 account only for integration and management tasks. Probably there is a different way to do this.

> I think the only way to debug travisci's osx problem and appveyors windows problem locally would be to have a mac locally and have windows locally. 

I don`t know how to execute the travis or appveyor script locally.
I could do a manual build for Win64.
However I do not have a Mac, so I can not do anything for OSX locally.
