### ISSUE TITLE
how to check during execution of request_handler() whether client has cancelled

### ISSUE THREAD

**Issue by mewalig** [civetweb/civetweb#285]
Hello,

While handling a request, how can request_handler() check whether the user has hit the "cancel" button in the browser? Would like to be able to do something like:
```
int request_handler(struct mg_connection *conn) {
  ...
  for(i = 0; i < this_will_take_a_long_time; i++) {
    if(user_has_cancelled(conn))
      break;
    ...
  }
```
Any suggestions are much appreciated. Thank you

-----
Edit: on further research it seems I have to try to write to the socket in order to determine that it is closed. I'm going to leave this issue open in case someone knows of a better way than that, but if not go ahead and close (or I will)

**Comment by bel2125** [comment]
The server will not know if someone pressed canel in the browser.

You need to write a JavaScript handler for the `onabort` event, and explicitly send a message to the browser. Maybe you want `on(before)unload` too: http://www.w3schools.com/jsref/dom_obj_event.asp

However, according to [this page](http://www.w3schools.com/jsref/event_onabort.asp), only Internet Explorer 9+ support this event, and no other browser. I don't think the other browsers will add support for this event, since the user will usually only hit the cancel button to stop the page from loading and executing scripts.

I never had the need for something like this - maybe you should solve the real problem in a different way.

If the browser, or any other client closed the connection, mg_write calls in the server will fail (sooner or later).

**Comment by mewalig** [comment]
Thanks, that's helpful
