### ISSUE TITLE
Document pattern syntax for embedded server addHandler()

### ISSUE THREAD

**Issue by joshpassenger** [civetweb/civetweb#315]
It is currently unclear if the embedded server utilises the same pattern syntax as documented for the CGI binding:

```
 **      Matches everything
 *       Matches everything but slash character, '/'
 ?       Matches any character
 $       Matches the end of the string
 |       Matches if pattern on the left side or the right side matches.

```

Can you please clarify what the syntax is in:

https://github.com/civetweb/civetweb/blob/master/docs/Embedding.md

**Comment by bel2125** [comment]
There is only one pattern matching function - it is used in every place where pattern matching is required.

It's heritage from well before 2013, and a source of recurring problems - #179 and a couple of others set to duplicate.

The syntax documentation is in https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md, 
There should be some specification of the pattern in the headed (https://github.com/civetweb/civetweb/blob/master/include/civetweb.h#L295).

Documenting the current pattern matching function will still not solve all the problems there are (see #179).

**Comment by joshpassenger** [comment]
Thank you! I was having trouble implementing a rest end point where I wanted /servicename/foo to match a list request and /servicename/foo/id to match for get requests and had these as separate handlers.

The issue was the first registered handler (list) was greedily consuming the /servicename/foo/id requests I just needed to register the list handler with a trailing '$' eg: /servicename/foo$

Problem solved.

I did a review of the c source code and was surprised to see the large number of web socket state variables and creep of scripting languages in a large number of methods (LUA etc)

These should probably be hidden away in the request context.

Additionally, polluting the main processing paths with each new scripting language is not really going to scale.

The handler architecture is quite slick if the context could be extended then everything could be done with handlers and the code would be much more succinct and maintainable.

With respect to path matching I think its OK now and changing it would not be backwards compatible as stated on the other issues.  

Regular expression path matching would be the ultimate (with some overhead and additional dependencies (I'm a C++ user)).

**Comment by bel2125** [comment]
Good to here your problem is solved.


Regarding the design issues in general:
I am not the original author of the code, just the maintainer, so many design decisions were not made by me. Sometimes I rewrite some functions to improve maintainability or optimize performance. But since the software is stable for years and compatibility is an issue, I usually take the code as it is and focus on other improvements or bug fixes.


Regarding the scale-ability when adding new scripting languages: 
I do not expect an additional built in scripting language any time soon.
On a system with proper resources, one can use CGI to call scripts in any language without extending the server directly. The builtin Lua engine in handy for embedded systems which can not use CGI (e.g, they are missing pipes or processes or don't have sufficient memory), or where heavy scripting engines like PHP can not be used (e.g, can not be easily built, don't have sufficient memory, ...). Lua can be useful on stronger system as well, since it is performing better than some scripting engine called by CGI. I added some experimental support for Duktape as an interpreter for server side javascript, since I do understand people want to use the same language the server side as on the client side (if the client is a browser).
I currently do not see any gap that would need to be filled by integrating another script engine. Furthermore, I can not add any interpreter that is not MIT licensed anyway.
The three script interfaces - CGI, Lua and Duktape - can be activated/deactivated by preprocessor defines (NO_CGI, USE_LUA, USE_DUKTAPE), so if you don't need any of them you can deactivate them at compile time so they don't cost you anything at run time (in case an #ifdef is missing somewhere, I can add it).

By the way: I usually create my REST APIs with Lua. I use Lua as a glue between the object model represented in the REST API and the internal object model of the application. During development, Lua is easier to change as C code. Later I found the Lua prototypes are efficient enough and extra flexibility to do some adaptations between the REST object model and the application object model.
This may or may not be useful for other applications as well.


Regarding a regex lib:
I can not use the C++11 standard regex library - CivetWeb is C, not C++.
The C library PCRE2 is probably larger than CivetWeb itself (and not MIT licensed).
An option could be a pattern matching like Lua with a smaller implementation but different regex patterns. This would be incompatible.
Probably this should be discussed in #179 or the google discussion group.

**Comment by joshpassenger** [comment]
Thanks for your detailed response, it makes sense now I see the history, especially around the scripting integrations (which we have turned off in the build as you indicated was possible).

I'm now comfortable using Civet for some very large projects going forward and to date I have been very impressed with its stability and performance (we have a service which has so far read many TB of large images from S3, encoded chunks of them and returned them to Java clients on demand).

Points taken on the regex libraries, this is C after all.

I think the current path matching implementation suits us perfectly, now I know how to drive it, consider this one closed.

If you need any assistance going forward I would be happy to help out.
