### ISSUE TITLE
Support HTTP2 in the future ?

### ISSUE THREAD

**Issue by sunchanras** [civetweb/civetweb#324]
Hi,
Do you have plan to support http2 in the near future?

Thanks,
Chanras

**Comment by bel2125** [comment]
I just thought about starting this discussion on the google group yesterday - but then decided to go swimming to the lake ;-)
I have to read the [RFC 7540](https://tools.ietf.org/html/rfc7540) and split the entire standard into smaller packages for implementation.

**Comment by sunchanras** [comment]
There is http2 C & C++ library here https://github.com/nghttp2/nghttp2
Thanks.
Chanras

**Comment by bel2125** [comment]
http2 seems to address performance issues for bad connections, at the cost of more complex algorithms in server and client. On the other hand, CivetWeb should stay rather small in order to run on embedded devices as well. So if http2 is added, it must be done as an optional extra module (mod_http2.inl) with a proper USE_HTTP2 preprocessor condition.
The nghttp2 contains an MIT licensed library implemented in C (not C++), so it fulfills the formal requirement that it could be included - checking it also technically will require much more time.

**Comment by benh57** [comment]
HTTP2 support would certainly be valuable for us and our use of civetweb via Ceph.

**Comment by bel2125** [comment]
It's been a while since this issue has been opened. Meanwhile I took a look at the nghttp library (https://github.com/nghttp2/nghttp2/tree/master/lib), that could be used according to the license.
I also think it's a lot more work than I expected.

Finally I found out, HTTP/2 does not solve any urgent problem for me. So my priority for this is rather low. But if someone is willing to implement it, I will certainly merge it. Otherwise it will take some time until we have it here - from my priorities, I will deal with some other topics first.

**Comment by Astaelan** [comment]
I would like to revitalize the interest in HTTP/2 support. As time continues to pass, adoption of HTTP/2 is becoming a little bit more popular. It would be nice to be on the front of this wave.
I do not believe the @bel2125 should redirect any major amount of time to this with any outstanding issues on the core, but as the product matures I think HTTP/2 should be revisited.
I am receiving some end-user pressure about the support for HTTP/2 on application services down the line.

**Comment by bel2125** [comment]
Now, V1.10 is released, and it's probably time to discuss content for V1.11 (and maybe V1.12).

HTTP/2 optimizes network traffic on the cost of CPU power and memory consumption at the server. It compresses headers, allows parallel channels on the same socket connection, ... but the server needs to store more session specific data and run more complex code.

For applications with strong server hardware, dealing with a lot of clients connected from the internet, HTTP/2 is certainly a nice improvement (in this respect, a modern PC is already a strong hardware).

There are other applications like server on embedded devices, dealing with a small number of clients in an isolated network - think of the HTTP interface of the weather station on my windowsill. In these cases, I think HTTP/2 isn't worth the additional effort, hardware requirements, ... Also HTTPS isn't used here. So there are applications, where HTTP/2 support is unwanted.

So HTTP/2 must be optional, just like TLS support or Lua support.

And there is also the question if we make a HTTP/2 implementation here, or add an interface to an existing one, that could be used like a third party component (like OpenSSL or the Lua interpreter).

**Comment by Astaelan** [comment]
Yes, I would agree. The HTTP2 support should be an optional thing, so that systems which do not wish to have it enabled at all can experience little or no additional overhead.
It might be nice to also have the option to enable it in the code, but disable it through configuration options so that the same library or application using it can be used across different needs, for example if multiple instances are started.

**Comment by bel2125** [comment]
V1.13 and V1.14 support some parts of HTTP/2 when built with USE_HTTP2.
They can answer HTTP/2 requests from a Web browser (Chrome, Firefox, ...).
Missing: support for parallel requests on the same connection and handling file upload (POST requests), but these features will be tracked with different issues.
