### ISSUE TITLE
mg_send_file filename

### ISSUE THREAD

**Issue by grunk** [civetweb/civetweb#325]
Hello,

I'm trying to let a user download a file from a handler.
I'm using the following code : 

```
const char *fileName = "test.avi"
mg_send_file(conn, fileName);
```

When i call my handler http://localhost/download , the downloaded file is called download.avi.

Is there a way to specify a filename without modifying civetweb source ?

I managed to specify a file name by adding `Content-Disposition: attachment;filename=myfile.avi\r\n` in `handle_static_file_request()` but i'd rather avoid modifying my civetweb source.

Any solution ?
Thanks

Note : I'm currently running civetweb 1.7

**Comment by bel2125** [comment]
So your handler looks like the one in the example:
https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c#L186

In Version 1.8, an additional parameter has been added to specify the MIME type independent from the file name extension:
https://github.com/civetweb/civetweb/blob/master/include/civetweb.h#L604

But there is currently no additional parameter to set the Content-Disposition (according to [RFC 6266](https://tools.ietf.org/html/rfc6266)). Probably this should be added, but with the `filename*` field instead of `filename`, to allow also non-ISO/IEC 8859-1:1998 (Latin alphabet) characters. It would be something like `filename*=UTF-8''%c2%a3%20and%20%e2%82%ac%20rates`, according to [RFC 5987](https://tools.ietf.org/html/rfc5987).
Maybe there are other headers missing as well, that should be added.

The only chance for V1.7 not to change the `civetweb.c` source would be to use mg_write in the handler directly. You would first have to send all the headers, then read the file chunk-wise and call mg_write in a loop, similar to what is done in `send_file_data` (currently [here](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L6754)).

**Comment by grunk** [comment]
Thank you,
I 'll probably go with writing everything with `mg_write` then.
