### ISSUE TITLE
Port does not bind to ipv6

### ISSUE THREAD

**Issue by makrsmark** [civetweb/civetweb#326]
If the civet port is set to "8080" it will only bind to ipv4 interfaces. I would expect it to bind to both ipv6 and ipv4 interfaces. The workaround is to set the port to "[::]:8080" which binds to both ipv6 and ipv4 interfaces.

It makes more sense to have the following behavior:
8080 - bind to all ipv6 and ipv4 interfaces
0.0.0.0:8080 - bind to all ipv4 interfaces only
[::]:8080 - bind to all ipv6 interfaces only

**Comment by bel2125** [comment]
8080 binds to IPv4 - probably since more than a decade. Changing this would break compatibility in this respect.

[::]:8080 binds to IPv6 only, and IPv6 is optional (see [this code section](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L10758)). The `IPV6_V6ONLY` option makes it bind only to the IPv6 port and not to the IPv4 port. The [documentation](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md) (section `listening_ports`)  is not entirely correct.

If you want to bind to both, you need to specify 8080,[::]:8080 (this might be a bit odd, indeed - but it gives you full control). At least it works this way in my test environments - some systems ignore `IPV6_V6ONLY` and/or somehow bridge between IPv4 and IPv6.

I am basically maintaining the configuration [created in 2004](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L2) (initially for IPv4 only).

Setting the default to IPv6 might lead to one problem: On systems with IPv6 deactivated (by the admin), it will not be possible to create/bind to a IPv6 socket. Thus, starting the server will fail, while before it worked by just using the IPv4 address. Changing the default here is not "nobody notices it anyway".

Still something should be done here:
- [ ]  Clarify the documentation
- [ ]  Find something shorter and more intuitive than `8080,[::]:8080` if both IPv? are used.

**Comment by makrsmark** [comment]
Looks like I need to test in a real ipv6 environment. I can access my server via 127.0.0.1 and [::1] despite using only the ipv6 declaration. Windows says it honors the IPV6_V6ONLY flag but they could be wrong.

I would argue changing the semantics of a raw port string is "nobody notices it anyway" because ipv6 must be explicitly enabled as a preprocessor definition, but I can understand your decision.

Thanks for the help!

**Comment by bel2125** [comment]
The short notation for using IPv4 and IPv6 will be an additional + sign in the configuration.
So:
- `80` still means port 80 IPv4 only.
- `+80` means port 80 IPv4 and IPv6 (one socket for both). (*new !*) 
- `[::]:80` means port 80 IPv6 only.
- `80,[::]:80` means port 80 IPv4 and IPv6 (one socket for IPv4, one for IPv6 only).

Also the documentation should be much clearer now. Still everyone needs to test what configuration works best, since the IPv6 network environments might be quite different.
