### ISSUE TITLE
bug: protect against directory disclosure attack 

### ISSUE THREAD

**Issue by hcp24** [civetweb/civetweb#327]
The function **remove_double_dots_and_double_slashes** does not realy wok if the first characters are double dots. You shold change it like:

static void
remove_double_dots_and_double_slashes(char *s)
{
    char *p = s;
    // insert this
    while (  s[0] == '.' && s[1] == '.')  s++;

   while ( *s != '\0') {
      ....
  }
} 

if you use file names with double or more dots at start we have little bit more work.

**Comment by bel2125** [comment]
I don't think there is a disclosure in the moment - a request to `..` will fail in `process_new_connection` with error "Invalid URI: [..]". For a request to `/..` there is already a `/` in the beginning, so the first character is not a dot. If the first character is not a `/` the request is not valid anyway.

**Comment by bel2125** [comment]
I could not find a way to exploit the .. at the begin of the string, since an URL like that will be rejected much earlier and never pass till the remove_double_dots_and_double_slashes. Still I changed the remove_double_dots_and_double_slashes function according to your suggestions, so if there is ever a way to call it with leading .. it will work.
