### ISSUE TITLE
Bug: civetweb 1.8 if we set request_time_out to 0

### ISSUE THREAD

**Issue by xR3b0rn** [civetweb/civetweb#330]
For now I have used civetweb 1.6, but updateting civetweb 1.6 to civetweb 1.8 leads to an confusing error.
Cause in read_request in civetweb.c the request_time_out parameter gets queried by

```
    if (conn->ctx->config[REQUEST_TIMEOUT]) {
        /* value of request_timeout is in seconds, config in milliseconds */
        request_timeout = atof(conn->ctx->config[REQUEST_TIMEOUT]) / 1000.0;
    } else {
        request_timeout = -1.0;
    }
```

So although when my request_time_out parameter is "0", the if continues inside.
Normally the programm shouldn't cause now request_timeout gets set to 0 instead of -1.0 what makes the server to close unexpected the connection.
Without an change in the sourcecode I am not able to set the request time out to infinity.

Julian

**Comment by bel2125** [comment]
Do you really need an "infinite" connection or just a "very long"?

---

There story behind the change is somewhat lengthy:

Initially, whatever value was configured was set as a socket timeout (in `set_sock_timeout`). This might be the case in 1.6 (I did not check it now, maybe it was somewhat earlier). 
The problem was, the server could not be stopped until all open connection have been closed. This is not much of a problem if you only serve small pages in high speed networks and do not use keep-alive. However, when websocket connections are used, long polls, unlimited keep-alive, ... server and client might keep the connection open for a long time. So when stopping the server, you had to wait - maybe for hours. 
The server could only exit earlier, if the connection was closed by the socket timeout. See https://github.com/civetweb/civetweb/issues/77.
The solution was to set the timeout to a value not longer than 10 seconds and loop if the configuration set a higher value. The 10 seconds constant was then replaced by the SOCKET_TIMEOUT_QUANTUM define (a constant value of 10 seconds, but with the option to override it when compiling the server). This made finite numbers work, while the server would still exit within ~SOCKET_TIMEOUT_QUANTUM seconds. Probably this time infinite was changed from 0 to -1, or to a month (2^32-1 ms) or so. Anyway, if 0 is used as infinite, what is used as 0? However, this solution made other problems (https://github.com/civetweb/civetweb/issues/184, https://github.com/civetweb/civetweb/issues/82 and others).
So finally from 1.8 to the 1.9 (currently work in progress), the SOCKET_TIMEOUT_QUANTUM has been removed again, and the entire shutdown logic is rewritten.

**Comment by xR3b0rn** [comment]
0 is the standard number on Windows to say, you want no timeout, so I thought it does make sense. I was looking for a possibility to ping my client from the civetweb-srever without starting a new thread (like in the civetweb-example), but I hadn't found something, so I decieded to set the timeout to infinity i.e. I need the infinity timeout.

**Comment by bel2125** [comment]
In the "Websocket for Lua" example ([this client side](https://github.com/civetweb/civetweb/blob/master/test/websocket.xhtml) and [this server side script](https://github.com/civetweb/civetweb/blob/master/test/websocket.lua)), I send a message from the server (the client thread) to the client (browser) every second. Is this what you mean? The example is in Lua, but it can be done in C as well.

Regarding 0 as infinite:
At least the very basic Windows API function ([wait functions](https://msdn.microsoft.com/en-us/library/windows/desktop/ms687032(v=vs.85).aspx)) use 0 as 0 and a different constant  INFINITE (-1 u). Pthreads use even a different function for intinite time ([cond_wait / cond_timedwait](http://linux.die.net/man/3/pthread_cond_wait)). I think 0 is more consistently used as "don't wait, just take what's ready now".

**Comment by xR3b0rn** [comment]
lua directly invoke timer_add, so why timer_add in timer.inl isn't a symbol in a header instead of being static in an .inl? Do I have to include timer.inl and include each of the dependencies of timer.inl?
Never saw this pattern before (what doesn't mean anything).

**Comment by xR3b0rn** [comment]
I solved the problem by removing the static before add_timer in the timer.inl and adding that to my cpp:
```
extern "C"
{
	typedef int(*taction)(void *arg);
	int timer_add(struct mg_context *ctx, double next_time, double period, int is_relative, taction action, void *arg);
}
```
Now I am able to add timers with:
`timer_add(mg_get_context(pConn), 1, 1, 1, callback_timer, pConn);`
And ping my Client with:
```
int callback_timer(void* pData)
{
	mg_connection* pConn = reinterpret_cast<mg_connection*>(pData);
	mg_websocket_write(pConn, WEBSOCKET_OPCODE_PING, NULL, 0);
	return 1;
}
```
So I have 1 more Thread handling all my timers, when I understood the code correctly.
But I still hate it to change library code...

**Comment by bel2125** [comment]
Timers were mainly written for Lua - maybe some modifications are needed to make them run for C as well. I did not consider C as so important, because: The timer implementation in CivetWeb is a very simple cross platform code, not necessarily the most efficient. If your code does not have to be cross platform, or you already have some other cross platform framework, you will not really need this timers in C but might wish to use the native platform timers (Windows multimedia timer or timer messages, posix timers) or the timers from your framework (QTimer ... whatever) - most likely you do not need an extra thread, and it's more efficient.

So if you have a different way to realize cyclic messages from the server to the client in your application, maybe it is already suitable. Otherwise one could also export the timers API with some mg_* prefix.

I'll be on vacation for 10 days now, we can discuss more details afterwards.

**Comment by xR3b0rn** [comment]
The executable shall be as small as possible. So the timer mechanism is neccessary but a new lib were over powered. But I understand: I either have to change your lib code or implement my own timer mechanism.
Thank you a lot.

**Comment by bel2125** [comment]
If you do not need cross platform code, but stick to either Windows or Linux, you already have a timer mechanism. If you need cross platform code, and use some other (major) cross platform library (not only ANSI C), you most likely already have a timer as well. 
For this reasons, I thought up to now there would be no need to use my timer mechanism outside, so the functions are static and there is no interface. But if there is indeed need, I would also consider to add it to the public interface as auxiliary function (like the function for creating a thread).

Of course you are free to use my timer mechanism and modify it yourself - the MIT license allows this, but there is no guarantee it works. It the only thing you need is a public interface to what already exits, I can add this (I will queue this on my TODO list).

**Comment by bel2125** [comment]
Most of this issue was already solved in summer, the only missing piece was a way to use the timers outside of civetweb.c (and that's probably another issue - for the moment one can set a TIMER_API define).
