### ISSUE TITLE
mg_send_mime_file: mg_fopen overrides everything set by mg_stat

### ISSUE THREAD

**Issue by PhilLab** [civetweb/civetweb#333]
In [handle_static_file_request](https://github.com/civetweb/civetweb/blob/5545a43c18daef7226fde66a942f7051d7aa3988/src/civetweb.c#L6925), `mg_fopen` is used to check whether the file is open.

But this leads to the `filep` variable being reinitialized ([in this line](https://github.com/civetweb/civetweb/blob/5545a43c18daef7226fde66a942f7051d7aa3988/src/civetweb.c#L1874)).

This means that the `last_modified` timestamp set in `mg_stat` and used in `construct_etag` is always set to zero.

*As a result, the call to `mg_stat` is without any effect*

**Comment by bel2125** [comment]
From my point of view, `mg_fopen` and `mg_stat` should not work on the same data structure.
This is something I disliked from the very beginning - after a while I created an issue: https://github.com/civetweb/civetweb/issues/246
It turned out, there are a lot of un-obvious connections between functions working on the FILE * part and functions working on the stat part, in particular when it comes to files in memory. So after trying for several hours to split this interdependence, I postponed this for a not yet defined time.

But this is probably just another effect of #246.

**Comment by bel2125** [comment]
Addressed with #246 later. (set as duplicate).

**Comment by PhilLab** [comment]
okay, therefore closed

**Comment by bel2125** [comment]
The functions causing this problem have been completely rewritten, eliminating the root cause for this and some related problems. I get a 304 in my tests now.
(Identical issue to #363 - removing "duplicate" mark since issue is closed)
