### ISSUE TITLE
wss client error: SSL is not initialized

### ISSUE THREAD

**Issue by motomuman** [civetweb/civetweb#335]
I call mg_connect_websocket_client with use_ssl = 1. 
This fail with message "Error: SSL is not initialized".

If I call mg_start with ssl_certificate option before I call mg_connect_websocket_client with use_ssl = 1, mg_connect_websocket_client success.

I'm writing the code of wss client and wss server which will run in other machines.
How can I run only wss client?(without mg_start with ssl).

**Comment by bel2125** [comment]
This is a known issue.
The SSL initialization is done in mg_start. There is [some discussion](https://groups.google.com/forum/#!topic/civetweb/GUBn10LZXzw) to split the initialization into 'init_library' and 'mg_start' (instead of only mg_start) and to do the SSL initialization and the WinSock initialization (for Windows only) in init_library. This would solve your problem as well.
Currently, if you have a pure client application, you would have to initialize SSL (and WinSock) on your own before calling any CivetWeb client function.
That's not nice, but currently the only way.

The 'init_library' idea is not implemented yet - but I guess I'll have to do this soon (~ September).

**Comment by motomuman** [comment]
I think usually client run different program from server program, so If we have init_library API, this would be really useful.
For the time being, I initialize SSL before call client function.

Thank you for your help.

**Comment by AndreyArsov** [comment]
hi, can you share some insight/code on how SSL is initialized before creating client connection? I tried calling initialize_ssl in civetweb directly, but this is not enough.
It seems that most of the stuff in set_ssl_option should called, but one needs a mg_context for which one can use common_client_context.

**Comment by bel2125** [comment]
In the current version (1.11 .. in progress), you should call `mg_init_library(MG_FEATURES_TLS);`

This is also checked in a unit test: 
https://github.com/civetweb/civetweb/blob/2428ade5108d67f16a5896b355458abcde13e184/test/public_server.c#L4584

This was a recent change - it was not sufficient for the last release version 1.10 from end of August.

**Comment by bel2125** [comment]
Another recent enhancement ... in progress ... is to add an API to provide an external SSL context - see https://github.com/civetweb/civetweb/issues/526. But this is related to the server, not to the client API (this issue was initially created for the client API).

**Comment by bel2125** [comment]
The HTTPS client API "always" worked, if a HTTPS server was initialized first (with `mg_start` and a secure `listening_port` and `server_certificate`).

**Comment by AndreyArsov** [comment]
Thanks, got the new version and it seems to work, i.e. ssl is initialized and one can start getting data.
In some cases however I see the following timeout:
```
static int
pull_all(FILE *fp, struct mg_connection *conn, char *buf, int len)
{
	int n, nread = 0;
	double timeout = -1.0;
	uint64_t start_time = 0, now = 0, timeout_ns = 0;

	if (conn->ctx->config[REQUEST_TIMEOUT]) {
		timeout = atoi(conn->ctx->config[REQUEST_TIMEOUT]) / 1000.0;
	}
	if (timeout >= 0.0) {
		start_time = mg_get_current_time_ns();
		timeout_ns = (uint64_t)(timeout * 1.0E9);
	}

	while ((len > 0) && (conn->ctx->stop_flag == 0)) {
		n = pull_inner(fp, conn, buf + nread, len, timeout);
		if (n == -2) {
			if (nread == 0) {
				nread = -1; /* Propagate the error */
			}
			break;
		} else if (n == -1) {
			**/* timeout */
			if (timeout >= 0.0) {
				now = mg_get_current_time_ns();
				if ((now - start_time) <= timeout_ns) {
					continue;
				}
			}**
			break;
		} else if (n == 0) {
			break; /* No more data to read */
		} else {
			conn->consumed_content += n;
			nread += n;
			len -= n;
		}
	}

	return nread;
}
```

Does one need to specifically set the timeout parameters on the connection?

**Comment by bel2125** [comment]
For the client API, currently you cannot specify a timeout.
This would need some incompatible interface revision - that's already tracked here: #479

I would like to keep this issue here focused only on the client SSL initialization. While other client issues (like the timeout) should be tracked in different issues.

**Comment by bel2125** [comment]
The current version V1.11 has an interface to initialize the civetweb library and, hence, the client function without starting a server (mg_init_library) - actually V1.10 had that function as well.
