### ISSUE TITLE
Build for OSX failing for ws_server example

### ISSUE THREAD

**Issue by saumitravikram** [civetweb/civetweb#352]
Build is failing on OSX for ws_server due to 3 errors.Snippet from build
```
ac87a336e29f:ws_server saumitv$ make all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../.. clean lib WITH_WEBSOCKET=1
rm -rf out
rm -rf libcivetweb.a
rm -rf libcivetweb.so
rm -rf libcivetweb.so.1
rm -rf libcivetweb.so.1.9.0
rm -rf civetweb
rm -f civetweb_test
cc -c -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -O2 -DOSX -Iinclude  -DUSE_STACK_SIZE=102400 -DNDEBUG -DUSE_WEBSOCKET -fPIC src/civetweb.c -o out/src/civetweb.o
ar cq libcivetweb.a out/src/civetweb.o
cp ../../libcivetweb.a .
cc -o ws_server -I../../include   ws_server.c libcivetweb.a -lpthread
ws_server.c:255:15: error: no member named 'websocket_connect' in 'struct mg_callbacks'
    callbacks.websocket_connect = websocket_connect_handler;
    ~~~~~~~~~ ^
ws_server.c:256:15: error: no member named 'websocket_ready' in 'struct mg_callbacks'
    callbacks.websocket_ready = websocket_ready_handler;
    ~~~~~~~~~ ^
ws_server.c:257:15: error: no member named 'websocket_data' in 'struct mg_callbacks'
    callbacks.websocket_data = websocket_data_handler;
    ~~~~~~~~~ ^
ws_server.c:258:32: warning: incompatible pointer types assigning to 'void (*)(const struct mg_connection *)' from 'void (struct mg_connection *)' [-Wincompatible-pointer-types]
    callbacks.connection_close = websocket_close_handler;
                               ^ ~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 3 errors generated.
make: *** [ws_server] Error 1
ac87a336e29f:ws_server saumitv$ 
```
This is due to the fact the MG_LEGACY_INTERFACE for websocket are not available.
I checked the makefile and I can see we are only enabling MG_LEGACY_INTEFRACE only when OS is Linux.
```
ifeq ($(TARGET_OS),LINUX)
        LIBS += -ldl -DMG_LEGACY_INTERFACE=1
endif
```

I have verified the example is working for OSX when we enable MG_LEGACY_INTERFACE.

Thus the Makefile can be modified to enable MG_LEGACY_INTERFACE for OSX also.

**Comment by saumitravikram** [comment]
Warning message can also be fixed by adding 'const' in function declaration of websocket_close_handler

```
static void websocket_close_handler(const struct mg_connection *conn)
```

**Comment by bel2125** [comment]
I do not have an OSX system available, so I cannot test any example in OSX. All examples are only maintained for Linux and/or Windows, and some older examples are no longer maintained at all.

The ws_server example is an obsolete one. It has not been changed since more than 2 years.
The recent websocket server example is in [embedded_c](https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c#L467).

Probably the example should be marked as deprecated/no longer maintained.

**Comment by saumitravikram** [comment]
Hi the example is as of now not marked as deprecated.

Since it was first time i was getting hand on with the codes so i thought to go through each example to understand the core structure and working of the civetweb code.

Thanks

**Comment by bel2125** [comment]
There are several old files in the repository that are mainly kept for reference - often in a state of "partially relevant". I agree this is not ideal, since you can not know when you start with the code.

In the last two years I merged almost all examples into the `embedded_c` example.
So this is the one you should start with - it's the only example that gets extended somewhat regularly.
The `example_cpp` example also works, but the C++ interface of civetweb is just a subset of the C interface and adds no additional features, so this example also shows only a subset of features possible with the C interface. All other examples are more or less legacy.

Also the test directory contains some legacy tests.

**Comment by saumitravikram** [comment]
Thanks for heads up.
