### ISSUE TITLE
Opening connection to a remote host

### ISSUE THREAD

**Issue by DisjointTech** [civetweb/civetweb#359]
Hello all,
Can someone please tell me what am I doing wrong here:

```
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "civetweb.h"

void connect_host(char *host, int port)
{
        char errbuf[100];
        struct mg_connection *conn = mg_connect_client(host, port, 0, errbuf, sizeof(errbuf)); 

        if (conn == NULL) {
                printf("[*] Errbuf: %s\n", errbuf);
                return;
        }

        char buf[10000] = "GET / HTTP/1.1\r\nUser-Agent: C\r\n\r\n";
        int byteSent = mg_write(conn, buf, strlen(buf));  // I think connection is closed after this line
        if (byteSent <= 0) {
                printf("[+] req not sent: %d\n", byteSent);
                return;
        }

        bzero(buf, sizeof(buf));   // fill buf with zeros
        mg_read(conn, buf, sizeof(buf));
        printf("[+] reply:\n%s\n", buf);  // empty buf
}

int main(int argc, char **argv)
{
        int port = atoi(argv[2]);
        connect_host(argv[1], port);

        return 0;
}
```

The first argument is the hostname or ip address to connect to, and the seconde argument is the port number to connect to.
I've noticed that a "FIN"(asking to close the connection) packet is sent right after sending the request buffer to the remote host--when I was monitoring the traffic with wireshark.
Thanks in advance!

**Comment by bel2125** [comment]
Already solved the problem on your own? (Since it is already closed),

You can find some examples in the /examples/embedded_c and /test/public_server

By the way, `"GET / HTTP/1.1\r\nUser-Agent: C\r\n\r\n"` is not fully HTTP/1.1 compliant. The User-Agent header filed is optional and can be ommitted, but a `Host: www.something.net` header field would be mandatory. Currently, the civetweb server does not really care if this field is missing, but if you want to
