### ISSUE TITLE
Incorrect value for HAVE_STDINT (result in compile error)

### ISSUE THREAD

**Issue by matanshukry** [civetweb/civetweb#365]
I'm using Urho3D, which uses this project (civetweb).

However when building when mingw, it seems this line in cmake:
```check_include_files(stdint.h HAVE_STDINT)```
result in ```false```, since  later on the file ```stdint.h``` isn't being included.

The actual problem though, is that the ```#else``` branch doesn't contains typedef for 'uintptr_t', which is used, and hence I'm getting a compile error on undeclared type.

Reference:
https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L406

**Comment by bel2125** [comment]
There is actually a continuous integration (CI) test on AppVeyor, using with CMake and MinGW - it does not have any issue with `stdint.h` there. The GCC version used by the AppVeyor Windows build images is [5.1.0](https://ci.appveyor.com/project/civetweb/civetweb/build/701/job/lqork3lprisaps3p#L196) (in this link, the build worked, but there is a problem in the test I'm currently looking at). So, there is no principal issue with MinGW, since it works on AppVeyor.
Obviously your MinGW installation must be somehow different than the one on AppVeyor - I think I cannot really help finding this difference.

Anyway, I think this HAVE_STDINT is a relic of old Visual Studio versions (before 2010). Today I would just claim <i>"you **have to** HAVE_STDINT"</i>, (maybe from [msinttypes](https://github.com/chemeris/msinttypes), or from anywhere else). 
So if it is required to change something in the way CivetWeb uses `HAVE_STDINT`, it would be to remove it completely and assume stdint,h exists and is standard compliant.

**Comment by bel2125** [comment]
I removed the "HAVE_STDINT" completely: Now stdint.h is simply required - 17 years after this has been added to the standard, I think this kind of define is no longer required. If someone still uses an old toolchain without stdint.h, he has to patch the toolchain and add stdint.h by himself.

**Comment by bel2125** [comment]
Since <stdint.h> is no longer optional in version 1.9 and later, all HAVE_STDINT related problems should be solved now.
