### ISSUE TITLE
SSL/TLS broken with OpenSSL >= 1.1

### ISSUE THREAD

**Issue by kakwa** [civetweb/civetweb#370]
It seems that OpenSSL breaks its API with version 1.1.

When I try to start civetweb with SSL/TLS, I get the following error:
```
load_dll: libcrypto.so: cannot find CRYPTO_num_locks
```

Environment:
* OS: Debian sid
* civetweb: v1.8
* OpenSSL version:  1.1.0c-2

**Comment by bel2125** [comment]
Debian sid is currently the unstable version, so I did not take a look at it yet.

It seems there are several incompatible changes (https://wiki.openssl.org/index.php/1.1_API_Changes), so probably there are more things that need to be changed.

But `CRYPTO_num_locks` is just the first of 20 symbols imported from libcrypto, and I did not find any indication this particular symbol does no longer exist in OpenSSL 1.1. Maybe it does not find any symbol there. 

Could you check `objdump -T /usr/lib/x86_64-linux-gnu/libcrypto.so` (or wherever libcrypto.so is located in debian sid)?

**Comment by kakwa** [comment]
That's okay, Debian packages the 1.0 and the 1.1 versions anyway, and seeing the extent of the API break, it will stay that way quite a long time, I just thought it's interesting to be notified of such breaks early ^^.

```objdump -T /usr/lib/x86_64-linux-gnu/libcrypto.so``` result:
https://gist.github.com/kakwa/28f38efc3865173f946580de395a432a

**Comment by bel2125** [comment]
The windows build now sporadically fails with a SegFault.
It seems the reason is `bn_bn2hex` in `ssl_get_client_cert_info`: According to https://linux.die.net/man/3/bn_bn2hex, strings returned from bn_bn2hex must be freed using OPENSSL_free, not mg_free. But OPENSSL_free did not exist in earlier versions - at least I did not find it in the 1.0.0 documentation, 

My earlier version used `i2c_ASN1_INTEGER`, and did not use memory allocated from openssl at all:
https://github.com/civetweb/civetweb/pull/384/files#diff-942b175a4f5673b8f0ce6c0ab2fc2932L11861

What do you think: Should we use the old code here, or add OPENSSL_free? Do you know when OPENSSL_free was added? Do you know if equivalent functions are available in other TLS libraries, e.g., for those who do not use OPENSSL but the OPENSSL-compatibility of GnuTLS or yassl?

**Comment by lammertb** [comment]
OPENSSL_free was introduced in OpenSSL version 0.9.6 which was released about 15 years ago. They may have changed the code in the background recently though which causes the current segfault. Personally I would go with the OpenSSL provided version of free() because if MEMORY_DEBUGGING is set when compiling Civetweb, mg_free_ex() will segfault on any memory not allocated with one of the mg_ allocation functions.

**Comment by bel2125** [comment]
Thank you, I just found it as a define to "CRYPTO_free" - in earlier version it was defined as "free".

Since civetweb can dynamically import the openssl function, we probably need a "if version < something use free else use CRYPTO_free" - I will check it.

**Comment by bel2125** [comment]
In OpenSSL, it seems OPENSSL_free is CRYPTO_free for at least 10 years.
In wolfSSL/yassl it's just free (https://fossies.org/linux/yassl/include/openssl/ssl.h),
In GnuTLS, I did not find this function (https://gitlab.com/gnutls/gnutls/blob/master/extra/includes/gnutls/openssl.h / https://www.apt-browse.org/browse/ubuntu/trusty/main/i386/libgnutls-dev/2.12.23-12ubuntu2/file/usr/include/gnutls/openssl.h / https://github.com/x2on/GnuTLS-for-iOS/blob/master/include/gnutls/openssl.h). 
But using CRYPTO_free seems to work in the tests.

**Comment by bel2125** [comment]
I think we can close this issue now:
There is a define "OPENSSL_API_1_1", it's tested in [a unit test](https://github.com/civetweb/civetweb/blob/master/.travis.yml#L255) - ([result: OK](https://travis-ci.org/civetweb/civetweb/jobs/199423484)).

**Comment by kakwa** [comment]
That's OK with me, do you want to close it or should I do it?

**Comment by bel2125** [comment]
Thank you for your contribution.
I will close the issue.
