### ISSUE TITLE
How to execute the sample code of .lua in civetweb ?

### ISSUE THREAD

**Issue by PaulTsai20160627** [civetweb/civetweb#373]
Hi ALL:

I tried to learn how to execute the .lua file by typing the script:

lua xxx.lua then press Enter,

it always shows the following messages:

paultsai@paultsai-VirtualBox:~/civetweb$ lua lua_example2.lua
lua: lua_example2.lua:1: attempt to index global 'mg' (a nil value)
stack traceback:
	lua_example2.lua:1: in main chunk
	[C]: in ?
I do not know  how to deal with this issue  !

lua sample code :
```
mg.write("HTTP/1.0 200 OK\r\nContent-Type: text/html\r\n\r\n")

mg.write([[
<html><body>
<p>This is another example of a Lua script, creating a web page served by the
<a href="http://sourceforge.net/projects/civetweb/">Civetweb web server</a>.
</p><p>
The following features are available:
<ul>
]])

  mg.write("<li>" .. _VERSION .. " server pages</li>")
  if sqlite3 then
    mg.write("<li>sqlite3 binding</li>")
  end
  if lfs then
    mg.write("<li>lua file system</li>")
  end


mg.write("</ul></p>\r\n")
mg.write("<p> Today is " .. os.date("%A") .. "</p>\r\n")
mg.write("<p> URI is " .. mg.request_info.uri .. "</p>\r\n")

mg.write("<p>Database example:\r\n<pre>\r\n")

  -- Open database
  local db = sqlite3.open('requests.db')
```

**Comment by bel2125** [comment]
You are not using the file in the right way.
You have to build the server with Lua support - e.g.:
```
make WITH_LUA=1
```
then start the server
```
sudo civetweb -listening_ports 80 -document_root test
```
(sudo if you want to use port 80, because of some outdated idea of port number security still present in Linux, this port requires root privileges, respectively special capabilities. You can switch the user with another parameter, but first let's get it running and than configure the details.)

If you open the example in a browser (http://localhost/page2.lua), you will see the generated code there.

**Comment by bel2125** [comment]
Did it work? Is there anything else I can do to help?
