### ISSUE TITLE
Change c++ library name on CMakeLists

### ISSUE THREAD

**Issue by paulobrizolara** [civetweb/civetweb#377]
When building civetweb, it uses a name too generic for the c++ wrapper library: "cxx-library". See [here](https://github.com/civetweb/civetweb/blob/master/src/CMakeLists.txt#L271).

I was thinking if it can be changed to something more related to civetweb, like "civetweb-cxx".
I can do a pull-request if you want.

Thanks!

**Comment by bel2125** [comment]
You are right.
I have to admit, I did not notice this before, since I'm not using the C++ library, and the C++ tests don't work this way.

I would tend to "civetweb-cpp", since cpp seems to me a bit more common to cxx (I also found this in the accepted answer in http://stackoverflow.com/questions/5171502/c-vs-cc-vs-cpp-vs-hpp-vs-h-vs-cxx). What do you think?

Yes, a pull request would be welcome.

**Comment by paulobrizolara** [comment]
Very nice.

I will submit a pull request soon.

Thanks!

**Comment by paulobrizolara** [comment]
Done. See pull-request #379.
