### ISSUE TITLE
Version 1.9 and LibreSSL

### ISSUE THREAD

**Issue by nntrab** [civetweb/civetweb#385]
Version 1.8 of Civetweb compiles cleanly with 'NO_SSL_DL' flag set against LibreSSL 2.3.5. Version 1.9 doesn't compile cleanly against LibreSSL 2.3.5 or LibreSSL 2.4.4. The warning on Windows using VS2015 is:

`build/src/civetweb.c(11864): warning C4013: 'ASN1_digest' undefined; assuming extern returning int`

Searching LibreSSL doesn't produce any reference to such a function, the closest match being 'ASN1_item_digest'. Searching the latest OpenSSL code does still find such a function, but it is enclosed in '#ifndef NO_ASN1_OLD', suggesting that it is likely to be removed at some point in the future.

Is the inability to compile against LibreSSL intentional or an unforeseen consequence?

**Comment by bel2125** [comment]
> Is the inability to compile against LibreSSL intentional or an unforeseen consequence?

No, this is not intentional. 
There is one larger new SSL/TLS related feature from 1.8 to 1.9 (now 1.9.1, since a patch was required):
If client certificates are used, there is an API to read certificate information. So you can use different certificates for different clients, granting them different rights. 
ASN1_digest is used to calculate the fingerprint of X509 certificate stored in `request_info.client_cert.finger`

You can drop this calculation as an immediate action - Civetweb will not need the result for anything, if you don't need it in a callback.
I will have a look if this function can be replaced by a new one. But the result should be the same as you get from looking at a certificate, e.g., by double click in Windows Explorer, so I cannot just use any hash function.

**Comment by bel2125** [comment]
The current version does no longer use `ASN1_digest`, but `EVP_Digest`.
I did not find any pre-compiled libressl package for Ubuntu - is there none, does it have a different name, or did I just look at the wrong place?

Is there any other function missing?

**Comment by nntrab** [comment]
I've compiled the master branch on Windows and CentOS 7 against LibreSSL 2.4.4 and it now links cleanly, so there doesn't appear to be any other function missing. Thank you. :-)
