### ISSUE TITLE
example: using decprecated API

### ISSUE THREAD

**Issue by PavelVozenilek** [civetweb/civetweb#393]
File `examples/embedded_c/embedded_c.c`:

In function `FooHandler` , line cca 165, `uri` is used. This structure member is labeled as deprecated in the docs ( https://github.com/civetweb/civetweb/blob/master/docs/api/mg_request_info.md ).

It would be also helpful, for the novices, to show in a comment just there typical example what could this or that item typically contain.  Not eveybody immediatelly recognises the jargon, like difference between absolute URI and local resource URI.

**Comment by bel2125** [comment]
I agree.
local_uri must be used here, like in almost every case.
Thank you, I will fix it.

**Comment by bel2125** [comment]
The `uri` member is in an `#ifdef(MG_LEGACY_INTERFACE)` clause now. 
All remaining uses of `uri` are gone, and they cannot be added again, because the current version of the example does not have `MG_LEGACY_INTERFACE` set and would not compile anymore.

So I think we can close this issue.

**Comment by sunsetbrew** [comment]
awesome work!  I think this project has become so successful because of the
skill and dedication you bring to it!

On Feb 10, 2017 4:58 PM, "bel2125" <notifications@github.com> wrote:

Closed #393 <https://github.com/civetweb/civetweb/issues/393>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/civetweb/civetweb/issues/393#event-958006550>, or mute
the thread
