### ISSUE TITLE
Make authentication domain checks optional

### ISSUE THREAD

**Issue by theanalyst** [civetweb/civetweb#396]
For absolute urls we currently validate that the request is directed to the server or not, however for ceph radosgw, we allow for multiple hostnames (one seperate set of endpoints for static websites hosted). So we'd like to have the option of making the domain checks configurable so that this can be turned off when required.

**Comment by bel2125** [comment]
Duplicate to https://github.com/civetweb/civetweb/issues/197#issuecomment-271652360 / https://github.com/civetweb/civetweb/issues/197#issuecomment-271992325 - but it's better to have this in a separate issue.
See also pull request: https://github.com/civetweb/civetweb/pull/397

- We can disable the domain check with a configuration, 
- or we can use a callback, so civetweb.c asks the calling code if a given domain is local
- or we can configure a list of domains that are supposed to be local

Advantage of all kinds of configuration is, it is also available for users of the pre-built stand-alone executables. If you embed civetweb.c in your application, you can use configuration and callback.

Currently civetweb uses the authentication_domain to check if an absolute uri is local.
If there are multiple domains on the same server, there should be more authentication domains as well, right? Probably you do not face this problem now, since you do not use digest authentication from civetweb? Or do you have a way to deal with different authentication domains as well?
I'm just asking to get the best possible solution for everyone, probably there is a yet unseen problem in a different combination/configuration.

**Comment by theanalyst** [comment]
afaik, we don't use the digest authentication from civetweb. We do validation against a set of allowed hostnames (some of which are also dynamically changeable),  and also have a validation check to ensure that the subdomain also is accessible to the user, ie. something like
 `bucket.ceph.gateway`, (which is also equivalent to `ceph.gateway/bucket`) we validate that the bucket is actually accessible for the user themselves.

**Comment by bel2125** [comment]
So anything like a domain list will not help you anyway.

I can merge the PR, but I would need to think if the config name is right and if boolean is the right type, or if there are other options than on and off. Once it's documented in UserManual.md and in a released version, I won't change it anymore.

**Comment by theanalyst** [comment]
makes sense, Thanks for  the quick feedback

**Comment by bel2125** [comment]
It's been almost three months, since this new configuration parameter has been introduced.
Did you experience any negative effects in the meantime? I did not find any reason to change the type or name of the parameter either, so I could document it and then close this issue.

**Comment by bel2125** [comment]
Finally, the option is documented. So, let's close this issue.

**Comment by theanalyst** [comment]
@bel2125 thanks!
