### ISSUE TITLE
VC++2015 and check.h

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#414]
1>------ Build started: Project: unit_test, Configuration: Debug Win32 ------
2>------ Build started: Project: ex_embed_cpp, Configuration: Debug Win32 ------
3>------ Build started: Project: civetweb_lua, Configuration: Debug Win32 ------
2>  embedded_cpp.cpp
1>  public_server.c
1>q:\git\civetweb\test\civetweb_check.h(38): fatal error C1083: Cannot open include file: 'check.h': No such file or directory
1>  public_func.c
3>  civetweb_lua.vcxproj -> Q:\git\civetweb\VisualStudio\\Debug\Win32\civetweb_lua.exe
3>  civetweb_lua.vcxproj -> Q:\git\civetweb\VisualStudio\\Debug\Win32\civetweb_lua.pdb (Full PDB)
1>q:\git\civetweb\test\civetweb_check.h(38): fatal error **C1083: Cannot open include file: 'check.h'**: No such file or directory
1>  private_exe.c
1>q:\git\civetweb\test\civetweb_check.h(38): fatal error **C1083: Cannot open include file: 'check.h':** No such file or directory
1>  private.c
1>q:\git\civetweb\test\civetweb_check.h(38): fatal error **C1083: Cannot open include file: 'check.h':** No such file or directory
1>  Generating Code...
2>  ex_embed_cpp.vcxproj -> Q:\git\civetweb\VisualStudio\\Debug\Win32\ex_embed_cpp.exe
2>  ex_embed_cpp.vcxproj -> Q:\git\civetweb\VisualStudio\\Debug\Win32\ex_embed_cpp.pdb (Full PDB)
========== Build: 2 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========

**Comment by bel2125** [comment]
You compile the unit test code here, not the server itself.
The unit test requires the "check" framework.
Please download and install it from https://libcheck.github.io/check/

**Comment by bel2125** [comment]
Alternatively, take check.h from https://libcheck.github.io/check/doc/doxygen/html/check_8h_source.html
Replace `#include <check_stdint.h>` by ` #include <stdint.h>` and set the #define `REPLACE_CHECK_FOR_LOCAL_DEBUGGING` and #define `MAIN_PUBLIC_SERVER` (or another MAIN_xxx) as 'main'.

That's not the way "check" is intended to be used, but you don't need to install / build anything and can run and debug the unit tests.

... if you need the unit tests at all. Otherwise just forget the `unit_test` Visual Studio project.

**Comment by pavel-pimenov** [comment]
thank you
https://github.com/civetweb/civetweb/commit/373dd462102ac284a9ce55840f7a6e00e17ba7c4
