### ISSUE TITLE
How to limit access to connections from the local host?

### ISSUE THREAD

**Issue by mwegithub** [civetweb/civetweb#419]
I want to limit access to civetweb to connections from the local host (same machine).

I use the **access_control_list** configuration option with the mask _-0.0.0.0/0,+127.0.0.1_.
Is this sufficient or may this fail, e.g. with IP6 connections.

**Comment by bel2125** [comment]
I would just bind to localhost, using the 'listening_ports' options:

`listening_ports 127.0.0.1:80' (or whatever port you prefer)

**Comment by mwegithub** [comment]
I have read the documentation of listening_ports and access_control_list, but I'm still a bit fuzzy about the details... 8^/

This is my spec:

1. Allow the port to be configurable by the user
2. Allow both HTTP and HTTPS connections
3. **Only allow connections from the same computer**
4. Support both IP4 and IP6 connections.

Assuming port 80 / 443 the listening_ports would then be

## 127.0.0.1:80, 127.0.0.1[::]:80, 127.0.0.1:443s, 127.0.0.1[::]:443s

is that correct?

**Comment by bel2125** [comment]
`127.0.0.1:80, [::1]:80, 127.0.0.1:443s, [::1]:443s`

The loopback address for IPv6 is ::1 

Since you only bind the server to the loopback interface, it cannot be reached from any other interface, and you don't need access control lists.

You must be a little careful with IPv6, since various network environments have different IPv4 <--> IPv6 translation (compatibility?) "features", so please test every IPv6 stuff on the target first, it might be different to my network.

**Comment by bel2125** [comment]
Anything else I can do to help? Or should we close this issue?

**Comment by mwegithub** [comment]
I apologize. I don't use GH very often and I did not know that I have to explicitly close an issue.

I did follow your advice and it works in all my tests. 
This only needs to run on Windows so there should also be no 'platform'-related issues.

Thanks again for your kind support 👍
