### ISSUE TITLE
civetweb.c:6090: error: undefined reference to `_mkgmtime'

### ISSUE THREAD

**Issue by xeoshow** [civetweb/civetweb#420]
Hello,

I am new to civetweb, and now importing the CivetWeb.pro at civetweb\Qt folder into Qt5.5.1-mingw492 version, but met below error when building the project, how to resolve the issue? Thanks!
##
civetweb.c:6090: error: undefined reference to `_mkgmtime'
##

**Comment by bel2125** [comment]
I remember this as a bug of MinGW.

https://bugreports.qt.io/browse/QTCREATORBUG-16937
https://sourceforge.net/p/mingw-w64/bugs/473/

And I remember ther was a

**Comment by xeoshow** [comment]
Thanks for kind reply！Any workround？

**Comment by bel2125** [comment]
Once someone sent me a mingw batch file (https://github.com/civetweb/civetweb/blob/master/resources/mingw.bat), but was never in production, and I do not really maintained this batch file.

There is also a working CMake build with MinGW, but I don't know how to translate it to a Qt project file.
It runs as a continuous integration test (e.g., https://ci.appveyor.com/project/civetweb/civetweb/branch/master/job/rm0fqdopoqxhigtr). Maybe AppVeyor simply uses a different minGW version than Qt.

If everything else fails, you could 
- either set the `NO_CACHING` define
- or add your own `timegm` (aka `mkgmtime`) implementation. There are quite a few implementations around, but most do not have a MIT license or do not calculate leap seconds and daylight saving / summer-winter time switching correctly.

**Comment by xeoshow** [comment]
Looks like NO_CACHING is the simplest solution, if set the NO_CACHING define, what is this option for and what will be affected? Where could I set it? 

Thanks so much!

**Comment by xeoshow** [comment]
Found the NO_CACHING option and problem resolved, thanks!

**Comment by bel2125** [comment]
NO_CACHING means, browsers or intermediate caches will not store the file, but always ask the server.

- If you have only dynamically generated contents (CGI, Lua, callbacks, ..) there won't be any difference, since you usually do not cache the generated results anyway.
- If you have only large files, or any files that are usually downloaded only once for every user, cache is also not that important (unless you have thousands of downloads of the same file, and use intermediate caches).
- If you use small/average static files, logos, http pages, ... you would certainly benefit from a cache.
