### ISSUE TITLE
Fails on large POST requests

### ISSUE THREAD

**Issue by pkvamme** [civetweb/civetweb#428]
civetweb 1.9.1 running on CentOS 7.2.

civetweb does not handle POST messages in SSL connections properly if there is more than approx. 16 Kb of data.

The problem is in pull(). This will first satisfy the request from some internal buffer. Then, if it needs more, it will poll the SSL file descriptor until data is available. The function does **not** check SSL_pending().

It is possible that the SSL layer itself has buffered all the remaining data. In that case SSL_pending() will return a positive number and polling conn->client.sock() will never return any data. So it times out.

I will attach a patch and some code to reproduce the bug. There might be more elegant ways of fixing this but my patch seems to work for me: [code.zip](https://github.com/civetweb/civetweb/files/841126/code.zip)

When reproducing the bug, paste approximately 16,500 bytes into the text field of the form.

Note: I have not tried cloning and building the latest version of civetweb to see if the problem has been fixed already. But I did look at the source and I am fairly sure the bug is still there.

**Comment by bel2125** [comment]
Thank you for your patch. I did not yet encounter this problem in practice, so probably the CI tests should be enhanced as well.

I merged the patch, and will have a look at the tests later.

**Comment by bel2125** [comment]
I cannot directly integrate your test into the unit test suite, since it's an interactive test, and it's in C++ while the test suite is currently plain C (technically, I could add a C++ test module, but since I need to rewrite it to an automated test anyway, I can translate it to C as well). But I don't want to track "add automated unit test" with this issue.

Your patch from the zip is merged. 
Thank you for your contribution.

**Comment by bel2125** [comment]
Fixed some weeks ago.
Closing this issue.

**Comment by pkvamme** [comment]
Thanks. Sorry I didn't spot that 'waiting for submitter to confirm' tag. New to github...

**Comment by bel2125** [comment]
No problem.
The "Status" labels are actually not the default Github labels. I think standard is just "bug", "duplicate", "enhancement", "help wanted", "invalid", "question" and "wont fix" - since this does not state anything about the progress of work, many repositories with a larger community add their own type and status labels.
