### ISSUE TITLE
Static linking with flag --static fails

### ISSUE THREAD

**Issue by davidsblom** [civetweb/civetweb#439]
I'd like to use static linking for my application with the `--static` flag, but get the following error

```
build/third-party/civetweb/libcivetweb.a(civetweb.o): In function `mg_start':
civetweb.c:(.text+0xe8ed): warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
build/third-party/civetweb/libcivetweb.a(civetweb.o): In function `mg_connect_client_impl.isra.17':
civetweb.c:(.text+0x3b9c): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
g++ -o build/sw-updater -pthread build/src/updater/main.o -Lbuild -Lbuild/third-party/civetweb -lsw-updater -lsw-third-party /usr/lib/x86_64-linux-gnu/libprotobuf.a -lcivetweb -lpthread -ldl -lgcov
```
the resulting binary cannot start.

Any ideas?

**Comment by bel2125** [comment]
`make slib` works for me without any warning.
Probably, it depends on the system. 

I asked google about your warnings, and found it could be related to the [GLibC Name Service Switch (NSS)](http://www.gnu.org/software/libc/manual/html_node/NSS-Basics.html#NSS-Basics):
- http://stackoverflow.com/questions/2725255/create-statically-linked-binary-that-uses-getaddrinfo
- http://stackoverflow.com/questions/5426420/linker-warnings-while-building-application-against-mysql-connector-c-libmysqlcli

**Comment by bel2125** [comment]
To look at this in more detail, I would need detailed system information.
What operating system / distribution / version, what compiler / version, what build system, ...?

**Comment by davidsblom** [comment]
thanks for the info. So I'm using the --static compilation flag for my own application. Then the compiler tries to link all dependencies with static libraries. I guess that's not possible for civetweb, since in the implementation of civetweb shared libraries are being used.

**Comment by bel2125** [comment]
I think it depends on the operating system, and maybe the feature defines (such as NO_SSL or USE_LUA). But there is little I can do here, if it does not work on your system.

I personally never use static libraries, but I tested it when you opened this issue, and it worked on my system (I know, this does not help you at all, if I put a [works on my machine certificate](https://blog.codinghorror.com/the-works-on-my-machine-certification-program/) here). While looking around, I also found an article claiming static libraries should not be used at all: https://www.akkadia.org/drepper/no_static_linking.html I do not insist on "everything written there is right". Everybody should do what he/she considers the best for the given project. I just posted the link here, because maybe there are some advantages in using dynamic libraries, that could be helpful for you as well.

**Comment by bel2125** [comment]
Thinking again on this issue:

Up to now I meant "make slib" does not work for you (--> you cannot build a static library).
This works for me.

Or did you mean "make COPT='--shared'" (gcc --shared civetweb.c main.c) does not work?
This does not work on my Ubuntu machine either, but this is not how the build is supposed to work, and this is not possible with glibc.

**Comment by davidsblom** [comment]
Thanks for your thoughts on this. I'm well aware of the drawbacks for using static linking. So, to be clear, `make slib` for civetweb works just fine. 

I would like to compile my application with the -static compilation flag:

http://stackoverflow.com/questions/8692128/static-option-for-gcc

But if this is not possible, you can close the issue. Thanks for your comments!

**Comment by eladkarako** [comment]
<code>make clean && make --ignore-errors LDFLAGS=-static CFLAGS=-Wno-error</code>
