### ISSUE TITLE
Why do responses include "X-Some-Test-Header: 42"?

### ISSUE THREAD

**Issue by snej** [civetweb/civetweb#446]
Every HTTP response generated by civetweb itself, instead of a user-defined handler (e.g. HTTP errors, redirects, etc.) includes a header `X-Some-Test-Header: 42`. I tracked this down to the function `send_additional_header` in civetweb.c. 

Is this some obsolete test code that got left in by accident? It's pointless, but can't be configured or removed without editing civetweb.c.

**Comment by bel2125** [comment]
Sending additional headers is a new feature planned for 1.10, but it's not fully implemented yet. It has not been included in the last released version 1.9.
The original intention was to add the "Strict-Transport-Security" required for some security scores, but the mechanism is rather general, and I have to think about an interface before the 1.10 is going to be released. But it's true, since it cannot be configured, it can be commented out at the moment. I've done that now, but I cannot promise when I have time to finish this new feature.

**Comment by nfrmtkr** [comment]
Hello bel2125,

I came accross this code while looking for a possibility to add Strict-Transport-Security to civitweb. Many security assesments recommend to use this header. For my own request handlers I can add it, but for responses send directly by civetweb it is hard to add. 
Your approach with send_additional_header() looks promissing. When you intend to continue working on this? I guess, the unused argument additional_headers of handle_static_file_request() can be removed once the send_additional_header() stuff is implemented.
Setting the content for the additional headers should be possble with xa_start() options argument, isn't.

**Comment by bel2125** [comment]
Yes, it was intended for "Strict-Transport-Security" originally, but then I found it useful for other headers as well. I was looking for an idea how to configure this.

If it is limited to "Strict-Transport-Security", there would be just the "max-age" parameter. It could be added as a configuration option (just like ports, certificates and a dozen of other options). All the mechanisms would be there to add this in like ~5 minutes of implementation.

But this will not allow to add any other header.

However, there does not seem to be an easy way to configure this. And it would not hurt to add the "Strict-Transport-Security" option now.

> I guess, the unused argument additional_headers of handle_static_file_request() can be removed once the send_additional_header() stuff is implemented.

No, since it is accessible in the external interface (civetweb.h) as argument to `mg_send_mime_file2`. Removing it there would be a compatibility issue. However, if you used  `mg_send_mime_file2()` to pass a "Strict-Transport-Security" header, you should remove this header-key-value-pair from your call to this function, while all other header-key-value pairs passed to  `mg_send_mime_file2` remain.

**Comment by bel2125** [comment]
@nfrmtkr: May I ask you to do the test? 
I know there is a test tool for security testing of web sites, but this week I won't find time to test it.

Implementation is already done (patch is here: 8fcb2e026620d86b686e7aacffd3dd5262e5f64b)

**Comment by nfrmtkr** [comment]
Well, I'll test as soon as possible, most probably next week.
Regarding configuration: Why not adding a string option "additional_headers" that is taken as it is in send_additional_header(). The content must be a valid HTTP header part 

parametername1: parametervalueA\r\n
parametername2: parametervalueB\r\n
...
parameternameN: parametervalueN

doing it this way developers can add any parameters.
In case of "Strict-Transport-Security", I would assemble string:

"Strict-Transport-Security: max-age=31536000"

and provide it as value for the additonal_headers option. Adding "Strict-Transport-Security" makes sense only in case the server provides a SSL port. This means that this header should not be added in case no SSL port is active. This information may be parsed from listening_port value (occurences of "s,").

**Comment by nfrmtkr** [comment]
Hello @bel2125,

another permanent security related header would be "X-Frame-Options" (RFC 7034). In past (<2013) browsers accepted this as part of html files (<meta http-equiv="X-Frame-Options" content="deny">), but today it must be sent as HTTP header in order to take effect. 
This header parameter can have different values:

DENY
SAMEORIGIN
ALLOW-FROM uri

Comming back to the configuration. Imagine I want to set Strict-Transport-Security and X-Frame-Options, I would set the additional_headers option to:

"Strict-Transport-Security: max-age=31536000\r\n
X-Frame-Options: SAMEORIGIN"

By the way. Does send_additional_header() send the headers for each response no matter what the HTTP command was? For istance, the two mentioned paramaters are used in responses for a GET, only.

**Comment by bel2125** [comment]
I'm not a fan of adding 'X-Something' options to the code, since X- is the indication for "non standard", and even if it is a "de facto standard", it is documented in the code, the user should send the X- options himself. This would be something for a generic key+value configuration (like `-add_header "X-Frame-Options SAMEORIGIN", similar to [other servers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options)).

> By the way. Does send_additional_header() send the headers for each response no matter what the HTTP command was? For istance, the two mentioned paramaters are used in responses for a GET, only.

They are sent always, no matter if it is GET, PUT or something else. I don't think it hurts - does it?
I did not read [the full RFC 6797](https://tools.ietf.org/html/rfc6797), but when searching for "GET" and "method" I did not find a method restriction.

**Comment by nfrmtkr** [comment]
I agree with you, the X- headers shouldn't be hardcoded. What do you think about my suggestion regarding configuration. Remove the option "strict_transport_security_max_age" add a new string option "addional_headers" and take the content as it is in send_additional_header(). In may case I would configure this option as follows:

"Strict-Transport-Security: max-age=31536000\r\n
X-Frame-Options: SAMEORIGIN"

The send_additional_header() function simply adds this bunch of text to the header.

**Comment by bel2125** [comment]
I added a configuration `additional_header` for tests.

**Comment by bel2125** [comment]
I added a configuration `additional_header` for tests.

**Comment by nfrmtkr** [comment]
Hello @bel2125,

I've testes the option addional_header. It is working as excpected, but multi line option values are not supported by civetweb. I've added following code in main.c  function read_config_file line 528, right before set_option in order to translate \r and \n to corresponding control chars:

			/*transalte \r and \n character sequemces by corresponding control character*/
			char tmp[MAX_CONF_FILE_LINE_SIZE];
			size_t k = j;
			size_t l = 0;
			while (line[k] != '\0')
			{
				if (line[k] == '\\' && line[k + 1] != '\0' && line[k + 1] == 'r')
				{
					tmp[l++] = '\r';
					++k;
					++k;
				}
				else if (line[k] == '\\' && line[k + 1] != '\0' && line[k + 1] == 'n')
				{
					tmp[l++] = '\n';
					++k;
					++k;
				}
				else
				{
					tmp[l++] = line[k]; 
					++k;
				}				
			}
			tmp[l] = '\0';
			strcpy(line + j, tmp);

With this code I was able to use following configuration in ciwetweb.conf:

additional_header Strict-Transport-Security: max-age=31536000\r\nX-Frame-Options: SAMEORIGIN

Being able to add any bunch of chars to the header section makes the code regarding "Strict-Transport-Security" obsolete from my point of view.

**Comment by bel2125** [comment]
I added the \r\n (and some other escape sequences) for all string parameters.

However, thinking about it again, it will cause problems with windows paths, that usually contain backslashes, so probably a different escape character is needed.

**Comment by nfrmtkr** [comment]
Hello @bel2125,

the current implementation causes an endless loop in sdupesc. The charÜ* p must be advanced. I did it using a new char* q. See attached diff. 
The backslashes in Windows PATH do not work with sdupesc. In order to allow a backslash two backslashes must be provided for document_root for instance. This is not very helpful. Most options don't require the special characters. Why not adding  a new type "CONFIG_TYPE_STRING_ESC" and decide if to use sdupesc based on this type. I tested it with additional_headers, see my code in attached diff.

[civetweb.zip](https://github.com/civetweb/civetweb/files/1025418/civetweb.zip)

**Comment by nfrmtkr** [comment]
Another issue I've detected is in the graphical options editor on Windows. The additional_header option value is loaded into the text widget after conversion and does not display the values \r\n. It includes the coverted chars x13x10 and saving the settings will write x13x10 back to civetweb.conf inestead of \r\n.

Simple feature, but lots of impact regarding configuration.

What about following approach. We leave set_option() in main unchanged (not using sdupesc). Thus \r\n will not be modified. This should solve the config issues in the window etc. In mg_context a new item char* additonal_headers will be added. In mg_start the additional_header option will be read and a copy will be created using sdupesc (translating \r\n etc) and stored in mg_context.additional_headers. In send_additional_header() the content of conn->ctx->additonal_headers will be used.

**Comment by bel2125** [comment]
I think, I fixed the endless-loop issue yesterday (https://github.com/civetweb/civetweb/commit/72252366a1d71bf351b74f0ade64315bb93a4ed8) ...

But, the more I think about it, the more I come to the conclusion escaping is a bad idea entirely. It is an alien element in the concept, causing a lot of problems, including compatibility issues. What you actually want to do is provide a list of something - header lines. There are already other parameters used to provide, e.g. listening_ports, cgi_pattern, cgi_environment, ssi_pattern, index_files, access_control_list, extra_mime_types, hide_files_patterns, lua_script_pattern, ... probably this list is not complete.
However, the standard separator for lists `,` can occur in headers as well. I don't know for the separator for patterns `|`. I will check if there is some printable ASCII character forbidden in headers.

This way, there is no more need to escape anything, but it's just reading a list, like in many other functions in civetweb.c.

**Comment by bel2125** [comment]
Now it should be possible to use the `additional_header` config option multiple times (as well as other config options of "list" or "pattern" types).

**Comment by nfrmtkr** [comment]
Hello @bel2125 ,

this works fine for me (embedded use of civetweb). But keep in mind that the configuration dialog of the Windows tray application cannot handle the CONFIG_TYPE_STRING_MULTILINE configuration type. 
Now that additional_header is working in a generic way, the specific option strict_transport_security_max_age can be removed, because we can use following configuration instead:

additional_header Strict-Transport-Security: max-age=31536000

**Comment by bel2125** [comment]
I think we can keep the `strict_transport_security_max_age` option. It is a standard header, just like the cache-control max age header. You can still choose to not set the `strict_transport_security_max_age` option and set the value using `additional_header`.

I will take care about the Windows dialog next week.

**Comment by bel2125** [comment]
The basic functionality is implemented since May/June.
The usability in the Windows multi-line dialog could be somewhat better - further usability improvements will not be tracked with this issue, but as a TODO on a different list.
