### ISSUE TITLE
Not seeing ping / pong messges for websocket 

### ISSUE THREAD

**Issue by saggoyal12** [civetweb/civetweb#461]
Hi,

I am using civet websocket for my application. I am not seeing ping / pong messages being exchanged between client and server. Do I need to configure this explicitly or civet library  takes care of it ? 

Thanks,
Sagar

**Comment by bel2125** [comment]
You need to send it in your callback, in case you want to use it. But not every browser supports it, and there is no API to detect it or use it in any way in JavaScript:
http://stackoverflow.com/questions/10585355/sending-websocket-ping-pong-frame-from-browser
Thus, ping pong seems pretty useless to me, so I usually use some cyclic keep-alive messages messages in the higher level protocol.

**Comment by saggoyal12** [comment]
"You need to send it in your callback" - any sample code for the same ?

**Comment by bel2125** [comment]
You need to send it in your callback, in case you want to use it. But not every browser supports it, and there is no API to detect it or use it in any way in JavaScript:
http://stackoverflow.com/questions/10585355/sending-websocket-ping-pong-frame-from-browser
Thus, ping pong seems pretty useless to me, so I usually use some cyclic keep-alive messages messages in the higher level protocol.

**Comment by bel2125** [comment]
I don't use ping/pong myself, since you cannot rely on it in any way.
You could try to adapt an example (either the C or the Lua example) to sent ping/pong messages instead of text messages.

For Lua, the websocket example is [test/websocket.lua](https://github.com/civetweb/civetweb/blob/master/test/websocket.lua) - just add `mg.write("ping", "something")` to the `timer` function.

For C, there is [example/embedded_c/embedded_c.c](https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c), and the corresponding call would be `mg_websocket_write(conn, WEBSOCKET_OPCODE_PING, text, strlen(text));`. But there is no existing timer in this example, so you have to add one.

**Comment by bel2125** [comment]
For the Lua test, you can actually see it working by checking the `websocket.trace` file. I added `mg.write("ping", "p");` to `function senddata()` right after `mg.write("text", string.format("%u:%02u:%02u", date.hour, date.min, date.sec));`

The websocket.trace file looks like this:
```
some time: data[127.0.0.1:#####]: {bits=138, client=userdata: 0x########, data=p}
same time: data[127.0.0.1:#####]: {bits=138, client=userdata: 0x########, data=p}
same time: data[127.0.0.1:#####]: {bits=138, client=userdata: 0x########, data=p}
```
With 138 = 128 + 10 (10 is the opcode of PONG, see [civetweb.h](https://github.com/civetweb/civetweb/blob/master/include/civetweb.h#L656)). There are multiple lines with the same time-stamp, and the combined CPU usage of browser and server is almost 100%, since they spent all their time with PING/PONG handling. Every PONG received by the server calls the [data callback function in websocket.lua](https://github.com/civetweb/civetweb/blob/master/test/websocket.lua#L79), and this calls `senddata` and, thus, PING again.

In 2012, websocket ping/pong was not supported by all clients, and there was no way to detect it 
([see this stackoverflow question](http://stackoverflow.com/questions/10585355/sending-websocket-ping-pong-frame-from-browser)). I have no recent data - I just heard ~2 years ago, some versions of safari for windows and opera mini had some problems, but I did not verify this by myself. So it might be safe to use websocket ping in all recent, relevant browsers - or maybe it is still not available everywhere - I cannot give any guarantee.

**Comment by bel2125** [comment]
Did you manage to run ping/pong with the instructions above?
Is there anything else I can do to help, or can we close this issue?

**Comment by bel2125** [comment]
It seems there are no open questions regarding this topic.
Closing this issue now.
