### ISSUE TITLE
listening_port option "+" doesn't work in Windows

### ISSUE THREAD

**Issue by nfrmtkr** [civetweb/civetweb#463]
The "+" option in listening_port configurarion doesn't work as documented on Windows. On Windows a IPv6 port is opened only. A short discussion about the default socket behavior can be found here;

http://stackoverflow.com/questions/20657650/socket-listener-for-ipv6-and-ipv4

I tried with following configuration on Windows: [::1]:5000,127.0.0.1:5000
This works fine:

netstat -an | grep 5000
TCP 127.0.0.1:5000 0.0.0.0:0 LISTEN
TCP [::1]:5000 [::]:0 LISTEN

I suggest to add a not to the listening_ports documenation.

**Comment by bel2125** [comment]
From my experience, the IPv6 support depends is very system dependent. The + worked well on my native WinXP test machine. But it might be different in virtual machines.

> I suggest to add a not to the listening_ports documenation.

Sorry - what do you mean?

**Comment by nfrmtkr** [comment]
Sorry! I suggest to add more information to the documentation that the + flag may not work on all operating systems this way. For instace on Windows 10 it doesn't work.

**Comment by bel2125** [comment]
The [listening_ports](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#listening_ports-8080) documentation currently states:

> Depending on your IPv6 network environment, some configurations might not work (properly), so you have to test to find the configuration most suitable for your needs.

I will insert anything that might help users. I don't want to add a list of operating system versions (and patches) that work this way or the other, since it will not be complete, I cannot test it for every system, and I don't know about future patches of this operation system or local variants. But I'm fine with some general statement like "most Windows versions",  "depending on the Linux distribution", ...

Could you provide a paragraph that might be helpful?

**Comment by bel2125** [comment]
I added some paragraphs to the documentation (https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#listening_ports-8080). It's still rather generic and does not mention specific operating system versions: Depending on your operating system version and IPv6 network environment, some configurations might not work as expected, so you have to test to find the configuration most suitable for your needs. In case +80 does not work for your environment, you need to use 80,[::]:80.

I guess that's the best we can do here.
