### ISSUE TITLE
Invalid handling of EWOULDBLOCK in push() function

### ISSUE THREAD

**Issue by HolakovskyJan** [civetweb/civetweb#474]
When send() returns EWOULDBLOCK another call to send() is performed immediately, which chokes the socket on platforms with small buffers. Instead of immediately repeating call to send(), select() should be called to determine whether the send() could be called again.

**Comment by bel2125** [comment]
As a quick fix, I added a mg_sleep.
I will have a deeper look into this later this week.

**Comment by bel2125** [comment]
I changed the code to use select, as proposed (and fixed some nasty GCC warning, when using socket macros). The automatic tests are running, but they were also working with the sleep and even without sleep call. Probably the original problem only occurs on platforms with very small network buffers and slow networks?
Could you have a look, if this fixes the problem on your test platform?

**Comment by bel2125** [comment]
Maybe the fix using `select` yields in an `ERR_CONTENT_LENGTH_MISMATCH` in Chrome - see https://github.com/civetweb/civetweb/issues/417#issuecomment-313931530

Currently I don't know why, since I can neither reproduce #417 nor this issue. Maybe one should not use select but just `sleep`, although, at the moment I would not know why.

**Comment by bel2125** [comment]
Maybe it was an uninitialized time variable ... tests are running.

**Comment by HolakovskyJan** [comment]
Adding select worked, problem seems to be fixed.
