### ISSUE TITLE
Read out of bounds in parse_http_message()

### ISSUE THREAD

**Issue by newsoft** [civetweb/civetweb#475]
I am fuzz testing Civetweb with "clang -fsanitize=address" to no luck. The fuzzer chokes in parse_http_message():
```
		start_line = skip(&buf, "\r\n");
[1]		ri->request_method = skip(&start_line, " ");
[2]		ri->request_uri = skip(&start_line, " ");
[3]		ri->http_version = start_line;
(...)
[4]		is_request = is_valid_http_method(ri->request_method);
[5]		if ((is_request && memcmp(ri->http_version, "HTTP/", 5) != 0)
		    || (!is_request && memcmp(ri->request_method, "HTTP/", 5) != 0)) {
```
Let's send the following (invalid) request: "GET /\r\n\r\n".

[1] ri->request_method points to "GET".
[2] ri->request_uri points to "/".
[3] ri->http_version points outside of the buffer.
[4] is_valid_http_method() returns True.
[5] memcmp(ri->http_version, "HTTP/", 5) might read 5 bytes of unallocated memory since http_version is past the end of the buffer.

**Comment by bel2125** [comment]
My current settings for manual tests are `make WITH_DUKTAPE=1 WITH_LUA=1 WITH_IPV6=1 WITH_WEBSOCKET=1 WITH_SERVER_STATS=1 COPT="-fsanitize=address -fno-omit-frame-pointer -fsanitize=undefined"`, so -fsanitize=address should work.

Currently [5] cannot read unallocated memory, due to the way buf is preallocated by the caller. But it could be uninitialized memory - and it will fail to compare with "HTTP/" in memcmp(ri->http_version, "HTTP/", 5). So, you won't crash the server.

But I agree, this is not a good idea to rely on the way the caller allocated the buffer - I'm going to have a deeper look into this later this week.

**Comment by bel2125** [comment]
I tested it: 
If you send `GET /\r\n\r\n`, 
[1] ri->request_method will be "GET" (just like you said)
[2] ri->request_uri will be "/" (like you said)
[3] ri->http_version will be an empty string. The pointer is at the "\r\n\r\n", with the first \r replaced by 0
[4] is_valid_http_method() returns 1
[5] memcmp(ri->http_version, "HTTP/", 5) compares [\0 \n \r \n \0] to [H T T P /], all 5 bytes are allocated

**Comment by tzimmofsecure** [comment]
Using memcmp() there instead of for example strncmp() that would stop at the NUL-terminator looks somewhat suspicious, although I didn't yet manage to break it with requests like "GET /\n\n" or "GET /\n\r\n" but I'm not yet sure it couldn't be broken. I'll take a further look at it.

**Comment by tzimmofsecure** [comment]
The buffer size seems to be 16384 bytes. When I send a request "GET /AAA...AAA\n\r\n" with a total size of 16384 bytes:

--8<--8<--
Breakpoint 1, parse_http_message (
    buf=0x7fffac0048d0 "GET /", 'A' <repeats 195 times>..., len=16384, 
    ri=0x6910c0) at ../../../build/civetweb/src/civetweb.c:7856
7856            request_length = get_request_len(buf, len);
(gdb) n
7858            if (request_length > 0) {
(gdb) print request_length
$1 = 16384
(gdb) n
7862                        ri->http_version = NULL;
(gdb) n
7861                    ri->remote_user = ri->request_method = ri->request_uri =
(gdb) n
7863                    ri->num_headers = 0;
(gdb) n
7865                    buf[request_length - 1] = '\0';
(gdb) n
7868                    while (*buf != '\0' && isspace(*(unsigned char *)buf)) {
(gdb) n
7871                    start_line = skip(&buf, "\r\n");
(gdb) n
7872                    ri->request_method = skip(&start_line, " ");
(gdb) n
7873                    ri->request_uri = skip(&start_line, " ");
(gdb) n
7874                    ri->http_version = start_line;
(gdb) n
7882                    is_request = is_valid_http_method(ri->request_method);
(gdb) n
7883                    if ((is_request && memcmp(ri->http_version, "HTTP/", 5) != 0)
(gdb) print ri->http_version - (const char *) 0x7fffac0048d0
$2 = 16382
--8<--8<--

...ri->http_version is actually in a position where there is only 2 bytes of buffer left. Now if memcmp() is optimized so that it doesn't just read it byte by byte and notice that the first bytes do not match 'H' and 'T', it could potentially read out of bounds, I think. What do you think? I didn't manage to get a crash or error in valgrind though.

**Comment by tzimmofsecure** [comment]
Now I added code there before memcmp() call as follows:

--8<--8<--
{
    unsigned int i;
    for (i = 0; i < 5; i++) {
        printf("ri->http_version[%u] = 0x%02x\n", i, ri->http_version[i]);
    }
}
--8<--8<--

and now I get an error from valgrind:

--8<--8<--
ri->http_version[0] = 0x00
ri->http_version[1] = 0x00
==25731== Thread 4 civetweb-worker:
==25731== Invalid read of size 1
==25731==    at 0x429F53: parse_http_message (civetweb.c:7885)
==25731==    by 0x432908: getreq (civetweb.c:13054)
==25731==    by 0x432E96: process_new_connection (civetweb.c:13388)
==25731==    by 0x433821: worker_thread_run (civetweb.c:13758)
==25731==    by 0x4338D9: worker_thread (civetweb.c:13803)
==25731==    by 0x5045063: start_thread (pthread_create.c:309)
==25731==  Address 0x5674e40 is 0 bytes after a block of size 16,384 alloc'd
==25731==    at 0x4C28C20: malloc (vg_replace_malloc.c:296)
==25731==    by 0x41FF4C: mg_malloc (civetweb.c:1015)
==25731==    by 0x4336EA: worker_thread_run (civetweb.c:13675)
==25731==    by 0x4338D9: worker_thread (civetweb.c:13803)
==25731==    by 0x5045063: start_thread (pthread_create.c:309)
==25731== 
ri->http_version[2] = 0x00
ri->http_version[3] = 0x00
ri->http_version[4] = 0x00
--8<--8<--

that indicates that is an optimized version of memcmp() could access unallocated memory.

**Comment by newsoft** [comment]
Indeed the bug might or might not trigger, depending on the memcpy() implementation - something you cannot rely upon. Here is how it plays out on my Ubuntu 16.04:
```
$ gdb ./civetweb
(gdb) b parse_http_message
Breakpoint 1 at 0x40e319: file src/civetweb.c, line 8611.
(gdb) r

[ From another console ]
$ nc localhost 8080
GET<return><return>

[ Switching to Thread 0x7ffff7fb1700 (LWP 32271) ]
Thread 4 "civetweb-worker" hit Breakpoint 1, parse_http_message (buf=0x7ffff00008c0 "GET\n\n", len=16384, 
    ri=0x62b298) at src/civetweb.c:8611
8611	{
(gdb) n
...
(gdb) n
8657			if ((is_request && memcmp(ri->http_version, "HTTP/", 5) != 0)
(gdb) p ri->request_method
0x7ffff00008c0 "GET"
(gdb) p ri->request_uri
0x7ffff00008c3 ""
(gdb) p ri->http_version 
0x7ffff00008c3 ""
(gdb) x/8x 0x7ffff00008c0 
0x7ffff00008c0:	0x00544547	0x00000000	0x00000000	0x00000000
0x7ffff00008d0:	0x00000000	0x00000000	0x00000000	0x00000000
```
So memcpy(length=5) might definitely access memory not belonging to the buffer; ASAN is right.

(Most memcpy() implementations would at least fetch 32 bits in the above case.)

**Comment by tzimmofsecure** [comment]
It is memcmp(), not memcpy(), but otherwise you are correct.

**Comment by bel2125** [comment]
Short story:
I will change it, but you won't be able to force a crash.

Long story:
It seems a hand-crafted invalid request (but not "GET /\r\n\r\n") may indeed read 1 byte past the buffer. Reading uninitialized memory will not cause a crash - the comparison will fail anyway since the bytes in front are already different. The only thing that might cause a crash is reading memory on a not allocated page. Pages come in quantities of 4096 bytes on almost all systems, some embedded systems have like 1024 bytes - all sizes are multiples of 4 (the 32 bit fetched by memcmp on 32 bit systems, if the address is aligned). If the address is not aligned, memcpy will compare byte-wise before and after the 4 byte aligned address is reached. This is required for many CPU types (you will get a "bus alignment exception" otherwise), and strongly advised for all others (X86 will allow it for not-atomic operations, but with a performance penalty). Also "malloc" returns addresses aligned to 4 bytes (at least if the size is 16kB, don't know/don't care for malloc(1 byte)). In the current (not yet released) version, the buffer size can be defined by the `max_request_size` parameter, but minimum is 1024 bytes. 
We make a "memcmp" for 5 bytes, and we know at least the first 2 are on an allocated, readable page. 
If there are 5 on the same page, it does not make any problem to read all of them anyway. If there are 4 on the readable page, it will read 4 bytes in one block, detect the difference and not read the fifth one. If there are less then four on the first page, memcmp will read bytewise and detect a difference as well. So you won't reach a crash.
Still this needs to be changed, since it relies on something out of the C standard. It works, because 32 bit CPU architectures works this way, and civetweb does not support 8 or 16 bit architecture anyway (it will work for any architecture >=32 bit).

**Comment by bel2125** [comment]
As a quick fix, I'm now using byte by byte comparison.
I want to restructure this function some time later anyway (in the context of #479).

Thanks everyone for your excellent analysis.

**Comment by tzimmofsecure** [comment]
You could also have there "if" before memcmp that the actual buffer (length) has still at least 5 bytes or (initialized) content before the comparison. If it has less, it cannot contain "HTTP/" anyway.

**Comment by bel2125** [comment]
I tend to split `parse_http_message(char *buf, int len, struct mg_request_info *ri)` 
into `parse_http_request(char *buf, int len, struct mg_request_info *ri)`
and `parse_http_response(char *buf, int len, struct mg_response_info *ri)`,
test every element immediately before parsing the next.
Maybe there could be a configuration for `max_uri_length`, that needs to be significantly smaller than `max_request_size` (got to think about this config entry).

Finally the API should distinguish between a mg_connection in the server case (read request from a client and send answer) and in client case (send request to a server and read answer).

But that's more than required here as a minimum. So I just did this minimum here, since I anyway want to restructure it later.

**Comment by bel2125** [comment]
Request parsing has been rewritten.
See #479

This should also solve this issue.

**Comment by bel2125** [comment]
Fixed some weeks ago by rewriting the code (Commits "Rewrite request parsing (Step x/x)"). 
Since the affected part of the code does no longer exist, I'm closing this issue.

**Comment by newsoft** [comment]
Submitter confirms :) Thank you!
