### ISSUE TITLE
Vanilla civetweb fails debugger in Windows (vs2010 & vs2015)

### ISSUE THREAD

**Issue by btsimonh** [civetweb/civetweb#487]
Using VS 2015 express for desktop applications (update 2) with master. (toolset v140)
Build either embedded_c or embedded_cpp.
Run the server from VS in debug.
create index.html like https://gist.github.com/btsimonh/af840daf1e222a6969874d711ae80468
open http://127.0.0.1:8081 (c++) or http://127.0.0.1:8884 (c)
Open more than once if you don;t see a failure...

wait..... (1/2 hour?).

then try to pause the app in the debugger.... if it pauses, the issue has not occurred - run on and wait a bit more.
"Once it has failed, trying to stop the app from VS results in 'The debugger was unable to terminate one or more processes: [2548] ex_embedded_c.exe: The object invoked has disconnected from its clients."  (similar in VS2010).

This also happens for me with VS2010 with a dll containing civetweb build with MSBuild toolset v100.
And I believe it happened with civetweb 1.9, sept 2016.

After lots of investigation, I'm still at a loss as to how to diagnose this issue - ApplicationVerifier did not reveal anything.

**Comment by btsimonh** [comment]
testing 1.9 now; will report

**Comment by bel2125** [comment]
Google/Microsoft told me "The object invoked has disconnected from its clients" is a low level DCOM error in Windows itself: https://support.microsoft.com/en-us/help/940466/fix-on-a-windows-server-2003-based-computer,-network-traffic-occurs-wh
it seems to occur from systems as old as server 2003 (and probably older ones) to systems as new as windows 10
https://social.technet.microsoft.com/Forums/windows/en-US/822263b7-bbee-4a14-bb77-a35db28a43cd/message-at-windows-logon-the-object-invoked-has-disconnected-from-its-clients?forum=win10itprogeneral

**Comment by btsimonh** [comment]
Now testing with Anonymous Logon with remote access permissions.  I hate DCOM! :).  Will report.

**Comment by bel2125** [comment]
This DCOM error seems to apply to a lot of very different products. Anonymous logon was just one solution in the first microsoft support article I found, from more than 80000 hits for `The object invoked has disconnected from its clients`. In your case, it is probably a DCOM error in Visual Studio - civetweb itself does not use any DCOM.

**Comment by bel2125** [comment]
... seems to be a problem for a couple of Visual Studio users, unrelated to CivetWeb ...

https://stackoverflow.com/questions/20248955/unable-to-start-debugging-because-the-object-invoked-has-disconnected-from-its-c

https://stackoverflow.com/questions/1835026/visual-studio-freezes-when-switching-to-debug-mode/1838147#1838147

https://connect.microsoft.com/VisualStudio/feedbackdetail/view/982277/the-object-invoked-has-disconnected-from-its-clients

https://developercommunity.visualstudio.com/content/problem/11208/the-object-invoked-has-disconnected-from-its-clien.html

https://social.msdn.microsoft.com/Forums/en-US/91e9c187-d18e-4e3c-bc91-4ca4f93ed2fb/error-the-object-invoked-has-disconnected-from-its-clients?forum=vbinterop

https://developercommunity.visualstudio.com/content/problem/11208/the-object-invoked-has-disconnected-from-its-clien.html

But does not only affect Visual studio but also Excel and many other programs form other vendors. Suggested solutions range from "ignore" to "re-install software" ... 
Sorry, I don't think I can help here.

**Comment by btsimonh** [comment]
After a complete powerdown, civetweb (1.9.1) ran overnight and I could still pause it in the morning :).  So I blame MS.  Closing for now; I'll keep an eye on it.
Have to say, there is no evidence that this was caused by Civetweb, and it only started to happen after the major MS june update but which unfortunately corresponded with lots of changes in my project, so I blamed the code, which has lost me about 10 hours :(.
