### ISSUE TITLE
undefined reference to `InterlockedAdd64' and `_mkgmtime'

### ISSUE THREAD

**Issue by eddyyanto** [civetweb/civetweb#491]
Trying to compile with Qt after a fresh clone and I've got a few undefined references.

- Windows 8
- Qt 5.3.2
- MinGW

Any thought?

```
11:21:25: Running steps for project CivetWeb...
11:21:25: Configuration unchanged, skipping qmake step.
11:21:25: Starting: "C:\Qt\Qt5.3.2\Tools\mingw482_32\bin\mingw32-make.exe" 
C:/Qt/Qt5.3.2/Tools/mingw482_32/bin/mingw32-make -f Makefile.Debug
mingw32-make[1]: Entering directory 'C:/Users/HP/Documents/GitHub/civetweb/build-CivetWeb-Desktop_Qt_5_3_MinGW_32bit-Debug'
g++ -Wl,-subsystem,console -mthreads -o debug\CivetWeb.exe debug/civetweb.o debug/main.o  -lws2_32 -lComdlg32 -lUser32 -lShell32 -lAdvapi32 
debug/civetweb.o: In function `mg_atomic_add':
C:\Users\HP\Documents\GitHub\civetweb\build-CivetWeb-Desktop_Qt_5_3_MinGW_32bit-Debug/../src/civetweb.c:864: undefined reference to `InterlockedAdd64'
debug/civetweb.o: In function `parse_date_string':
Makefile.Debug:79: recipe for target 'debug\CivetWeb.exe' failed
C:\Users\HP\Documents\GitHub\civetweb\build-CivetWeb-Desktop_Qt_5_3_MinGW_32bit-Debug/../src/civetweb.c:6652: undefined reference to `_mkgmtime'
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: Leaving directory 'C:/Users/HP/Documents/GitHub/civetweb/build-CivetWeb-Desktop_Qt_5_3_MinGW_32bit-Debug'
Makefile:34: recipe for target 'debug' failed
mingw32-make[1]: *** [debug\CivetWeb.exe] Error 1
mingw32-make: *** [debug] Error 2
11:21:26: The process "C:\Qt\Qt5.3.2\Tools\mingw482_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project CivetWeb (kit: Desktop Qt 5.3 MinGW 32bit)
When executing step "Make"
11:21:26: Elapsed time: 00:01.
```

**Comment by bel2125** [comment]
A continuous integration build and test with MinGW is running in several configurations.
In the current version, both the [32-bit](https://ci.appveyor.com/project/civetweb/civetweb/branch/master/job/nhxv6aare0e3r43g) and [64-bit](https://ci.appveyor.com/project/civetweb/civetweb/branch/master/job/dfterxt4j9t6g10x) MinGW build is running OK (no errors, no warnings, all integration tests pass).

What configuration options are you using (the `USE_*` defines)?
You are using the 32 bit MinGW version and build for Win32?

**Comment by bel2125** [comment]
It seems, the missing `_mkgmtime` is a bug of MinGW 32 bit, and fixed in the 64 bit version - see https://sourceforge.net/p/mingw-w64/bugs/473/
Or it's a feature from Visual Studio 2008 that never got added to some versions of MinGW - http://mingw.5.n7.nabble.com/Missing-mkgmtime-in-time-h-td8976.html
But it seems to be present in MinGW i686-5.1.0


`InterlockedAdd64` is only used if `USE_SERVER_STATS` is defined.
Again, recent MinGW versions/distributions seem to have this function.
However, in a next civetweb version, you could use the `NO_ATOMICS` define, to avoid all "Interlocked"/"sync_fetch"/.. operations - I don't know about the performance penalty.

**Comment by eddyyanto** [comment]
Yes, I am using the mingw_32. In that case, I  guess this issue is more of a IDE or a compiler thing.
Closing this now.
