### ISSUE TITLE
Question: Does civetweb support RTMP?

### ISSUE THREAD

**Issue by zhangsw** [civetweb/civetweb#492]
I'm a newer to civetweb. I'm not sure whether civetweb supports rtmp like nginx. Could anyone tell me about this?

**Comment by bel2125** [comment]
> Question: Does civetweb support civetweb?

Yes, absolutely ;-)

> I'm not sure whether civetweb supports rtmp like nginx.

I don't know any details on the rtmp support of nginx. 
There are different variations of RTMP ([RTMP Wikipedia](https://en.wikipedia.org/wiki/Real-Time_Messaging_Protocol)). Probably you are only interested in RTMPT, since both nginx and CivetWeb are HTTP servers (don't know if nginx supports any other RTMP version as well).

You probably can use CivetWeb for the HTTP tunnel, but you will need some source for the RTMP media content. I don't know how RTMP media servers work, and what kind of interface they provide for tunnelling.

**Comment by bel2125** [comment]
I just found, nginx seems to be a RTMP media server on it's own (according to [this list](https://en.wikipedia.org/wiki/List_of_RTMP_software#RTMP_server_software)), with the [nginx-rtmp-module](https://github.com/arut/nginx-rtmp-module). 

Currently there is no equivalent module for CivetWeb - at least I don't know it ... 
... but wait: Google knows when just looking for "RTMP civetweb".
Maybe this could help you: https://github.com/Tigerdile/rtmptd

Please tell, if this is the module you are looking for (so I also know, civetweb now supports rtmp).

**Comment by zhangsw** [comment]
Yeah~ I think it is. Thanks~

**Comment by bel2125** [comment]
So, I think we can consider this question as answered, and close this issue.
