### ISSUE TITLE
Does SSL support work when I'm embedding Civet?

### ISSUE THREAD

**Issue by jbmonroe** [civetweb/civetweb#509]
...or does it only work if I build CivetWeb as a stand-alone web server?

**Comment by bel2125** [comment]
sure, it works embedded and standalone

You can consider the "standalone" server as [civetweb.c](https://github.com/civetweb/civetweb/blob/master/src/civetweb.c) embedded into [main.c](https://github.com/civetweb/civetweb/blob/master/src/main.c) - or you can have a look at the [embedded_c.c](https://github.com/civetweb/civetweb/blob/master/examples/embedded_c/embedded_c.c) example. It works as long as you do not set the `#define NO_SSL`.
Do you plan to use OpenSSL as your SSL/TLS library?

**Comment by jbmonroe** [comment]
Yes, with a customer-supplied certificate.  I've been reading up on how to get it all working (although I'm not doing the coding on this--for a change!).

**Comment by bel2125** [comment]
If you are using OpenSSL, everything should work out of the box. You can choose to set `#define NO_SSL_DL` to use openssl as load-time dependency (instead of as run-time dependency). 

There are also some minimum examples in [Embedding.md](https://github.com/civetweb/civetweb/blob/master/docs/Embedding.md) (for HTTP only). The unit test ([function `test_mg_start_stop_https_server`](https://github.com/civetweb/civetweb/blob/master/test/public_server.c#L529)) is somewhat harder to read - maybe I'll add a minimum HTTPS example as well.

**Comment by jbmonroe** [comment]
Thanks--I'm not too worried about the load-time issue.  The code in question will run continuously after starting (taking into account however often the customer chooses to restart the VMs).

**Comment by bel2125** [comment]
Anything else I can do to help?
Or should we close this issue?

**Comment by jbmonroe** [comment]
Feel free to close--it was more of a question and Github just isn't good
with plain old questions. :)
