### ISSUE TITLE
Set timeout for mg_websocket_write

### ISSUE THREAD

**Issue by siyangy** [civetweb/civetweb#517]
I have an application that uses mg_websocket_write to send data every 0.1 seconds. I'd like to set some sort of timeout so that the server will drop the current frame of data when it's taking too long. I tried to set the timeout manually by setsockopt(conn->client.sock, SOL_SOCKET, SO_SNDTIMEO, timeout), however, it looks like mg_connection is a forward declaration and I cannot access client.sock from outside. I also tried to set request_timeout_ms, but that didn't seem to work either.

I noticed a comment from the source code: 'set_sock_timeout is not required for non-blocking sockets.', and the set_socket_timeout related code is commented out. The socket doesn't seem to be 'non-blocking' to me though. I am testing this by cutting off the network while my application is sending data, and it just hangs there after the network is down.

**Comment by bel2125** [comment]
Beside `request_timeout_ms` there is also `websocket_timeout_ms` for websockets. Did you try this as well?

Otherwise, I need to understand it in more detail: 
  - The server is sending data cyclically to the client, and you unplug the cable directly at the server port? Or after some switch? So, is the link physically/electrically down, and the server operating system notices this immediately?
  - Does the client send some data back to the server? If so, at what rate?
  - Is the client a browser or are you using another type of client (some machine to machine communication)? If machine to machine, what client are you using (and, do you know: does it support websocket ping pong)?
  - Are you using the ping pong mechanism at server side?
  - Are you serving one or many clients with the same data? So, is it like a broadcast service for many clients that are only listening, or is it more a request response to an individual client?

**Comment by siyangy** [comment]
I don't think websocket_timeout_ms is related here, which from my understanding is similar as keepalive timeout rather than a timeout for sending data itself. What I want is simply a mechanism that will return after a specific time while mg_websocket_write is blocked.

To answer your questions:
1. yes, I essentially unplugged the cable.
2.  I have my client sending a heartbeat every 10 seconds so the the connection won't be cut off from server side, as the default websocket_timeout_ms is 30s.
3. The client is a browser.
4. Not quite sure about this one, the client does not echo back for each of the message it receives.
5. Yes, the server broadcasts the same data to one or more clients using a push model.

**Comment by bel2125** [comment]
Are you sure it's blocking in the send call? It shouldn't, since it's set to non-blocking here

https://github.com/civetweb/civetweb/blob/2ebc7989b3d39e950225a0e26ecacbf6c42a7db0/src/civetweb.c#L8133

but maybe the operating system still blocks - what OS are you using?
Or could it be blocking in the select here:

https://github.com/civetweb/civetweb/blob/2ebc7989b3d39e950225a0e26ecacbf6c42a7db0/src/civetweb.c#L5565

Ping pong is special websocket protocol message. If you did not add some extra calls, you do not use it. It would help you to discover if a client is disconnected.

But before going into any details, this "non blocking socket is blocking" needs to be clarified - this concept will not work if the sockets are blocking.

**Comment by siyangy** [comment]
Right, that's where I got confused, what's the expected behavior when a socket is set as non-blocking? My OS is Ubuntu 14.04 LTS. 

I suspect it was blocked at https://github.com/civetweb/civetweb/blob/2ebc7989b3d39e950225a0e26ecacbf6c42a7db0/src/civetweb.c#L5499. I changed the civet source code a little bit to set SO_SNDTIMEO, and it did get out of mg_websocket_write instead of blocking forever.

**Comment by bel2125** [comment]
> what's the expected behavior when a socket is set as non-blocking? 

From https://linux.die.net/man/2/send:
> No indication of failure to deliver is implicit in a send(). Locally detected errors are indicated by a return value of -1. 

> When the message does not fit into the send buffer of the socket, send() normally blocks, unless the socket has been placed in nonblocking I/O mode. In nonblocking mode it would fail with the error EAGAIN or EWOULDBLOCK in this case. 

So, the expected behaviour would be: If the connection is broken, first of all the `send` call still succeeds and places data into the send queue of the operating system. Only after the send queue is full, there is a difference between blocking and non-blocking. Blocking sockets should wait in the send call until there is space in the send queue or until SO_SNDTIMEO. Non-Blocking must not wait but immediately return -1 and set errno to EAGAIN or EWOULDBLOCK.

**Comment by bel2125** [comment]
And from https://linux.die.net/man/7/socket

> **SO_RCVTIMEO** and **SO_SNDTIMEO**
    Specify the receiving or sending timeouts until reporting an error. The argument is a struct timeval. If an input or output function blocks for this period of time, and data has been sent or received, the return value of that function will be the amount of data transferred; if no data has been transferred and the timeout has been reached then -1 is returned with errno set to EAGAIN or EWOULDBLOCK, or EINPROGRESS (for connect(2)) just as if the socket was specified to be nonblocking. If the timeout is set to zero (the default) then the operation will never timeout. Timeouts only have effect for system calls that perform socket I/O (e.g., read(2), recvmsg(2), send(2), sendmsg(2)); timeouts have no effect for select(2), poll(2), epoll_wait(2), and so on. 

So, setting SO_SNDTIMEO and SO_RCVTIMEO to 1 microsecond (the smallest value in struct timeval larger than 0), it should behave *almost* like a non-blocking socket (but blocking for a microsecond seems weird and inefficient - I would not do this without tests on a lot of different systems).

**Comment by bel2125** [comment]
I think there was a problem in `set_blocking_mode` for Linux. 
I have to repeat some tests with the recent version.

**Comment by siyangy** [comment]
Thanks for the thorough explanation! I changed my application and I am no longer bothered by this problem. Still, it's probably worth investigating why non-blocking socket is not working as intended on Civet side.

**Comment by bel2125** [comment]
I will have a look - we are anyway currently testing a release candidate.
So, since you have a solution, we can close this issue, right? Issues occurring during the release test are managed here #512, and #517 is "your" issue that's solved for you.

**Comment by siyangy** [comment]
sure, closing.
