### ISSUE TITLE
CPU usage 100% / index file served even though not requested?

### ISSUE THREAD

**Issue by user1313** [civetweb/civetweb#519]
I have downloaded the latest commit (i think it was 2ebc7989b3d39e950225a0e26ecacbf6c42a7db0) and have a problem. When the CGI file does not exist, or has no permission set, or in any other case that it is not a successful execution of that file, the Civetweb starts to behave strangely. I think when the file does not exist, e.g. "https://hostname/cgi/test3252.cgi", it serves the index file instead, in my case it is "/index.cgi". When the requested file exists, but there are problems while executing the file, Civetweb starts to use one complete core at 100% and it seems it does it forever. I just reverted back to 1.9.1 and it is fine in that both regards. However, the test in 1.9.1 was on port 80 and plain http. I had to upgrade because we are moving to a SSL-only and 1.9.1 crashes with another error:

load_dll: libcrypto.so: cannot find CRYPTO_num_locks
Failed to start CivetWeb V1.9.1:
load_dll: libcrypto.so: cannot find CRYPTO_num_locks

This is the command i am using to start the server
/usr/local/bin/civetweb -listening_ports 80r,443s -run_as_user MYUSERNAME -enable_directory_listing no -request_timeout_ms 86400000 -document_root /home/MYUSERNAME/PROJECTNAME -ssl_certificate /home/MYUSERNAME/config/PROJECTNAME

**Comment by bel2125** [comment]
`CRYPTO_num_locks` is part of the OpenSSL 1.0.x API.
The OpenSSL 1.1.x API does no longer have this function.
CivetWeb 1.9 and earlier need to use OpenSSL 1.0.x (or alternatively 0.9.x).
OpenSSL 1.1 support is added in CivetWeb 1.10

I can reproduce the index.cgi file is sent, but I cannot reproduce an increased CPU load.

**Comment by bel2125** [comment]
Now it's clear for me, why `index.cgi` is called.
It's a side effect of the enhancement "Allow sub-resources of index script files" - see [V 1.10 release notes](https://github.com/civetweb/civetweb/blob/master/RELEASE_NOTES.md#release-notes-v110)

It works like this:

**Up to V1.9**, you could have scripts like
1) `/path/to/script.cgi`
and you could have "script resources" like
2) `/path/to/script.cgi/sub/thing.here`
So the script `/path/to/script.cgi` could handle `/` (for (1)) and ' /sub/thing.here' (for (2)).
In V1.9 you could also have
3) `/some/other/path/index.cgi`
requests to `/some/other/path/index.cgi` work for this script,
and requests to '/some/other/path/` are also redirected to this index script.
In V1.9, you could also have
4) `/some/other/path/index.cgi/some.thing`
requests to `/some/other/path/index.cgi/some.thing` work for this script as well,
but in **V1.9** you could not omit the `index.cgi`, so the short-cut to `/some/other/path/some.thing` did not work. So from the client point of view, the URL  `/some/other/path/` was not able to handle sub-resources, only `something.cgi` (or .lua) could do.

In **V1.10** this limitation was removed, so `/some/other/path/some.thing` is redirected to  `/some/other/path/index.cgi/some.thing` with `PATH_INFO='/some.thing'`.

This has the consequence, that `/some/invalid/path/file.ext` might be handled by
`/some/invalid/path/file.ext` (with `PATH_INFO='/'`, or without PATH_INFO since .ext is not a script)
`/some/invalid/path/index.cgi` with `PATH_INFO='/file.ext'`
`/some/invalid/index.cgi` with `PATH_INFO='/path/file.ext'`
`/some/index.cgi` with `PATH_INFO='/invalid/path/file.ext'`
`/index.cgi` with `PATH_INFO='/some/invalid/path/file.ext'`

Effectively an `/index.cgi` on top level will catch all 404 "Not Found".
This was not really intended, but thinking about it, this is a clear consequence of this enhancement.

Probably we need some filter or some option to turn this off ... I have to think about it.

Still, this does not explain a 100% CPU load - I also do not observe this in my test. Maybe your CGI script requires 100% CPU - did you check what process causes this CPU load?

**Comment by bel2125** [comment]
Note: Check this in release tests (#512)

**Comment by bel2125** [comment]
@user1313: For a further analysis, please check if the CPU load is caused by your `index.cgi` (maybe by replacing it with [a simple test script](https://github.com/civetweb/civetweb/blob/master/test/linux.cgi)).

**Comment by user1313** [comment]
Thank, your fast answer is highly appreciated.

With SSL and 1.10 trunk i got A on https://www.htbridge.com/ssl/. Thanks to that our IT guys allowed me to expose civetweb to the public.

With the index file i understood, but this is not a big problem, you can even see i renamed the topic, because i found this side effect while testing the 100% CPU problem.

Regarding the 100%, it is the civetweb itself! I even put an one-liner like below (not even a shebang line) as a cgi script, with the same result.
`crash this file`

**Comment by user1313** [comment]
i will start civetweb tomorrow morning with an empty document_root  and will see if 100% appears, just to exclude some problem on my side. Please hold.

**Comment by user1313** [comment]
I can confirm the behavior. It seems to appear only with files that have an extension related to CGIs. I tried .pl, .php, .cgi and they all seem to induce this bug. Files without an extension or .txt or .xnr files are not affected. So i will try to explain once more.

1. Any cgi file that does not execute properly, such as one with a typo, or a missing library dependence. So anything that when executed on the command line gives an error, when run from Civetweb makes Civetweb use 100% of the CPU core. The content of my current file which hangs the server is just one line:
file 1: `crash this file`
while the other test file works fine with any extension (or no extension):
file 2: ```
#!/usr/bin/perl
print "\n\n";
print "crash this file";
```

2. I tried different paths:
a) /test.cgi
b) /cgi/test.cgi
c) /folder/test.cgi/
d) /cgi/test

It seems the path has no influence, only the extension. Also, in this test i don't have any index files. The document_root contains only one file, within a folder or (in one case) not. I also tried to play with the permissions, it has absolutely no influence whether it is 777 or 000, if the file's content is rubbish. But! Also if the file content is not rubbish (see file 2 above), the moment i remove either the execute or read permission for the owner of the file (and server is run by the same user), i get a hang. So:
Rubbish file 1 with cgi/pl/php extension -> hang.
Rubbish file 1 with no_extension/txt/xnr extension -> ok, file content listed.
Non-rubbish file 2 with cgi extension and 100 permission -> hang.
Non-rubbish file 2 with cgi extension and 400 permission -> hang.
Non-rubbish file 2 with cgi extension and 500 permission -> ok.

**Comment by user1313** [comment]
just noticed that when i ctrl+c civetweb it prints few lines of errors. The number of lines is suspiciously equal to the amount of cores at 100%.


CivetWeb V1.10 started on port(s) 8080,80r,443s with web root [/home/username/project]

^CExiting on signal 2, waiting for all threads to finish...Error: CGI program sent malformed or too big (>16384 bytes) HTTP headers: []
Error: CGI program sent malformed or too big (>16384 bytes) HTTP headers: []
Error: CGI program sent malformed or too big (>16384 bytes) HTTP headers: []
Error: CGI program sent malformed or too big (>16384 bytes) HTTP headers: []
Error: CGI program sent malformed or too big (>16384 bytes) HTTP headers: []
Error: CGI program sent malformed or too big (>16384 bytes) HTTP headers: []
 done.

**Comment by bel2125** [comment]
I think you just run into the timeout:

/usr/local/bin/civetweb -listening_ports 80r,443s -run_as_user MYUSERNAME -enable_directory_listing no -request_timeout_ms ***86400000*** -document_root /home/MYUSERNAME/PROJECTNAME -ssl_certificate /home/MYUSERNAME/config/PROJECTNAME

Could you test if it works if you set the timeout to 1000?

**Comment by user1313** [comment]
Just checked, 1.10 hangs for 1 second, then returns the error. 1.9 returns the error right away. Am i missing something?

**Comment by bel2125** [comment]
By the way, a request timeout of 86400000, which is 24 hours, will make the server extremely vulnerable  to denial of service attacks - just open "telnet localhost 8080" for 50 times (-num_thread times), and that's it for 24 hours.

**Comment by bel2125** [comment]
> Just checked, 1.10 hangs for 1 second, then returns the error. 
> 1.9 returns the error right away. Am i missing something?

V1.9 did not distinguish between error and timeout here. If you don't send an appropriate CGI header immediately, V1.10 waits some timeout for a CGI response.
The difference should be only visible for "slow" cgi scripts (like https://github.com/civetweb/civetweb/blob/master/test/delayed.cgi)

**Comment by user1313** [comment]
OK, i am even more confused now. Can i disable this behavious in 1.10? Do you confirm the 100% usage problem in 1.10? am i missing something here that a 100% usage even with broken files and 24h timeouts should not happen?
Thanks.

**Comment by bel2125** [comment]
This is the current result from my investigation:

1) Independent from V1.9 or V1.10, you should not set a 23h timeout for a server accessible from the internet
2) In V1.9, the server did not use a timeout to waiting for a response from the CGI program, while in V1.10 it waits the `request_timeout_ms`. This is due to some restructuring that distinguishes better between "timeout" and "I/O error". Here, the same function is used for reading from sockets and reading from the CGI process. While the improvement in V1.10 definitely makes sense for sockets, having this timeout for a pipe can be reconsidered.
3) While waiting for a response is an "idle wait" for sockets (using the `select` function), it is a "busy wait" for CGI processes. This is not a problem for correct CGI programs that do send a header quickly. However, it turns out to fill one CPU core during the timeout for programs that don't. Meanwhile I can reproduce this.
4) Then there is this change for `index.cgi` mentioned above (https://github.com/civetweb/civetweb/issues/519#issuecomment-329590388).

So, who's turn is it:

1) yours ... this is in your config - I strongly recommend to use a timout not longer than a few seconds
2) mine ... thinking about if it's meaningful to have a timeout for CGI, maybe removing it, then give you feedback
3) mine ... it should not be a busy wait. I will either fix the busy wait, which is ~2 lines of code, or remove the timeout for CGI entirely (see 2), so it's no longer required
4) either yours or mine or both ... I will add a switch to disable index scripts having sub-resources, alternatively you can make your index script handle a 404 directly, and of course we can do both

**Comment by user1313** [comment]
1. I will definitely remove the long timeout, you have convinced me that i have to do it finally. I will leave the default 30 seconds.

3. how about a program which buffers the output until the end of its execution? Would that be still a busy wait?

Thanks, i think we mostly clarified the issue now.

**Comment by bel2125** [comment]
The busy wait problem existed only for bad CGI programs, so it's the combination of high timeout, bad scripts and maybe index.cgi, otherwise it would be hard to even notice this behaviour.

Anyway, reading from the CGI program is done as blocking IO without timeout now, so this should behave just like it was in V1.9 (solving 2 and making 3 obsolete)

So the only thing left to do is to add a parameter, if index scripts are used for sub-resources or not (4).

**Comment by bel2125** [comment]
I added the configuration parameter `allow_index_script_resource` with default `no`, so in respect to (4) V1.9 and V1.10 behave the same way now. Unless someone sets `allow_index_script_resource` to `yes`, of course.

I think this new feature is valuable, but causes more confusion if it's accidentally activated, without the server admin even knowing - that's why the default is `no`.

**Comment by bel2125** [comment]
So, I think all issues and otherwise weird appearing behavioral traits are gone now.
Could you repeat your test?

**Comment by user1313** [comment]
I can confirm that sub-resources are off.

**Comment by bel2125** [comment]
Fine. Bad scripts are also handled the same way as in V1.9 and before
So, let's close this issue.
