### ISSUE TITLE
noisy STDERRs of CGIs cause problems

### ISSUE THREAD

**Issue by user1313** [civetweb/civetweb#529]
Hi,

I have just come across this. I am dealing with BioPerl modules (http://bioperl.org/), some of them are very noisy and output lots of warnings on STDERR. I took me a while to understand what was happening. At the moment i am avoiding this issue by silencing warnings in CGI scripts:

$SIG{'__WARN__'} = sub { warn $_[0] unless ( caller eq "Bio::Root::RootI" ); };

But i though you may want to know that this causes trouble if there is a lot of warnings - such CGIs  choke the server. It is also quite bad that the default timeout  of 30 seconds does not help. Server was blocked indefinitely, at least from what i could try.

Regards,

**Comment by bel2125** [comment]
From my understanding, a CGI process should either send a valid response to stdout, OR an error message to stderr. CivetWeb checks for a valid response from stdout first. Only if there is no valid data it reads up to 16kB from stderr.

It should not be possible to block the server for longer ... I will try to reproduce this by some script generating a lot of dummy data.
What CivetWeb version are you using - could you post the output of "civetweb -I"?

**Comment by user1313** [comment]
This is strange that you say STDOUT first. My CGI continuously produced few megabytes of data to STDOUT which was successfully read by the client (Google Chrome or Firefox) before download stopped. Now, when i silenced STDERR, i could download 1.5GB in one request.

Freshly downloaded V1.10 release today:


CivetWeb V1.10 (CivetWeb V1.10)
{
"version" : "1.10",
"os" : "Linux #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) (4.9.0-3-amd64) - x86_64",
"features" : 3207,
"feature_list" : "Server: Files HTTPS CGI Cache",
"build" : "Oct  5 2017",
"compiler" : "gcc: 6.3.0",
"data_model" : "int:2/4/8/8, float:4/8/16, char:1/4, ptr:8, size:8, time:8"
}

**Comment by bel2125** [comment]
I can reproduce this by adding one line to [linux.cgi](https://github.com/civetweb/civetweb/blob/master/test/linux.cgi):

```
#!/bin/sh

printf "Content-Type: text/plain\r\n"
printf "\r\n"

echo "This is a shell script called by CGI:"
tree / 1>&2
echo
set

```

I will have a closer look why this blocks the request for at least an hour next week.

**Comment by bel2125** [comment]
CivetWeb specific analysis result
---

The issue is reproducible with any script that fills the stderr buffer to overflow. The intention of using stderr in CivetWeb was, a CGI script can EITHER write a correct message to stdout (the HTTP response for the client), OR write a SHORT error message to stderr (a one-liner in the error log). It was never intended to use stderr as a debug logging aid.

This has been clarified in the documentation.

General considerations
---

According to this article (https://docstore.mik.ua/orelly/linux/cgi/ch03_01.htm), there is no general consensus how stderr is handled in CGI scripts:

> 3.1.1.3. STDERR
>
> CGI does not designate how web servers should handle output to STDERR, and servers implement this in different ways, but they almost always produces a 500 Internal Server Error reply. Some web servers, like Apache, append STDERR output to the web server's error log, which includes other errors such as authorization failures and requests for documents not on the server. This is very helpful for debugging errors in CGI scripts.
>
> Other servers, such as those by iPlanet, do not distinguish between STDOUT and STDERR; they capture both as output from the script and return them to the client. Nevertheless, outputting data to STDERR will typically produce a server error because Perl does not buffer STDERR, so data printed to STDERR often arrives at the web server before data printed to STDOUT. The web server will then report an error because it expects the output to start with a valid header, not the error message. On iPlanet, only the server's error message, and not the complete contents of STDERR, is then logged.

CivetWeb specific rules for stderr
---

The rules for CivetWeb have been added to the [UserManual](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md).

> In case a CGI script cannot handle a particular request, it might
write a short error message to stderr instead of writing to stdout.
This error message is added to the server error log.
>
> A script should not write to stderr after writing a reply header
to stdout. In case CGI libraries are writing to stderr (e.g., for
logging/debugging), the CGI script should redirect stderr to a 
user defined log file at the beginning of the script.

Remaining issue
---

Although debug logging to stderr is not the intended use case, it should not completely deadlock the CGI script. Current idea is to reach this with a general CGI timeout. This will stop stderr-noisy CGI scripts as well as endless loops of all kinds.
Logging should be done with a different function provided by the CGI script or by manually writing a log file.

**Comment by bel2125** [comment]
Adding a CGI timeout is an additional feature: #618

**Comment by bel2125** [comment]
Solved using a new configuration parameter `cgi_timeout_ms` - see #618

**Comment by bel2125** [comment]
CGI timeouts can be used in the new release V1.11
