### ISSUE TITLE
SSL_CTX_set_info_callback VS 2015

### ISSUE THREAD

**Issue by grunk** [civetweb/civetweb#536]
Hi,

i'm trying to update to the recent 1.10 version but i have an error with visual studio 2015 on SSL_CTX_set_info_callback.
The comment above the line seems to claim that it could cause a warning , but in my case i got an error : 

> C2664	'void SSL_CTX_set_info_callback(SSL_CTX *,void (__cdecl *)(const SSL *,int,int))': cannot convert argument 2 from 'void (__cdecl *)(SSL *,int,int)' to 'void (__cdecl *)(const SSL *,int,int)'	vendor	D:\C++\Projets\a\src\cpp\vendor\civetweb.cpp	14324

What can i do to fix that ? (it's compiling by simply commenting it out but i guess this this not a viable solution).

Thanks ;)

**Comment by bel2125** [comment]
The pre-built binaries on SourceForge are compiled with Visual Studio 2015, so it was not an error in this case. Probably you are compiling with C++ instead of C? ... seems you renamed civetweb.c to civetweb.cpp, so the "const" for the "SSL *" is an error instead of a warning.

You could add this "const" [here](https://github.com/civetweb/civetweb/blob/53ab2e364e1d0a4936184373d008691c59442c6e/src/civetweb.c#L14304), then it will work for you without this C warning (C++ error).

Unfortunately, it will raise a warning in other cases ... like in noted in [this comment](https://github.com/civetweb/civetweb/blob/53ab2e364e1d0a4936184373d008691c59442c6e/src/civetweb.c#L14425):
```C
	/* Depending on the OpenSSL version, the callback may be
	 * 'void (*)(SSL *, int, int)' or 'void (*)(const SSL *, int, int)'
         ...
```
So, in the moment I have no idea how to solve it for all versions and operating systems.

I could add something like 
```C
#ifdef SSL_VERSION_NEEDS_CONST_POINTER_AS_FIRST_ARGUMENT_OF_SSL_INFO_CALLBACK
static void
ssl_info_callback(const SSL *ssl, int what, int ret)
#else
static void
ssl_info_callback(SSL *ssl, int what, int ret)
#endif
```

but this appeared emetic to me.

**Comment by grunk** [comment]
I'am indeed compiling in cpp.
Adding `const` to `ssl_info_callback` did the trick.

Openssl seems to be a real pain to work with :(

Thanks for your time 👍
