### ISSUE TITLE
Conditional url rewrite rules

### ISSUE THREAD

**Issue by samal84** [civetweb/civetweb#551]
I am working on a single page application and need to rewrite urls that don't match files anywhere inside document root to go to the index.html file at document root.

So all the actual static files inside my document root will actually be resolved to themselves so that they can be fetched. But all other urls will be rewritten to the index.html in document root, so that all possible "virtual" urls in my single page application will work.

Example for use case: https://stackoverflow.com/questions/14319967/angularjs-routing-without-the-hash

Any possibility for this?

**Comment by bel2125** [comment]
There are different ways to do this.

I would use a 404 handler page for this. Create a directory, put a file named `error404.something` there, and set the parameter `error_pages` to this directory.
The `.something` could be `.html`, `.cgi`, `.lua`, `.php` ... depending on how you built the server.
If you want to redirect to `intex.html` from there, do it as HTML or HTTP redirect.

**Comment by bel2125** [comment]
Did you manage to work do your redirect with `error_pages`, or do you need some alternative way to do this?

Do you more information, or can we close this issue?

**Comment by samal84** [comment]
Well we only have three sub routes that we know we need to support in our app, so we just added specific rewrite rules for those and that is working fine already. Ideally we wouldn't need to maintain these specific rules, hence the question.

I'll let you know when we get so far as to test the 404 error page with http redirect approach.

**Comment by bel2125** [comment]
> I'll let you know when we get so far as to test the 404 error page with http redirect approach.

It's about 5 months since the last comment. Did you do the tests? Can we close this issue?

**Comment by samal84** [comment]
Hi again :) Yeah we got by with just a few url rewrite rules for subdirs, so we never tried the 404 error redirect method.

**Comment by bel2125** [comment]
So, can we close this issue?

**Comment by samal84** [comment]
For my sake right now we can close it. There doesn't seems to be interest for conditional rewrite rules from anyone else either yet so I guess closing is the right thing right now. I opened this issue, so I'm allowed to close.

**Comment by michel47** [comment]
I would like to a "200.html" redirect scheme implemented w/ civetweb, in would be awesome for "modern" website.

 using 404.html for conditional rewrite is not exactly the same as a "catch-all" page like 200.html
the way it works is as  explained by @the-rasmussen if the document.location.pathname exists then it is served,
otherwise a 200.html file is served if it exists and the header's status is 200, and 404.html if the file 200.html is missing
(ideallly ./200.html then ../200.html then ../../200.html etc. until /200.html would be tested, then /400.html)

The main difference with a 404.html redirect is the reponse status is 200 OK, which make a huge difference for an angular type of page routing !

**Comment by bel2125** [comment]
I know this already works - I will explain one way to do this below. I don`t know if this is the best way to deal with this if you are using Angular - I don't use Angular myself, but I might get some recommendation of an Angular guy who already solved this somehow.

This is one way (how I would do this ... without deeper Angular knowledge):
Use a 404.lua or 404.lp file or a 404.cgi file (instead of 404.html) - the lua and lp files are script files that can return whatever status they feel like. The file name "404" tells civetweb to use this file in case of a "404 Not Found". Alternatively you could use a "4xx.lua" file to catch all "request errors" (400-499), or just an error file without number to catch all errors. The extensions are the same as for directory index files: "index.xhtml,index.html,index.htm,index.lp,index.lsp,index.lua,index.cgi,index.shtml,index.php" if you build with Lua, "index.xhtml,index.html,index.htm,index.cgi,index.shtml,index.php" if you build without - in this search order.
For everything except xhtml, html, htm and shtml you can freely define the HTTP response status code.
A script should also get the original request uri for the missing document/resource - you can still decide where to go there.

Another way would be to activate the configuration "allow_index_script_resource". This allows you to use a file "/path/to/index.lua" (or cgi) on the server, that is going to handle "/path/to/something", "/path/to/something/else", "/path/to/whatever", "/path/to/everything", ... Again: Not sure if the Angular guys used it this way to get their unknown URLs redirected, or yet another way.

In case we are still missing some features, we can definitely add it to civetweb.
