### ISSUE TITLE
SSL_ERROR_SSL in OS X with self signed certificate

### ISSUE THREAD

**Issue by vanimayya** [civetweb/civetweb#553]
I have integrating Civetweb for OS X and and invoking with following options:

 callbacks.begin_request = beginHandler;
 callbacks.init_ssl = sslHandler;

 const char *options[] = {
       "document_root", "~/Sites",
       "listening_ports", "10001s",
       "ssl_certificate", "Self_signed.pem",
       "num_threads","1",
       NULL
     };
Installed the self signed certificate in key chains. But When I invoke the localhost url, connection always disconnects in sslize(..) function with err = SSL_get_error(conn->ssl, ret); returning SSL_ERROR_SSL.
Could anyone please put some light to resolve this?

**Comment by bel2125** [comment]
What version are you using?

**Comment by vanimayya** [comment]
CivetWeb Version: 1.11
OS X: Sierra (10.12)

**Comment by bel2125** [comment]
1.11 is the current development version (not released, only automatic tests). Some features intermediate versions may have bugs. What commit number did you use? Did you check if this commit number passes the CI test for OSX?

**Comment by vanimayya** [comment]
Tried with 9351729, it gives the same error:

 consume_socket:16481: grabbed socket 15, going busy
worker_thread_run:16653: Start processing connection from 127.0.0.1
 mg_cry:3408: mg_cry: sslize error: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
 worker_thread_run:16696: Connection closed
 consume_socket:16477: going idle
I generated the .pem file as mentioned in https://github.com/civetweb/civetweb/blob/master/docs/OpenSSL.md.  Installing the root certificate also did not help.
Anything other settings are needed for OS X?

**Comment by bel2125** [comment]
From the error message "SSL23_GET_CLIENT_HELLO:unknown protocol", it seems the client uses a protocol not supported by the server. Since you do not have an [`ssl_prococol_version`](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#ssl_protocol_version-0) setting to disable old SSL/TLS versions in the server, it's maybe some extreme version mismatch between the SSL libraries of client and server? 

It could be related to the certificates as well: Did you test the certificate in [resources/cert/server.pem](https://github.com/civetweb/civetweb/blob/master/resources/cert/server.pem)?

You could also try with another client - maybe with the openssl command line interface:
`openssl s_client -connect localhost:10001`
compare to
`openssl s_client -connect google.com:443`

> Anything other settings are needed for OS X?

I don't have a local OS X system to test this myself - I can only run remote tests, on machines I do not administrate myself. So I cannot really help checking if it could be some general OS X configuration error. I can only tell the commit number above has no principal issue with self signed certificates on OS X.

**Comment by vanimayya** [comment]
Thank you bel2125  for useful information. The root cause of issue was though libssl_1.0.0.dylib was linked, libssl.dylib(older version) was being loaded in code. Changing the SSL_LIB to new path, resolved the issue. 
Is there any way, we could link these libraries statically?

**Comment by bel2125** [comment]
> Is there any way, we could link these libraries statically?

Set the `NO_SSL_DL` flag (see [docu](https://github.com/civetweb/civetweb/blob/master/docs/Building.md#setting-compile-flags)) ... it will cause static linking of the libraries set by `SSL_LIB` and `CRYPTO_LIB` (see [docu](https://github.com/civetweb/civetweb/blob/master/docs/Building.md#setting-build-options)).
But do not set `NO_SSL` ... this will deactivate SSL/TLS/HTTPS completely, while `NO_SSL_DL` will deactivate dynamic linking but use static linking.

**Comment by bel2125** [comment]
Did you try it?
Is there anything else you need for this topic?

**Comment by bel2125** [comment]
No more activities since 3 months.
Closing this issue.
