### ISSUE TITLE
Compile Warning in GCC 6.3.0

### ISSUE THREAD

**Issue by marcoafo** [civetweb/civetweb#561]
Hi there,

Recently I started to use civetweb in gcc 6.3, like this:

`$ gcc --version`
`gcc (Debian 6.3.0-18) 6.3.0 20170516`
`$ gcc -c -Wall -I./source/ -o /tmp/civetweb.o ./source/civetweb.c`

But I don't remember seeing the warning below.

`./source/civetweb.c: In function ‘mg_get_system_info_impl’:`
`./source/civetweb.c:17862:32: warning: ‘-Werror’ is not an option that controls warnings [-Wpragmas]`
` #pragma GCC diagnostic ignored "-Werror"`

Everything works as expected, but this keeps nagging on the screen. It seems that removing the line works fine too, but I suppose it's there for a reason. The piece of code is this:

`#if defined(__GNUC__)`
`#pragma GCC diagnostic push`
`/* Disable bogus compiler warning -Wdate-time */`
`#pragma GCC diagnostic ignored "-Wall"`
`#pragma GCC diagnostic ignored "-Werror"    <-- this is the line`
`#endif`

I just want to share this.

Thanks!
Marco

**Comment by bel2125** [comment]
> It seems that removing the line works fine too, but I suppose it's there for a reason. 

CivetWeb used to compile without warning on a very high warning level (-Wextra) in some older GCC version. A GCC update introduced some new, spurious warnings. Unfortunately the `#pragma GCC diagnostic ignored` to disable a warning for a certain line and re-enable it again afterwards does not work consistently for all warnings and all versions of GCC.

For the same line of code, some versions do not rise a warning, some versions allow to disable it using a pragma and some versions do not allow to disable it for a single line/code block. Sometimes the pragmas used to disable a warning in one version give a new warning (like "unknown pragma") in another version. This behaviour differs for different warnings. Bug reports for GCC exist, but they remain unsolved for many years.

So, since GCC unfortunately is everything but consistent in this respect, I finally had to lower my expectations - "warning free for every GCC version" is simply not possible in the higher warning levels.
clang seems to be more consistent than GCC

I probably added this line while I was still trying to get the code compile with -Wextra for several GCC versions, and I did not remove again after I found this is impossible.

You can safely remove all `#pragma diagnostic` lines - I can have a look what lines could be removed in the master later.

**Comment by marcoafo** [comment]
Indeed I noticed that this warning didn't occur in previous version of GCC
(I believe it was 5.x). I can live with the warning since it doesn't affect
anything at all.

Thanks for the clarification.

Em 05/12/2017 8:51 PM, "bel2125" <notifications@github.com> escreveu:

**Comment by bel2125** [comment]
This code was removed a month ago, but I forgot to give feedback here.
Is the current version working for you now?

**Comment by marcoafo** [comment]
It's all good now. Thanks!
