### ISSUE TITLE
Compiler warnings from mod_lua.inl

### ISSUE THREAD

**Issue by extergnoto** [civetweb/civetweb#564]
I am using version 1.10 at the moment.

The following compiler warnings occur:
"C:\civetweb\src\mod_lua.inl", line 791: warning #552-D: variable "ctx" was set but never used
"C:\civetweb\src\mod_lua.inl", line 869: warning #552-D: variable "ctx" was set but never used
"C:\civetweb\src\mod_lua.inl", line 949: warning #552-D: variable "ctx" was set but never used
"C:\civetweb\src\mod_lua.inl", line 989: warning #552-D: variable "ctx" was set but never used
"C:\civetweb\src\mod_lua.inl", line 1028: warning #552-D: variable "ctx" was set but never used
"C:\civetweb\src\mod_lua.inl", line 1065: warning #552-D: variable "ctx" was set but never used

**Comment by bel2125** [comment]
The V1.10 release is not free from warnings, due to a change Travis did the same time V1.10 had to be released - some history can be found here: #512
A different compiler version in the new build environment caused several new warnings, some of them cannot be deactivated for some lines using a pragma. It is not possible to build without warnings for all compilers and all their versions.

Anyway, the current 1.11 head version builds without warnings **for selected versions of major compilers**

**Comment by bel2125** [comment]
The reported warnings have been solved long ago --> closing this issue.

Note that some other gcc warnings remain due to a known compiler bug (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53431).
