### ISSUE TITLE
Feature request: Means to replace mg_cry() and log_access() totally by an own implemention

### ISSUE THREAD

**Issue by extergnoto** [civetweb/civetweb#582]
Is it possible to add a define or some other means to replace mg_cry() and log_access() totally by an own implemention.

The reason is, that I have a very limited embedded system. The big string buffers created on the stack are not suitable and I don´t use file based logging, but a system logging facility.

Ideally the user defined functions should be implemented in an extra file (.c or .inl).

At them moment, I have replaced the functions, but this introduces some merge effort with each new version of civetweb.

**Comment by bel2125** [comment]
`mg_cry` and `log_access` are two different kind of functions.
First of all, the interface is different. 

For `mg_cry`, you need to overwrite `mg_cry_internal_impl`
https://github.com/civetweb/civetweb/blob/44174c83718f23aedc07e206d8aa71fef4314bc2/src/civetweb.c#L3367
```C
static void
mg_cry_internal_impl(const struct mg_connection *conn,
                     const char *func,
                     unsigned line,
                     const char *fmt,
                     va_list ap)
```
with the error message passed in parameters, while for `log_access`
https://github.com/civetweb/civetweb/blob/44174c83718f23aedc07e206d8aa71fef4314bc2/src/civetweb.c#L13809
```C
static void
log_access(const struct mg_connection *conn)
```
all data must be extracted from the private `struct mg_connection` not defined outside civetweb.c.
For your own `mg_cry_internal_impl`, you probably don`t need anything from the `struct mg_connection` parameter, since all data is in separate parameters.
`log_access` does already have a callback interface with the message as prepared string, so you can work with the official interface (if this string is sufficient - if not: what's missing?).

We could discuss about moving `mg_cry` and/or `log_access` to one (or two) *.inl files. Some of the reasons why I did not split civetweb.c in multiple inl files are here: https://github.com/civetweb/civetweb/issues/545#issuecomment-341572018

For `log_access` there is a 4 kB string buffer, for `mg_cry_internal_impl` it's `MG_BUF_LEN` bytes (8 kB as default). Is it only a matter of stack size, or is there more about it?

**Comment by extergnoto** [comment]
I have implemented two little helpers that extract the request info and status from the connection. This is the information I need from my logging functions.

```C
const struct mg_request_info*
cw_get_request_info(const struct mg_connection *conn)
{
   const struct mg_request_info* const ri = conn ? &conn->request_info : NULL;
   return ri;
}

typedef struct cw_conn_status_data_s
{
    int        status_code;    ///< HTTP reply status code, e.g. 200
    int64_t    num_bytes_sent; ///< Total bytes sent to client
} cw_conn_status_data;

cw_conn_status_data cw_conn_status_data_get(const struct mg_connection* conn)
{
   cw_conn_status_data data = { 0 };
   if (conn) {
      data.status_code    = conn->status_code;
      data.num_bytes_sent = conn->num_bytes_sent;
   }

   return data;
}
```

I have also introduced a conditional CW_DISABLE_FILE_BASED_LOGS to eleminate the file writing code.

**mg_cry**

Here the buffer size on the stack is my only concern. I am using buffer size 200 at the moment, but something like 1000 is also OK.
The CW_FILE_BASED_LOGS optimization is just nice to have.
As it looks to me, mg_cry_internal_impl is basically the same.

```C
void
mg_cry(const struct mg_connection *conn, const char *fmt, ...)
{
       // smaller, stack friendly buffer
       enum { CW_BUF_LEN = 200 };
       char buf[CW_BUF_LEN];

	va_list ap;

	va_start(ap, fmt);
	IGNORE_UNUSED_RESULT(vsnprintf_impl(buf, sizeof(buf), fmt, ap));
	va_end(ap);
	buf[sizeof(buf) - 1] = 0;

	DEBUG_TRACE("mg_cry: %s", buf);

	if (!conn) {
		puts(buf);
		return;
	}

	/* Do not lock when getting the callback value, here and below.
	 * I suppose this is fine, since function cannot disappear in the
	 * same way string option can. */
	if ((conn->ctx->callbacks.log_message == NULL)
	    || (conn->ctx->callbacks.log_message(conn, buf) == 0)) {
#if (CW_DISABLE_FILE_BASED_LOGS)
#else // CW_DISABLE_FILE_BASED_LOGS
                char src_addr[IP_ADDR_STR_LEN];
        	struct mg_file fi;
	        time_t timestamp;

		if (conn->ctx->config[ERROR_LOG_FILE] != NULL) {
			if (mg_fopen(conn,
			             conn->ctx->config[ERROR_LOG_FILE],
			             MG_FOPEN_MODE_APPEND,
			             &fi) == 0) {
				fi.access.fp = NULL;
			}
		} else {
			fi.access.fp = NULL;
		}

		if (fi.access.fp != NULL) {
			flockfile(fi.access.fp);
			timestamp = time(NULL);

			sockaddr_to_string(src_addr, sizeof(src_addr), &conn->client.rsa);
			fprintf(fi.access.fp,
			        "[%010lu] [error] [client %s] ",
			        (unsigned long)timestamp,
			        src_addr);

			if (conn->request_info.request_method != NULL) {
				fprintf(fi.access.fp,
				        "%s %s: ",
				        conn->request_info.request_method,
				        conn->request_info.request_uri
				            ? conn->request_info.request_uri
				            : "");
			}

			fprintf(fi.access.fp, "%s", buf);
			fputc('\n', fi.access.fp);
			fflush(fi.access.fp);
			funlockfile(fi.access.fp);
			(void)mg_fclose(&fi.access); /* Ignore errors. We can't call
			                              * mg_cry here anyway ;-) */
		}
#endif // CW_DISABLE_FILE_BASED_LOGS
	}
}
```

**log_access**

See next comment.

**Comment by extergnoto** [comment]
**log_access**

I have modified the function:
- First call the handler. If the handler returns non-zero: finished.
- Else: Do formatting and file writing stuff. 
- I had to take out the second call to the handler.

Calling the handler function with the big formatted buffer is unhandy for me for the following reasons:
- The big buffer on the stack might cause a stack overflow
- The internal logging implementation being used in the handler cannot cope with one big buffer. It can do much better with the data from the request info.

I'm not sure how this could be resolved in a clean fashion. A second handler function is probably not desirable. Maybe one could evaluate (valid buffer pointer vs. NULL) in the handler to distinguish between a first and second call.

```C
static void
log_access(const struct mg_connection *conn)
{
#ifdef MY_MODIFICATION
   if (!conn || !conn->ctx) {
      return;
   }

   if (conn->ctx->callbacks.log_access && conn->ctx->callbacks.log_access(conn, NULL)) {
      // have callback and it returned non-zero -> finished
      return;
   }

   const char * const accessLogFileName = conn->ctx->config[ACCESS_LOG_FILE];
   if (!accessLogFileName) {
      return;
   }

#endif // MY_MODIFICATION

#if (CW_DISABLE_FILE_BASED_LOGS)
   (void) header_val;
#else // CW_DISABLE_FILE_BASED_LOGS

    // big buffer
   char buf[4096];

   <Do formatting and file writing stuff>

#ifdef MY_MODIFICATION
   // already done
#else
   if (conn->ctx->callbacks.log_access) {
      conn->ctx->callbacks.log_access(conn, buf);
   }
#endif

   <Some more file writing stuff>

#endif // CW_DISABLE_FILE_BASED_LOGS
}
```

**Comment by bel2125** [comment]
> mg_cry
>
> Here the buffer size on the stack is my only concern. I am using buffer size 200 at the moment, but something like 1000 is also OK.

It would be an easy fix to have a separate configuration define for the buffer size for logging - like 10 minutes to implement, basically no effort to maintain.

**Comment by bel2125** [comment]
A significantly more radical approach already on some wish-list was to modify civetweb so it runs on a platform completely without a file system. This is basically setting the "NO_FILES" define and removing/replacing authentication files, error log files (mg\_cry) and access log files (log\_access).

Does this match your requirements?

**Comment by bel2125** [comment]
Otherwise, mg\_cry and log\_access must be handled differently.

For mg\_cry, the source information is basically a text string (and some source location for developers). If everything runs fine at server side, mg\_cry should never be called, even if the client gets legitimate error responses.

For log\_access there is no string as source information, but the string is created from some internal fields in a data structure not available in the public interface. I don't want to make this structure public either - we have to be free to change this from version to version.
One way to pass information with changing fields would be to pass JSON strings, like for `mg_get_system_info`, `mg_get_context_info` and `mg_get_connection_info`. The latter might be a way to get data from `conn` in `log\_access`.

**Comment by bel2125** [comment]
Another approach would be to do defines like this around relevant functions (like `some_function'):

```C
#if defined(SOME_FUNCTION_EXTERNAL)
#include "some_function.ext.inl"
#else
rettype some_function(...) {
   ...
}
#endif
```

**Comment by bel2125** [comment]
... I just dropped a couple of ideas here, for further discussion ...
Just tell we what could be suitable for you, and what would not help you at all.

**Comment by extergnoto** [comment]
The SOME_FUNCTION_EXTERNAL-approach is exactly what I need.
It would be good to add a prototype before including the external implementation to allow for check of the function signature.

Thanks.

**Comment by bel2125** [comment]
I added configuration options for `mg_cry_internal_impl`
https://github.com/civetweb/civetweb/blob/b7b35d3c8fd8e4461face2d22420801dd6ad6f94/src/civetweb.c#L3415-L3422

and `log_access`
https://github.com/civetweb/civetweb/blob/b7b35d3c8fd8e4461face2d22420801dd6ad6f94/src/civetweb.c#L14045-L14048

as well as a documentation chapter in [Embedding.md](https://github.com/civetweb/civetweb/blob/master/docs/Embedding.md#externally-provided-functions).

Please check if this fits your needs. Interface and function names and defines may change in the future, so you need to check when updating - but it should still reduce the merge effort significantly.

**Comment by extergnoto** [comment]
That´s what I need.
Thanks.
