### ISSUE TITLE
Error on Android when start server

### ISSUE THREAD

**Issue by prsolucoes** [civetweb/civetweb#585]
Hi,

Im trying use my library inside android and getting this error:

```
Caused by: java.lang.RuntimeException: null context when constructing CivetServer. Possible problem binding to port.
```

It is working on mac/linux, but not on Android.

The code is here:
https://github.com/prsolucoes/epubreader/blob/master/dependency-server/build/source/cpp/EpubReaderServerImpl.cpp

And the library:
https://github.com/prsolucoes/epubreader/tree/master/build/android

Can anyone help me?

Thanks.

**Comment by bel2125** [comment]
Most of my projects don't allow to use C++11, so I probably cannot help much in this respect.

Probably you should just set the `error_log_file` parameter (like you did with `document_root` and `listening_ports`) to some file name, try again and check the content of this file.

**Comment by prsolucoes** [comment]
Hi,

On log i got:

```
01-26 12:08:44.364 12271-12271/com.epubreader.epubreader I/EPUBREADER: [1516975688] [error] [client ] 9090: invalid port spec (entry 1). Expecting list of: [IP_ADDRESS:]PORT[s|r]
```

**Comment by bel2125** [comment]
`9090�` looks like there is an invalid character in your `listening_port` specification.
You get an error from `mg_start`, this underlying C API function returns NULL if it cannot create a server instance (e.g, because you specified an invalid configuration). 

From my point of view, using the basic C API function is much clearer than using the various layers of C++ and Java on top of it, but that's probably a matter of taste. C++ passes this NULL return as a more or less generic exception: https://github.com/civetweb/civetweb/blob/44174c83718f23aedc07e206d8aa71fef4314bc2/src/CivetServer.cpp#L287-L290

**Comment by prsolucoes** [comment]
Hi,

Yes. It is working. I forgot write here because im testing. I think that the char dont have the \0 when i pass to the param list. I change all to string to let users pass "ip:80" and everything works. So, my conclusion is the \0 that dont have on my old code.

See:
https://github.com/prsolucoes/epubreader/blob/master/dependency-server/build/source/cpp/EpubReaderServerImpl.cpp

Thanks for your help man.
