### ISSUE TITLE
Sailor Lua Web Framework

### ISSUE THREAD

**Issue by Acciaiodigitale** [civetweb/civetweb#594]
Hi! I'm Massimiliano Bertinetti and I'm the new Lead developer of Sailor (https://github.com/sailorproject/sailor)

I'm trying to revive this framework and I'm searching a server that let me use Sailor with Lua 5.3 in development with automatic reload and that can do well in production? I find your project and I want to ask if you can guide me to configure Sailor to be used with Civetweb.

**Comment by bel2125** [comment]
Sure.
But I don't know Sailor, and the project web site http://sailorproject.org/ seems to be down right now, so I currently have no idea what needs to be done.

**Comment by CodelessFuture** [comment]
http://sailorproject.alwaysdata.net

You can see how it works in source repos. For example it use Xavante as in

https://github.com/sailorproject/sailor/blob/master/src/sailor/blank-app/start-server.lua

Il 26 feb 2018 11:47 PM, "bel2125" <notifications@github.com> ha scritto:

**Comment by bel2125** [comment]
Since I never used Sailor, I don't know the architecture. I also did not read the entire documentation, but some sections to get an overview. From what I saw in [documentation](http://sailorproject.alwaysdata.net/docs/create) it's used to create files/structures for a web server like [the sailor website](https://github.com/sailorproject/sailor_website). Right?

Now, how do you deliver this content? By CGI? What interpreter?
CivetWeb can execute Lua code natively (in server), without using CGI.
Are you looking for a CivetWeb configuration for the existing directory structure?

Regarding Lua 5.3: Yes, CivetWeb supports Lua 5.3 in server, I still use 5.2 as default since the main change from 5.2 to 5.3, introducing integers, is a disadvantage for web applications from my point of view (can explain why on request). But 5.3 can be used, if you prefer.

**Comment by CodelessFuture** [comment]
Actually Sailor use Cgilua. I enter Sailor only a month ago and I don't
know really well the internals. I don't know very well web server internals
and CGI.
What can I say is that Sailor use a front controller for routing request
and CGI for *.lua and *.lp files at today. But for the future we can do
what is best.

I want find a solution for Sailor to be fast and reliable. I find someone
to join forces and do this. If you want we can do a Skype call and discuss
if we can work together on this. I'm very happy if you can teach me how
achieve this.

Il 27 feb 2018 8:39 PM, "bel2125" <notifications@github.com> ha scritto:

Since I never used Sailor, I don't know the architecture. I also did not
read the entire documentation, but some sections to get an overview. From
what I saw in documentation
<http://sailorproject.alwaysdata.net/docs/create> it's used to create
files/structures for a web server like the sailor website
<https://github.com/sailorproject/sailor_website>. Right?

Now, how do you deliver this content? By CGI? What interpreter?
CivetWeb can execute Lua code natively (in server), without using CGI.
Are you looking for a CivetWeb configuration for the existing directory
structure?

Regarding Lua 5.3: Yes, CivetWeb supports Lua 5.3 in server, I still use
5.2 as default since the main change from 5.2 to 5.3, introducing integers,
is a disadvantage for web applications from my point of view (can explain
why on request). But 5.3 can be used, if you prefer.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/civetweb/civetweb/issues/594#issuecomment-368999950>,
or mute the thread

**Comment by CodelessFuture** [comment]
One must have is caching in production and reload contents in development environment (I now have problems with this with Xavante)

**Comment by bel2125** [comment]
CivetWeb is definitely stable and already used in production. One could use both, CGI and "Lua in-server".

For CGI, every request from a web client (browser) to a web server means, the spawns a new "CGI" process. Then the web server forwards data sent from the web client (browser) to stdin of the CGI process. In the other direction, the web server forwards data written to stdout by the CGI process to the web client. 
(I think these three lines description are simpler than [Wiki](https://en.wikipedia.org/wiki/Common_Gateway_Interface)).

A CGI process can be basically any program (console application) in any programming language. It can be a compiled C/C++ program, but it can also be a script interpreter running basically any scripting language.

CGI comes with the overhead of creating a new process for every request. The most efficient alternative (in terms of speed and memory consumption) is an "in server module": Instead of creating a CGI process to execute a script, the web server can interpret the script itself.

For "in server module" the web server must have a built in interpreter for the script language.

==> CivetWeb has a built in interpreter for Lua 5.1 or 5.2 or 5.3 or LuaJit (you need to select) and a script interpreter for server side javascript (duktape). So if you can generate Lua5.3 code, the fastest option would be to build CivetWeb with Lua 5.3 and use in in-server.

**Comment by CodelessFuture** [comment]
Can you help me test a Civetweb configuration to test with Sailor? What I
need to do exactly? If you can dedicate 15 minutes tomorrow on Skype for
guiding me I really appreciate. My email is massimiliano@codelessfuture.com

Il 27 feb 2018 9:46 PM, "bel2125" <notifications@github.com> ha scritto:

**Comment by bel2125** [comment]
Could you provide some details on your test systems, in particular operating system (Windows or Linux, what distribution / version) and maybe a link to a test app ([this one?](https://github.com/sailorproject/sailor/tree/master/test/dev-app)).
