### ISSUE TITLE
Response headers?

### ISSUE THREAD

**Issue by irobayna** [civetweb/civetweb#598]
I'm new to CivetWeb and I am trying to figure out how to send different headers back to the client.  

I'm sending an HTTP error back which appears to work via:

```
mg_send_http_error(pConn, 422, "%s\r\n", ErrBuf);
```
and then send headers back via:
```
	mg_printf(pConn, "Access-Control-Allow-Origin: *\r\n");
	mg_printf(pConn, "Access-Control-Allow-Methods: POST\r\n");
	mg_printf(pConn, "Access-Control-Allow-Headers: Content-Type\r\n");
	mg_printf(pConn, "Access-Control-Allow-Headers: X-Requested-With\r\n");
```
which sends them on the body not the header.

What am I missing?

Here is the output via curl:
```
< HTTP/1.1 422 Unproccessable entity
< Cache-Control: no-cache, no-store, must-revalidate, private, max-age=0
< Pragma: no-cache
< Expires: 0
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 08 Mar 2018 13:44:17 GMT
< Connection: close
```
right output which should be:
```
< HTTP/1.1 422 Unprocessable Entity
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST
< Access-Control-Allow-Headers: Content-Type
< Access-Control-Allow-Headers: X-Requested-With
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
<
```

Thank you

**Comment by bel2125** [comment]
You could either send the entire header completely using `mg_printf` / `mg_write`, then an empty line (`mg_printf(pConn, "\r\n");`), then the body, or you can specify additional headers by setting the configuration. But headers in the configuration will be returned for more or less every response.
Since you know the headers anyway, you should probably just print them directly, like in this example:
https://github.com/civetweb/civetweb/blob/1a2c55349f927639d04efb5c6770d2156798b204/examples/embedded_c/embedded_c.c#L484-L489

**Comment by irobayna** [comment]
@bel2125 Thank you!

**Comment by ryanbinns** [comment]
Although this workaround works, it's a bit clumsy. It means that ALL the required headers have to be generated, rather than just adding an extra header to the standard ones that civetweb sends. It would be nice to be able to do something like this:
```
mg_set_additional_header(conn, "Allow: GET, PUT, DELETE\r\n");
mg.send_http_error(conn, 405, "Method Not Allowed");
```
I would envisage that the additional header would only have effect once. Multiple headers could be specified in the string as well if required. Does this sound like a reasonable suggestion? I'd be happy to have a go at implementing it if you like.

**Comment by bel2125** [comment]
Do you mean the Lua interface (mg.send_http_error with dot) or the C interface (mg_send_http_error with underscore)?

Some functions like mg_send_http_error do send headers, others like mg_write/mg_printf just send what they get. In other cases, such as serving static files from the document root directory, headers are sent implicitly without any API call. The problem with an additional mg_set_additional_header function, it is a bit unclear on what scope is it going to word: For the next mg_something call? Until the next mg_send_http_error call? For all calls in this connection (depending on keep-alive)? 
Depending on how this is supposed to work, it might be easier to understand to add a parameter for additional headers to the relevant function(s).

**Comment by ryanbinns** [comment]
Sorry, typo. I meant the C interface `mg_send_http_error`. I was envisaging that the additional header would be sent once only, the next time that civetweb internally generates the header via the `mg_send_http_error` or `mg_send_http_ok` functions. It would not be used for responses generated by calling `mg_write` or `mg_printf`, as the calling code is deciding exactly what headers to send anyway. It also wouldn't be used for static files or for the API functions that send files, as `mg_send_mime_file2` already has an additional header parameter.

Perhaps simply adding `mg_send_http_error2` and `mg_send_http_ok2` with an additional header parameter would suffice, similary to `mg_send_mime_file`/`mg_send_mime_file2`.

**Comment by bel2125** [comment]
> Perhaps simply adding mg_send_http_error2 and mg_send_http_ok2 with an additional header parameter would suffice, similary to mg_send_mime_file/mg_send_mime_file2.

Yes, I think so too. The "next time something is called" is usually far less intuitive to use, in particular in a multi-threaded server when reusing threads to handle multiple connections, handling multiple requests using one connection.
