### ISSUE TITLE
Lua, open explorer window

### ISSUE THREAD

**Issue by gaby64** [civetweb/civetweb#677]
is it possible, im trying with:

`io.popen("explorer .\External\MillerSubConOrientation")`

gives me page isnt working ERR_INVALID_HTTP_RESPONSE

**Comment by bel2125** [comment]
I'm not exactly sure what you want to reach by opening the Windows explorer from a Lua server page.

How io.popen works:
---

`f = io.popen("program.exe argument")` means, execute "program.exe", pass "argument" as command line argument and get `f` as a file handle to the console output (stdout) of "program.exe". You need a loop like 
```
out = f.read()
while (out and (#out>0)) do
  mg.write(out)
  out = f.read()
end
```
to pass the output of "program.exe" to the client. This only works for programs generating output to stdout - program.exe needs to write a valid HTTP response to stdout ... or you have to send the HTTP header on your own from Lua before.



explorer
---

As to my knowledge, explorer does not send anything to stdout.
If you want the output of MillerSubConOrientation, you could just use 
io.popen(".\External\MillerSubConOrientation.exe")
... if MillerSubConOrientation is a console program.


Window?
---

Or is MillersSubConOrientation a directory, and you want to open a Window on the server?
This will not generate any response at all.

If you want to open a window on the server side, for whatever reason, you could use
os.execute("start explorer .\External\MillerSubConOrientation.exe")
But the, every request by a client will open an explorer Window on the server.


I think I can't help without understanding the use case.

**Comment by bel2125** [comment]
> I have tried os.execute, nothing works, I can only get a valid response through with mg.write

If you want to do it like this (server = client), then you need to send a HTTP response (like this: https://github.com/civetweb/civetweb/blob/master/test/page5.lua) to generate a valid response AND call os.execute("start explorer ...") to open the explorer window.

If you ever want to split server and client, you could use mg.send_file or mg.send_file_body (see https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#lua-scripts-and-lua-server-pages), so the browser will download the file and you can open it locally in whatever program.

**Comment by gaby64** [comment]
I cant get it to execute anything, im not sure if its a permission issue in windows 10, I have the service installed and allow interaction with the desktop

**Comment by bel2125** [comment]
I tested with Windows 10 Home, Build 1803 - but not with CivetWeb as a service.
I guess the problem is a Windows service cannot open a desktop window - at least not with the regular "start a program" call.

I tried a redirect to a local file (file:///C:/path/to/folder/) to open the local folder in the browser instead of explorer, but browsers actively block this as "unsafe redirect". 

I guess the only quick solution is to not run the server as a service.

More information and lengthy solutions:
https://stackoverflow.com/questions/5307968/how-can-i-run-an-exe-program-from-a-windows-service-using-c
https://www.codeproject.com/Tips/1071738/Launching-UI-Application-from-Windows-Service

**Comment by gaby64** [comment]
could you add a launch on startup option?

**Comment by bel2125** [comment]
You can easily do this on your own.
I recommend, you write a start_learning_service.bat or start_learning_service.cmd file (start_learning_service is some name to identify your program):

```bat
cd c:\somewhere\learning_service\workingpath
c:\somewhere\learning_service\bin\civetweb.exe c:\somewhere\learning_service\config\civetweb.conf
```

Just move this into the autostart folder. In Windows 10, this folder is somewhat hidden - to open it, type [Windows]+R to execute a program and type shell:startup - it will open a folder like
C:\Users\UserName\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
If you put the batch file there, it will be executed when the user (UserName) logs in.

In principle, you can also put a shortcut to civetweb.exe there - the batch file will allow you to pass additional options, ... even start multiple programs if you use "start". If you really just want to start civetweb,exe, the shortcut will be just fine.

**Comment by jmucchiello** [comment]
FYI, windows services cannot launch programs that interact with the desktop. (As of Vista).

**Comment by bel2125** [comment]
> FYI, windows services cannot launch programs that interact with the desktop. (As of Vista).

For this very special use case, you must not run it as a service, but as a regular program, started by a regular user - the user that should see the explorer window ... but  think this is intended in this particular use case anyway. 

You can still add it to autostart, as explained above.

@gaby64: Is there anything else we can do for you, or can we close this issue?

**Comment by gaby64** [comment]
I would prefer an option in civetweb config that would automatically setup autostart

I run civet web on many computers and being able to just set the config file and copy them to all the computers and just start it would be helpful

**Comment by bel2125** [comment]
Current civetweb-version does not have an "add to autostart" feature built in, and it's currently not on the TODO list. There is also no "setup" that would install civetweb and add it to autostart - it works as a portable executable without the need for a setup. What I can offer today is a "reg" file to add it to autostart. I cannot attach a "*.reg" file here (not an allowed file type), but it's a text file containing only a few lines:

```ini
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run]
"MyXYZServer"="\"C:\\MyPATH\\MyXYZServer\\CivetWeb64.exe\" -title MyXYZServer"

```

Call it "MyXYZServer.reg" ... or probably replace all MyXYZServer by LearningServer or whatever name suites best. The "MyXYZServer" to the left should be some unique name unlikely to be used by other products. The MyXYZServer to the right (after -title) is what you will see on mouse-over the tray icon. You can optionally also set the -icon option and the -website option (I will probably add some more options like -noservice). With these options, civetweb.exe appears like "your" LearningService in the system tray, and you can customize the icon (instead of the civet icon) and the website.

Make sure C:\MyPATH\Leardingservice\CivetWeb64.exe (whatever is in the reg file) is the correct path.

To "install" the autostart command, double-click the "LeardingService.reg" file - confirm you want to add it to the registry (may require admin rights - don't know for sure).

Just tested it on my Win10 ... works fine.

It's still not a setup that will create a directory, copy all required files there, write the path to this directory automatically to the registry ... and allow some "uninstall". But, in contrast to full windows installers, this *.reg file can be written and tested in ~5 minutes.

**Comment by gaby64** [comment]
I gave up on launching PowerPoint on the host machine though lua, im running as a service and using google slideshow

MyPATH varies per machine because the training folder is on the desktop

closing the issue, I was just hoping the simple feature would be added for others.
