### ISSUE TITLE
How to use cjson under lp file?

### ISSUE THREAD

**Issue by hcaihao** [civetweb/civetweb#715]
Can you give me an example? Thank you!

**Comment by bel2125** [comment]
Choose a JSON library for Lua ([here](http://lua-users.org/wiki/JsonModules) is a list, [here](http://regex.info/blog/lua/json), [here](https://github.com/rxi/json.lua/blob/master/json.lua), [here](https://gist.github.com/tylerneylon/59f4bcf316be525b30ab) are even more - [lua-cjson](https://www.kyne.com.au/~mark/software/lua-cjson.php) is the most often downloaded library on [LuaRocks](https://luarocks.org/modules/openresty/lua-cjson)).
In a Lua tag, "require" the library or your choice and use it as in a Lua script.

If the JSON library loads a C library (DLL or SO), you should load this library as well in the "lua_background_script", for performance reasons.


```
<html><body>
<% cjson= require ''cjson" %>
<% ... use cjson here ... %>
</body></html>
```

**Comment by bel2125** [comment]
Civetweb builds with static Lua unless you set the "WITH_LUA_SHARED" flag (for Linux: `make WITH_LUA_SHARED=1`), then it uses the system library.
Many Linux distributions already come with their version of Lua, you use the "shared object" already installed (liblua.so.*).

For Windows, there is no equivalent of a Lua.dll in a "Windows distribution" - and with various versions of "redistributables for C/C++" I think it's not feasible to create something equivalent.
So, for Windows you will need to modify the build directly to use the Lua.dll you want to use.

There is yet another idea: You can add a C module for JSON directly into the civetweb build (e.g.: https://github.com/Nicholas3388/cJSON4Lua ... but I cannot do this for the official build, since it does not have a clear license statement). You can also do this with C code of Lua library "cjson" which is a different one to the C code of the C library "cjson".

**Comment by bel2125** [comment]
Before I go into more details: What operating system are you using? Are you building any C code on your own or are you using the pre-compiled versions? What version of "cjson" (have you got a download link?)?

**Comment by hcaihao** [comment]
Platform: Windows 10 + VS2015

I use pre-compiled versions civetweb, Could civetweb support dynamic link to lua? So we can add many plugins to civetweb(Such as: csjon.dll, lcurl.dll, sqlite3.dll ...), Then the sqlite3 lib could be removed from civetweb.

**Comment by hcaihao** [comment]
https://github.com/mpx/lua-cjson

This is what I used cjson, I build it with vs2015. It works well in other project.

If you build it, You should add cjson.def manually.

```
LIBRARY	"cjson"
EXPORTS
luaopen_cjson
```

**Comment by bel2125** [comment]
> Could civetweb support dynamic link to lua? 
> So we can add many plugins to civetweb (Such as: csjon.dll, lcurl.dll, sqlite3.dll ...), 

It works exactly like this for Linux in the "lua shared" configuration. Linux distributions have one official "liblua.so" used by all Lua libraries and one system C library (and if there is Lua 5.1 and 5.2 in parallel, Linux takes care). Windows is different here: There is no *official* "lua.dll" used by all Lua libraries, and there are ~10 different C libraries (redistributables), and you must not intermix them. For Linux, distributions also bring a full build environment (C compiler, ...), while this is not the case for Windows where there are multiple different compilers and in different versions, usually with additional licenses, registrations, and sometimes license costs.

Using Luarocks for windows is one approach to create a similar infrastructure for using Lua on Windows and Linux - but that's far from a ***no installation, no dependency, "just start it" portable executable*** like civetweb.exe is now.

**Comment by hcaihao** [comment]
Yes, you are right. I'll replace the lua library with my shared one, and rebuild it by myself. Thank you.

**Comment by hcaihao** [comment]
I modified 4 places in civetweb.sln:
1. Remove macro: USE_LUA_SQLITE3 & USE_LUA_FILE_SYSTEM in project civetweb_lua.
2. Remove file: mod_lua.inl in project  civetweb_lua
3. Include my shared lua in project civetweb_lua.
4. Remove project lua_lib.

Is it correct for my porpose?

**Comment by bel2125** [comment]
1) You can remove all definitions for extra libraries lodad in `civetweb_open_lua_libs`
https://github.com/civetweb/civetweb/blob/f07acaf7391d4805907046f5aa4a48c7acb9169a/src/mod_lua.inl#L2079

USE_LUA_SQLITE3, USE_LUA_LUAXML, USE_LUA_FILE_SYSTEM

2) I think you don't want to remove mod_lua.inl, since this will be the code required to use Lua as an in-server-module. If you remove it, you end up using Lua as CGI, which is a vast loss in performance.
Just keep this file.

3+4) In the civetweb_lua you need an import lib for your Lua DLL. Then you can remove the Lua project included in the solution.
