### ISSUE TITLE
How to set user connection data using init_connection callback

### ISSUE THREAD

**Issue by lewimuchiri** [civetweb/civetweb#744]
I am currently using `mg_set_user_connection_data(..) ` to add custom data for each connection. In the function's documentation, it says that the function is deprecated and that I should use the init_connection callback. 
How do I do this? I could not find any example showing how to use init_connection callback.

**Comment by bel2125** [comment]
You are right, the `init_connection` callback is somehow missing all documentation - except the comments in the header:

https://github.com/civetweb/civetweb/blob/757c72d63a5b92ff5c00011789b42bba48c2a6df/include/civetweb.h#L385-L398

It was initially created because `mg_set_user_connection_data` requires a const-cast, for the connection - see https://github.com/civetweb/civetweb/issues/452
To use it, set the `init_connection` member of the `struct mg_callbacks` parameter passed to `mg_start`. As a callback, something like the following C / C++ mixture will work:

```C++
int my_init_connection)(const struct mg_connection *conn, void **conn_data) {
   CMyConnectionData *my_connection_data = new CMyConnectionData(conn);
   *conn_data = my_connection_data;
   return 0;
}

void my_connection_close(const struct mg_connection *) {
   CMyConnectionData *my_connection_data = (CMyConnectionData *)mg_get_user_connection_data(conn);
   delete my_connection_data;
   return 0;
}
```

**Comment by lewimuchiri** [comment]
Thank you for your response.
