### ISSUE TITLE
support for mbedtls on roadmap?

### ISSUE THREAD

**Issue by tzjb** [civetweb/civetweb#761]
Hi, will civetwe support mbedtls as an alternative to openssl in the future? Thanks!

**Comment by bel2125** [comment]
Is mbedTLS a rebrand of WolfSSL / yassl?
Does it have an openSSL compatibility layer?

Some earlier version of CivetWeb used to support yassl and there is some documentation here: https://github.com/civetweb/civetweb/blob/master/docs/yaSSL.md
But it's not tested for quite a while (see notes on top of the documentation).
Getting it to work again is on the (unsorted) "long list", but not yet on a "short list" of tasks that are going to be worked on soon.

You need an openSSL alternative?

**Comment by tomzhu9988** [comment]
HI @bel2125 , thanks for your reply. mbedTLS is not a rebrand of WolfSSL/yassl. It is part of ARMBed and is finding its way to more applications, e.g., AWS IoT embedded C SDK uses mbedTLS.
I looked into the source code of mbedTLS, and it seems mbedTLS and openssl have similar workflow. I 
BTW, when civetweb uses openssl for the server side, is BIO blocking or non-blocking? Is this configurable?

**Comment by bel2125** [comment]
BIOS is non-blocking since version 1.9 - see [release notes](https://github.com/civetweb/civetweb/blob/master/RELEASE_NOTES.md#release-notes-v19).

It's not configurable, since it requires several code changes / different algorithms to deal with non-blocking sockets. It would basically double testing effort without providing additional value.

**Comment by bel2125** [comment]
For your information: Demo implementations using mbedtls are available: #832 #839
I still have to check how to merge it to the recent version.
