### ISSUE TITLE
SOMAXCONN cannot be configured

### ISSUE THREAD

**Issue by chardan** [civetweb/civetweb#775]
The SOMAXCONN parameter is hardcoded and cannot be configured by the user. Some users run out of connections and have no way to tune the parameter.

**Comment by bel2125** [comment]
Your PR is merged. Thanks for your contribution.

Yet, I'm not sure if this helps, since
a) it depends on the operating system, what the maximum value really is
b) if you run out of connections, you probably run out of worker threads first, or your worker threads perform to costly operations (cpu or io intensive scripts), or it might even be a disc speed problem.

Still, you can give it a try if increasing this value changes anything for the better.

Maybe let me know in what cases this really helps.

**Comment by chardan** [comment]
@bel2125 Thank you very much! :-) I'll try to address your concerns:
a) Since the value was previously hardcoded to a limit far below to current kernel limit, which has
changed between versions, it seems useful to be able to configure it.
b) In the case for which this patch was written, it allowed for 3x the load before the worker threads were exhausted (before making SO_MAX_CONN tuneable, load balancer checks were getting dropped under high load), so for some situations being able to tun the parameter makes a big difference.

**Comment by bel2125** [comment]
Merge request merged. Closing this issue.
