### ISSUE TITLE
Please release 1.12

### ISSUE THREAD

**Issue by gjasny** [civetweb/civetweb#795]
Hello,

since the release of 1.11 many changes and fixes have been accumulated. Some of them are crucial for compilation with modern toolchains.

Would you please consider releasing a 1.12 version?

Thanks,
Gregor

**Comment by PhilLab** [comment]
@bel2125 Would you consider it safe to use the current master or are you aware of regressions / defects?

Thank you for your maintenance and continuous improvement of civetweb 👍

**Comment by bel2125** [comment]
Yes, the current state is good and stable ... although I have to check the open issues list here once again. One reason it's not yet released ... the "long term issue": #479
There is some branch for this and a new interface proposal ... I planned to make it available at least as "EXPERIMENTAL_INTERFACE", to get some first feedback.

**Comment by Dialga** [comment]
bump

**Comment by gjasny** [comment]
Hello,

it would really be nice to have an official version with working CMake export available.

Thanks,
Gregor

**Comment by bel2125** [comment]
The current version works well for Linux and Windows.
Right now I'm updating the release notes, doing some static code analysis, ...

I'm just currently not able to do (or delegate) any tests on MacOS.

**Comment by bel2125** [comment]
- [X] Automatic tests for Linux, Windows and MacOS
- [X] Manual test on Linux
- [ ] Manual test on Windows (with Executable for Sourceforge upload)
- [ ] Manual test on MacOS (with Executable for Sourceforge upload) <-- blocked, may be skipped
- [X] Update RELEASE_NOTES
- [X] Update CREDITS
- [X] Static code analysis
![image](https://user-images.githubusercontent.com/5619191/76802398-e07adf80-67d7-11ea-8a29-a3e2fb8c209b.png)
- [ ] Creating a release on GitHub
- [ ] Creating Zip with executables+documentation for Sourceforge Upload
- [ ] Announement on Google Groups (if anyone still looks there instead of looking at GitHub)

**Comment by bel2125** [comment]
done
