### ISSUE TITLE
Access violation - ctx->client_wait_events used in free_context. mg_start calls free_context if ctx->client_wait_events == NULL.

### ISSUE THREAD

**Issue by wgatesqs** [civetweb/civetweb#804]
In mg_start:

```
    if (ctx->client_wait_events == NULL) {
        mg_cry_internal(fc(ctx),
                        "%s",
                        "Not enough memory for worker event array");
        mg_free(ctx->worker_threadids);
        free_context(ctx);
        pthread_setspecific(sTlsKey, NULL);
        return NULL;
    }
```
In free_context:

```
#if defined(ALTERNATIVE_QUEUE)
    mg_free(ctx->client_socks);
    for (i = 0; (unsigned)i < ctx->cfg_worker_threads; i++) {
        event_destroy(ctx->client_wait_events[i]);
    }
    mg_free(ctx->client_wait_events);
#else
```

**Comment by bel2125** [comment]
I thought `mg_free(ptr)`, as the C library function `free(ptr)` does nothing if `ptr == NULL` ... but with the `USE_SERVER_STATS` define, it indeed uses this memory in `mg_free_ex`.
Did you set this define?

The easy fix would be to check for `ptr == NULL` in `mg_free_ex` as well - and it's probably the safest as well, since it satisfies the implicit expectation "free(0) is OK and does nothing" (see [here](https://www.tutorialspoint.com/c_standard_library/c_function_free.htm) or in the standard).

Just to be sure: Did you set this `USE_SERVER_STATS` define, and get the access violation in `mg_free_ex`? (or did I miss something?)

**Comment by wgatesqs** [comment]
Sorry, I should have been more specific. The issue is not with the mg_free call. The issue that caused the crash was with the line 

`event_destroy(ctx->client_wait_events[i]);`

That is where I got the access violation when it was trying to to access the NULL ptr.
