### ISSUE TITLE
mg_stat() fails on Windows for files with symbolic links

### ISSUE THREAD

**Issue by linev** [civetweb/civetweb#820]
I using German Windows version, which has directory "C:\Programme", which just a symbolic link to "C:\Program Files" folder. If I try to send file like ""C:\Programme\test\file.txt" with mg_send_file() function, civetweb fails. Problem is mg_stat() function, which cannot extract file information for such file. Problem with such files described also here: https://stackoverflow.com/questions/221417/

**Comment by bel2125** [comment]
Tested it with a German version - it seems the GUI works well:
![GermanWindows](https://user-images.githubusercontent.com/5619191/71913340-7dd1eb80-3177-11ea-96dd-c505a82a8db5.png)

You get a mixture of German and English dialogs (CivetWeb settings dialog is English; file/directory chooser dialog is German/System language), but the file chooser will replace the "C:\Programme\" with "C:\Program Files\".  The file chooser provides the resolved link, and civetweb.c will work with that.

If I understood it correctly, you are not using a a setting dialog that will automatically resolve links, but you are using a C API function with an unresolved link. Working with unresolved links in Windows was not intended/considered anywhere in the design, until now. I am not sure if calling "GetFinalPathNameByHandle" in `mg_stat` will solve all problems, or if it's just the beginning of a lot of troubles caused by not considering links for Windows at all (for Linux, Links just work "under the hood").

**Comment by linev** [comment]
Yes, I using direct civetweb API to send file by http request. 
Seems to be, I have to use `GetFinalPathNameByHandle` myself before calling `mg_send_file` on Windows.
