### ISSUE TITLE
arm-linux-uclibceabi-gcc 4.7.1  compile warning

### ISSUE THREAD

**Issue by Qinch** [civetweb/civetweb#821]
Hi, I have a compile warning, as follows:

**gcc version:**
arm-linux-uclibceabi-gcc 4.7.1

**compile command:**
make slib  CC=arm-linux-uclibceabi-gcc  COPT="-DNO_CGI -DNO_SSL "

src/civetweb.c: In function 'mg_get_system_info_impl':
**`src/civetweb.c:19051:9: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]`**

The -Wdate-time option is  added in gcc version 4.9. Can I ignore this warning?

**Comment by bel2125** [comment]
Line 19051 in what version?
Is ist this one in the current version
https://github.com/civetweb/civetweb/blob/8e911a9fa3558d7cbf02b6f66712bdeea255679b/src/civetweb.c#L19923

If yes, you can ignore this. 
It seems GCC decided some time ago to add a warning if __DATE__ or __TIME__ is used in a source code, that the binary will be different every time you compile. ... From my point of view. this compiler warning is plain stupid, because that's the very idea of __DATE__ and __TIME__.

**Comment by Qinch** [comment]
yes, thanks.
