### ISSUE TITLE
parse_port_string() is unable to resolve hostnames correctly

### ISSUE THREAD

**Issue by lmartanovic** [civetweb/civetweb#822]
I believe the commit https://github.com/civetweb/civetweb/commit/c9e47bf75b173c48f1af4e2199ee9904b9256057 breaks hostname resolution.

The last branch of the ``parse_port_string()`` function (around https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L14603) seems to be incorrect.

In the current state, a hostname string without the ":port" part is created (the ``hostname`` variable), but never used - the original ``vec->ptr`` is used instead.
This causes the whole string (including the ":port" part) to be passed to ``mg_inet_pton()`` resulting in ``getaddrinfo()`` not being able to resolve the address correctly.

IPv4 and IPv6 branches are both affected.

Possible solution is to just use the already prepared ``hostname`` variable.

**Comment by bel2125** [comment]
It seems you already analyzed and solved the problem.
Could you create a pull request?

Otherwise, could you post your fix here?

Do you have a test case (something like the `{"1.2.3.4:65535" --> valid=1, family=4, port=65535`) we already have?
https://github.com/civetweb/civetweb/blob/8e911a9fa3558d7cbf02b6f66712bdeea255679b/unittest/private.c#L596-L630

**Comment by lmartanovic** [comment]
I created a PR - https://github.com/civetweb/civetweb/pull/823

**Comment by bel2125** [comment]
PR is merged.
Regarding unit test: Please just give me an example
"input" --> "wrong result" / "correct result" - then I can add the unit test in ~5 minutes

**Comment by lmartanovic** [comment]
Thanks for merging the PR.

As for the testing example - it can be verified by running
./civetweb -listening_ports "localhost:8080"
It will fail with the error message

localhost:8080: invalid port spec (entry 1). Expecting list of: [IP_ADDRESS:]PORT[s|r]
Failed to setup server ports
Failed to start CivetWeb V1.11:
localhost:8080: invalid port spec (entry 1). Expecting list of: [IP_ADDRESS:]PORT[s|r]

Whereas after the fix, it will correctly resolve the address and produce the following output
CivetWeb V1.11 started on port(s) localhost:8080 with web root.

Is this enough?

**Comment by bel2125** [comment]
In fact, with this example it became much more clear what you actually want to do - and what additional issues you might encounter in doing so: "localhost" could be 127.0.0.1 or [::1] - some systems use the IPv4 others the IPv6 address (try "ping localhost" on different systems). So, binding to "localhost:80" will sometimes bind to IPv4, sometimes to IPv6 ... that's why I usually do not use (or recommend) it. Although it works, since client and server will *usually* use the same "localhost", support/diagnosis might be harder.

The example is enough, however, I have to do more than just adding a single line with "input --> valid (1/0), ip-family (4/6), port (0-65535)" like here:

https://github.com/civetweb/civetweb/blob/adf54959e0eaf00cb239177924555b3db12131fe/unittest/private.c#L625

since either `{"localhost:8080", 1, 4, 8080},` or `{"localhost:8080", 1, 6, 8080},` might be correct.

However, I think we can close this issue.

**Comment by lmartanovic** [comment]
Localhost is of course just an example and not my intended usage, but the gist of what you described is the exact reason why I wasn't really sure how to approach the unit tests. Thanks again for taking the testing part.

Will you close the issue, or should I do it?
