### ISSUE TITLE
function `set_option` in main.c (civetweb version 1.11) add a `break`

### ISSUE THREAD

**Issue by Qinch** [civetweb/civetweb#825]
function `set_option` in main.c (civetweb version 1.11),  code snippet is as follows:

```bash
	/* Not an option of main.c, so check if it is a CivetWeb server option */
	type = MG_CONFIG_TYPE_UNKNOWN;
	for (i = 0; default_options[i].name != NULL; i++) {
		if (!strcmp(default_options[i].name, name)) {
			type = default_options[i].type;
		}
	}
```

I think  that if `name` is found in `default_option`,  need to  add `break` to exit loop

**Comment by bel2125** [comment]
It makes no difference, if we add a break after line 636 or not: Since all options have a different name, we are only setting the "type" variable once (or never).

https://github.com/civetweb/civetweb/blob/adf54959e0eaf00cb239177924555b3db12131fe/src/main.c#L632-L642

The code is also executed only once, when the server is started. It would be a tiny performance improvement: adding a break may improve the starting time by some nanoseconds, but nothing once the server is started.
