### ISSUE TITLE
Single threaded server waits 1s between sending linked files.

### ISSUE THREAD

**Issue by Jezza2** [civetweb/civetweb#830]
I've noticed that when the number of worker threads is set to 1, uncached files linked to a web page (e.g. stylesheets, javascript files etc.) are loaded one at a time (obviously), but civetweb takes exactly one second between serving up each of those files.

I happened upon this because my company uses an in-house wrapper class to interface with civetweb and its default number of threads is 1. It took me far too long realise this and fix it!  Anyway after some digging, I still don't understand why it takes one second to handle each request.  Would you mind explaining?

**Comment by bel2125** [comment]
Depends on your other settings.
How did you send "enable_keep_alive"?
HTTP or HTTPS?

It also depends on the client. What client are you using: A browser, some library, ...?

> It took me far too long realise this and fix it!

How did you "fix" this?

**Comment by bel2125** [comment]
There is a test page including many linked filed in the test directory: 100images.htm
It loads quite quickly with just one task as well:

![image](https://user-images.githubusercontent.com/5619191/73212160-eb0ce700-414d-11ea-88c5-a35607f004c7.png)

So, I think there is another (an additional?) setting responsible for your observation, not just "num_thread". If you want to know what takes the time in your case, I need much more details on your specific test setting.

**Comment by Jezza2** [comment]
By 'fixed' I mean I increased the number of worker threads.  

This is using graphical browsers.  I've tested on Firefox, Chrome and Edge.  Firefox seems to do something different with its caching because it happens at every refresh, while Chrome and Edge don't have the issue once the page has been loaded for the first time.

These are HTTP requests.

> How did you send "enable_keep_alive"?

The requests have the "Connection: keep-alive" header, if that's what you mean.

I start the server with the following options set:
{"listening_ports",  "8080",
"num_threads", "1",
"enable_keep_alive", "yes"};

**Comment by bel2125** [comment]
I tested these settings with the current head version (1.12) on a Windows 10 system, and cannot reproduce a 1s delay between every file using the "100images.htm" test. Using 1 thread is absolutely not recommended if you client is a web browser. Web browsers tend to open multiple connections to a server when loading a web page, just to load resources in parallel - how many depends on the browser, the webpage (the network?) ... in my 100images test, it used 6 connections. I strongly recommend to use at least 5 threads when the client is a browser (could be less if your client is another program/script, curl, ...).
What probably happened: The browser asks for the web site using the first connection (in my case 100images.htm) closes this connection and evaluates the html content. There are a lot of images embedded (actually 100), so the browser opens 4 more connections and sends the "GET image1", "GET image2" ... "GET image100" (and I think another one for favicon). One of the connection is processed if you have just one thread. The others are accepted but not processed, the browser simply does not get any response here. A lot of images are loaded quickly, the final few images are only delivered after the first connection is closed. This is not a "1s per resource" situation, but a "many resources using the first connection" followed by "a few resources later" because the requests were sent but not accepted/processed.
If this behavior does not match with your observation, I would need a test page and the system spec (Windows/Linux, OS version?, server version? ... basically what is shown in "Show system information" in the Windows Standalone server).

**Comment by Jezza2** [comment]
Thanks a lot for your help.  As I say, I'm now using more threads so my initial issue is resolved.  Your description of what probably happens tallies with what I've been seeing.
