### ISSUE TITLE
Embedding server causes large virtual memory allocation

### ISSUE THREAD

**Issue by mandersen-ss** [civetweb/civetweb#837]
When embedding the server in a linux application the stack size for threads defaults to 8096. This causes a large chunk of virtual memory to be allocated. When compiling for stand-alone application using the provided makefile, each thread is given 102400 bytes of stack, thereby reducing the virtual memory footprint, resulting in more static memory allocation up-front, which can be desired from a preformance perspective.
In the documentation under embedding the server, please mention some details about thread stack size and what implications it would have. Also recommended sizes would be nice.

**Comment by bel2125** [comment]
Where did you find the default of 8096? Only in `#define ZEPHYR_STACK_SIZE 8096`, or somewhere else? (8096 is not an integer multiple of 4096, see below).

Big stack limits usually only require address space, not memory - the memory is only committed when the stack is really used. Windows reserves 1 MB address space for a task stack, Linux 8 MB (don't know if this is the case for all versions/distributions) - and you can have 1000 threads with 1 MB reserved address space, and still require less than 10 kB of memory.

Rules for finding a proper stack size:
- Stack comes in page sizes (4096 bytes for many architectures, in particular for X86). So always choose an integer multiple of 4096 (I think the system will round up otherwise).
1) If any thread exceeds its stack size limit, the entire process must be terminated. (--> never choose a too small stack size, add some extra space). Stack overflow issues are quite hard to find.
2) The overall address space is limited to 2 GB for 32 bit applications (no matter how much RAM the system has) or "unlimited" (Exa-Bytes) for 64 bit applications. Data, code and all stacks have to fit into this address space.

(up tp now, there is no relation to physical memory - the available RAM in the system is not important)

3) In the "non-embedded" case, the operating system will commit one page (4096 bytes) stack memory, whenever a thread requires an extra page, up to the address space limit for this thread. If there is no RAM available, the system will swap to disk (slow). If this is not possible, the system may run out of memory (but this has nothing to do with the stack size).
4) In the "embedded case", one may wish to pre-allocate the stack for several reasons (maybe more than listed here): Allocating a page "on demand" may take some time, compromising deterministic behavior. The embedded operating system may have a simpler memory management system than a general purpose operating system (e.g., an embedded OS may do a 1:1 mapping between virtual and physical memory). Hard to test allocation failures at run-time are avoided by pre-allocating and locking everything at start-time.
In this special case, the stack size really matters.
5) While for CivetWeb "itself", 8kB stack for a worker thread is enough, there are C/C++ handler functions and/or Lua scripts requiring additional stack size. How much depends on the handler/scripts. You can do "a lot" with 24kB (6 pages) - but see 1) - don't limit yourself it it's not required. I never had any problem with 64 kB, even with huge scripts. The 102400 Bytes = 100 kB (25 pages) - have some additional safety buffer.

Is explanation understandable? Is it helpful?

**Comment by mandersen-ss** [comment]
In civetweb.c this definition is there

#if defined(USE_STACK_SIZE) && (USE_STACK_SIZE > 1)
#define ZEPHYR_STACK_SIZE USE_STACK_SIZE
#else
#define ZEPHYR_STACK_SIZE 8096
#endif

Unless we define USE_STACK_SIZE it will be set to 8096. You are right that the OS it is running on has a minimum stack size and how it will distribute that between allocated/committed memory and virtual is up to the OS.
What I’m saying with this is that it should be mentioned in the embedded section that this needs to be considered. In our old linux it caused some issues if we didn’t specify it large enough up front.

**Comment by bel2125** [comment]
> Unless we define USE_STACK_SIZE it will be set to 8096 ...

Just to avoid a possible misunderstanding:
All uses of `ZEPHYR_STACK_SIZE` in the code are inside
`#if defined(__ZEPHYR__)`
This, unless you use the Zephyr operating system, this define to 8096 has no effect. If you do not set USE_STACK_SIZE and your operating system is Windows, Linux, .... (something else than Zephyr), the code will NOT default to a stack size of 8096 (or 8192).


I agree, it makes sense to add some information on stack sizes to https://github.com/civetweb/civetweb/blob/master/docs/Embedding.md

**Comment by mandersen-ss** [comment]
Ahh thanks, Missed it was under that flag. Then it makes more sense what we see that virtual mem is allocated as the thread stack is created/needed.
