### ISSUE TITLE
BoringSSL Support

### ISSUE THREAD

**Issue by gou4shi1** [civetweb/civetweb#843]
I link civetweb again boringssl (with `-DNO_SSL_DL`), meet this linkage error:
` error: undefined reference to 'DO_NOT_USE_THIS_FUNCTION__USE_mg_free'`
Related to https://boringssl.googlesource.com/boringssl/+/HEAD/PORTING.md#memory-allocation ?

**Comment by gou4shi1** [comment]
It works if I delete `#define free DO_NOT_USE_THIS_FUNCTION__USE_mg_free` from `civetweb.c`

**Comment by bel2125** [comment]
Probably BoringSSL defines "free" somewhere in a header? Although, I don't know where this could be.

The `#define free DO_NOT_USE_THIS_FUNCTION__USE_mg_free` is only there to make sure everybody contributing to civetweb.c (and *.inl) uses "mg_free" instead of "free".
You should not encounter this link error, unless some piece of code using "free" has been added to civetweb.c or a #included file after the #define line. Using "free" on a piece of memory allocated using "mg_malloc/mg_calloc/mg_realloc" may break memory usage statistics - so just deleting the #define is not recommended.

**Comment by gou4shi1** [comment]
How to test the civetweb with BoringSSL?
Any unit test/integration test?

**Comment by gou4shi1** [comment]
from `boringssl/src/include/openssl/mem.h`:
```
/* Memory and string functions, see also buf.h.
 *
 * OpenSSL has, historically, had a complex set of malloc debugging options.
 * However, that was written in a time before Valgrind and ASAN. Since we now
 * have those tools, the OpenSSL allocation functions are simply macros around
 * the standard memory functions. */

#define OPENSSL_malloc malloc
#define OPENSSL_realloc realloc
#define OPENSSL_free free
```

from `civetweb.c`:
```
		/* Strings returned from bn_bn2hex must be freed using OPENSSL_free,
		 * see https://linux.die.net/man/3/bn_bn2hex */
		OPENSSL_free(str_serial);
```

**Comment by bel2125** [comment]
I see.
Indeed, this combination causes the link error you found.
And, in this particular case, "free" is indeed the right function to use (not mg_free).
So the `#define free DO_NOT_USE_THIS_FUNCTION__USE_mg_free` should not be there for BoringSSL, but it should be there in other cases (at least for the unit test).


I did not test CivetWeb myself with BoringSSL - the project recommends not to use it (from https://github.com/google/boringssl):

> Although BoringSSL is an open source project, it is not intended for general use, as OpenSSL is. We don't recommend that third parties depend upon it. Doing so is likely to be frustrating because there are no guarantees of API or ABI stability.

**Comment by bel2125** [comment]
The corresponding pull requests are merged. Is there anything left to do, or can we close this issue?

**Comment by gou4shi1** [comment]
closed :)
