### ISSUE TITLE
Prevention of brute force login attack

### ISSUE THREAD

**Issue by veselinovicst** [civetweb/civetweb#857]
Hello, I am trying to implement prevention of a brute force login attack. 
The idea is to use request throttling (or tar pit) technique. I would like to set a number of possible requests to the login API endpoint per second. Does civetweb supports some kind of request throttling or do you have any suggestions how this could be implemented?

**Comment by bel2125** [comment]
Yes, it does support request throttling (see [UserManual](https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#throttle)) - the throttling is configured in kB/s (or B/s or MB/s). 
But I think it will not really help you during logins, since login is an exchange of quite small data. 

An easier way would be to sleep for ~1 second in the "login" API ... 
... or, for 10 seconds for every failed login attempt.

However, both sleep and throttle would make it vulnerable against denial of service attacks.

A more sophisticated approach would be to count login attempts on a "per user" or "per source IP" base, and then block only this user/IP for a longer time. By "block" I don't mean "throttle" or "sleep", but immediately reply with a "you are blocked for 8 hours" (or something like this) message.
Or you just block a user completely after 3, 5, ... failed login attempts, and require manual unlocking by an admin, or by a lengthy form with, ...

**Comment by veselinovicst** [comment]
Sorry for not answering sooner.

Thank you for your suggestions, I decided to go with fail2ban.
