### ISSUE TITLE
Allow pipe in get_uri_type()

### ISSUE THREAD

**Issue by grunk** [civetweb/civetweb#894]
I ran into a problem using postman against an api runned by civetweb. Postman does not urlencode the "|" anymore due to new standard [whatwg url](https://url.spec.whatwg.org/) which obsoleted RFC-3986. but civetweb still consider that the pipe char must be url encoded , hence the 400 bad request invalid uri.

You can read the detail [here](https://github.com/postmanlabs/postman-app-support/issues/8794).

Is there any plan to comply to whatwg url at some point ? I had a problems only with the pipe but i did not read the standard to see if something else changed, so maybe there is other chars involved.

**Comment by bel2125** [comment]
I don't see https://tools.ietf.org/html/rfc3986 is obsoleted. 
E.g., for https://tools.ietf.org/html/rfc2396 there is an "obsoleted by ..." mark, for 3986 there is not.
There are two updates, https://tools.ietf.org/html/rfc6874 and https://tools.ietf.org/html/rfc7320, both not dealing with `|`.
I did never consider "whatwg url" as any kind of standard and therefore had no plans to even read it. It seems to be drafts with ongoint work, but not a standard, at least not yet.
In the current standard (as to my knowledge this is still rfc3986), the pipe character is neither reserved nor unreserved.

Independent of standard or not, could you explain precisely what the problem is, and how to reproduce it?

**Comment by grunk** [comment]
Indeed i'm wrong by saying that rfc3986 is obsoleted.
Nevertheless it seems that most of the browsers (at least chromium based and firefox) now implements whatwg url and do not url encore the pipe.

So if i call : 
`http://mycivetserver/get?score=>|10 `
The browser will actually send : `http://mycivetserver/get?score=%3E|10` instead of `http://mycivetserver/get?score=%3E%7C10` 

which will return a 400 Bad Request Invalid URI because civetweb consider the pipe as un unsafe character as stated in rfc3986.

It seems easier to have civetweb supporting this new "trend" than asking each user to urlencode this specific character.

**Comment by bel2125** [comment]
Currently civetweb accepts only the following characters in URLs:
- reserved characters `:/?#[]@!$&'()*+,;=`
- unreserved characters `A-Z`, `a-z`, `0-9` and `-._~`
- and `%` for URL %-encoding

it rejects:
- spaces 
- control characters like newline (ASCII 0 - 31)
- tab
- everything above code 126 (all non-ASCII characters)
- `"<>\^{|}` and `

In a file system, at least the characters `"<>| ` and (for Windows) `\\` have some special meaning.

The whatwg website seems to have [7 different sets](https://url.spec.whatwg.org/#c0-control-percent-encode-set) of characters for 7 different % encodings. It seems they propose a different encoding subset for different parts of an URL - leading to high effort to implement. Probably this is due to the assumption that everything before `?` translates to a path in the file system while everything behind `?` to parameters for a script. This might be a reasonable default, but it's not strictly required, neither by a standard nor by the civetweb implementation.


> It seems easier to have civetweb supporting this new "trend" than asking each user to urlencode this specific character.

It would be possible to move URL validation from rejecting suspicious URLs when they are received to rejecting them when they are used. Only characters 0 to 32 (ctrl + space) need to be rejected at the beginning, before any further parsing/processing.
But this change has to be tested carefully.

A quick fix for your case would be to remove `case '|':  /* 124 */` from `get_uri_type`.

**Comment by bel2125** [comment]
Fixed.

**Comment by xtne6f** [comment]
@bel2125 : Please tell me what the purpose of `mg_path_suspicious()` is?
I agree with above discussions. There should be no reason to deny shell-metacharacters (such as `><|`) in `get_uri_type()` phase.
Then, `mg_path_suspicious()` (newly introduced) returns `0`(=not suspicious) in almost all cases. I think the behavior of `mg_path_suspicious()` is not wrong. Because the function is used only for `mg_fopen()` and `mg_stat()`, and these functions have no strong incentive to deny shell-metacharacters.
So, my only question is : why `mg_path_suspicious()` exists?

**Comment by bel2125** [comment]
Two main reasons:
1) Somewhere in request processing, I wanted to have a point where I can be sure that a path is what one would expect to be a path (you probably know **"Did you really name your son Robert'); DROP TABLE Students;--?**  from https://bobby-tables.com/). I don't want to think about if all API calls after this point handle all strange cases correctly - I don't want to think about `mg_fopen()` and `mg_stat()` handling all kind of weird filenames correctly. 
2) In case some new strange "feature" comes up, like a `Ctrl-R` in a filename means you read from the Windows Registry, there is one point where to fix this. Yes, that's a long shot - the idea is, `mg_path_suspicious` is a barrier for everything we don't want to have in the "inner" logic - for everything we know now and everything we may learn in future.
3) My intention was also to add user defined filters at this point. Rather as a callback than using pattern matching. Also "conn" is an input here, so it may be possible to hide files only for certain connections. But this is still in an experimental phase.

**Comment by xtne6f** [comment]
Thank you for your reply!
Then, is it okay to think of `mg_path_suspicious()` as no effect for now and may be implemented something in the future?
The current `mg_path_suspicious()` is the following:
```C
static int
mg_path_suspicious(const struct mg_connection *conn, const char *path)
{
	const uint8_t *c = (const uint8_t *)path;
	(void)conn; /* not used */

	if ((c == NULL) || (c[0] == 0)) {
		/* Null pointer or empty path --> suspicious */
		return 1;
	}

	while (*c) {
		if (*c <= 32) {
			/* Control character or space */
			return 0;
		}
		if ((*c == '>') || (*c == '<') || (*c == '|')) {
			/* stdin/stdout redirection character */
			return 0;
		}
#if defined(_WIN32)
		if (*c == '\\') {
			/* Windows backslash */
			return 0;
		}
#else
		if (*c == '&') {
			/* Linux ampersand */
			return 0;
		}
#endif
		c++;
	}

	/* Nothing suspicious found */
	return 0;
}
```

The part that I felt strange was the meaningless `while (*c)` loop (since all of `if()` blocks return `0`).
I didn't understand the intent of the loop.

**Comment by bel2125** [comment]
> The part that I felt strange was the meaningless while (*c) loop (since all of if() blocks return 0).
> I didn't understand the intent of the loop.

Now that you mention it: They should all return 1

**Comment by xtne6f** [comment]
I strongly think they don't need to return 1. Especially on Linux, they should not return 1.
On Linux, `><|\&` are all completely valid as filename characters:
`$ touch "><|\\&.txt"`

**Comment by bel2125** [comment]
Windows does not allow it:
![image](https://user-images.githubusercontent.com/5619191/99886471-114fc600-2c3d-11eb-99a8-50cc93a0852e.png)

And if I create `><|\\&.txt` inside WSL, it looks like this in the Windows Explorer ... but it does not seem to cause any problem:
![image](https://user-images.githubusercontent.com/5619191/99886506-452aeb80-2c3d-11eb-8956-6fc1b4c581da.png)

Linux seems to accept everything but `/` and the NULL character, even broken UTF-8.
Although POSIX "fully portable filenames" must only contain
```
    Alphabet upper case letters : A B C … Z (not recommended?)
    Alphabet lower case letters : a b c … z
    Numbers : 0 1 2 … 9
    Dot : .
    Underscore : _
    Minus : –
```

Probably the Linux APIs "stat", "fopen" and "access" accepts all these characters and work correctly - but what about "execle"?

It seem this needs a different treatment for Windows and Linux.

**Comment by bel2125** [comment]
Just tested: Linux execle will also accept filenames with `>` and not treat this as redirection.


So this means, only Windows needs to be checked more carefully, probably like this (not tested yet):
```C
/* Reject files with special characters (for Windows) */
static int
mg_path_suspicious(const struct mg_connection *conn, const char *path)
{
	const uint8_t *c = (const uint8_t *)path;
	(void)conn; /* not used */

	if ((c == NULL) || (c[0] == 0)) {
		/* Null pointer or empty path --> suspicious */
		return 1;
	}

#if defined(_WIN32)
	while (*c) {
		if (*c <= 32) {
			/* Control character or space */
			return 1;
		}
		if ((*c == '>') || (*c == '<') || (*c == '|')) {
			/* stdin/stdout redirection character */
			return 1;
		}
		if (*c == '\\') {
			/* Windows backslash */
			return 0;
		}
		if (*c == ':') {
			/* Windows drive letter */
			return 1;
		}
		if ((*c == '*') || (*c == '?')) {
			/* Wildcard character */
			return 1;
		}
		if (*c == '"') {
			/* Windows drive letter */
			return 1;
		}
		c++;
	}
#endif

	if (conn->phys_ctx->callbacks.block_access) {
		return conn->phys_ctx->callbacks.block_access(conn, path);
	}

	/* Nothing suspicious found */
	return 0;
}
```
I'm not sure about the space here - this needs to be tested for Windows.

**Comment by xtne6f** [comment]
Thank you. My question (why `mg_path_suspicious()` exists?) has been solved.
The original issue has been closed, so it's not good to have another discussion here.
If you are going to dig into this topic, I want you to reopen the issue or create a new issue for other contributers.
