### ISSUE TITLE
Set return code using civetweb CXX api

### ISSUE THREAD

**Issue by pietercardoen** [civetweb/civetweb#909]
Dear

I've analysed the examples provided by this project. In rest.c, a quite complete API is shown which allows us to configure return codes as we want to depending on internal logic. However using the embedded_cpp.cpp example, it is possible to define a handle and return true/false to indicate if the handle exists. It is however not possible to change return code.

Is it possible to have a look at this API and adapt it to be complete?

Thanks
Pieter

**Comment by bel2125** [comment]
During the last years, my approach was: 
The C API (civetweb.h) is complete and gets extended in the regularly. 
The C++ wrapper (CPP source) and C++ API is far from complete, and if a new feature is added to the C API, it will not be added automatically to the C++ API as well.

A well designed C API can be easily used in C++, and it can be wrapped into many other languages (scripting languages as well as compiled ones). For a fundamental library, a C interface is better usable than a C++ interface, since it allows a wider range of applications.
A C++ API cannot be used in C, and there are several very different "flavors" of C++ APIs, so a C++ API of one library may feel strange if used in combination with some other C++ API/framework. In addition, there are different C++ standards - I don't think all embedded compilers already support C++11 ... but in C++11/14/17, you would use a different API design as in C++98. The CivetServer C++ wrapper is just one possibility to wrap the C API, there are probably thousands of other ways, design concepts, ... to wrap the C API into C++ in a different fashion.
The unit test (CI test) is using the C API, not the C++ API.
For all projects I'm involved in, we use the C API, not the C++ wrapper.

> Is it possible to have a look at this API and adapt it to be complete?

The C++ API extensions were mostly community driven. Most extensions are merged pull requests, created by someone who actually used the C++ API. But the API needs to remain compatible, changing the meaning of return value will not be compatible, adding a new optional parameter or creating an overloaded function will be.

**Comment by pietercardoen** [comment]
Dear

Thanks for the explanation.

Knowing this, I think it's best for my application to migrate to the C API to have complete functionality.

PS. Embedded applications nowadays are also using modern C++. I'm currently copiling against C++17.

**Comment by bel2125** [comment]
Yes, using the C API is the complete API you should use. It's also documented here: 
https://github.com/civetweb/civetweb/blob/master/docs/APIReference.md#civetweb-api-reference

> PS. Embedded applications nowadays are also using modern C++. I'm currently copiling against C++17.

Lucky you ;-) 
I know some embedded developers who are still stuck with Visual Studio 2008.
