### ISSUE TITLE
Unclear how to build Lua C modules for use in Lua scripts under Civetweb

### ISSUE THREAD

**Issue by JoshuaPK** [civetweb/civetweb#929]
What is the correct way to build C-based modules for use in Lua scripts under Civetweb?  In my attempts I am getting errors complaining about symbols not being exported or liblua not able to be found.

I am building things as follows:
1. Create an environment with Lua 5.4.0 using Luarocks "Vert" package (https://github.com/aconbere/vert)
2. Clone the Civetweb source code.
3. Modify the Lua 5.4.0 source code under Civetweb so that it builds shared libraries.  (Using patterns seen in the Makefile and src/Makefile patches here: https://stackoverflow.com/questions/20848275/compiling-lua-create-so-files)
4. Build the Lua 5.4.0 under Civetweb
5. Build the Civetweb server.
6. Copy civetweb into place under the Vert environment.
7. Build a custom C module, linking to the shared Lua libraries under the Civetweb source code.
8. Use Luarocks to build a few other libraries (namely Luasocket).  Copy those libraries- the .lua and .so files and associated directories- under my main www directory.
9. Copy lua.5.4.so under my main www directory.
10. From that main www directory, run Civetweb using a config file in the parent directory.

I encounter two problems:

1. I have a script that I am running via the lua_background_script that uses luasocket to send an email out as a test.  If I run this under the Lua interpreter itself, it runs fine.  If I run Civetweb, Civetweb errors out with an error message: "lua_background_script error: Error running file /opt/abx/data/background.lua: error loading module 'socket.core' from file './socket/core.so':
        ./socket/core.so: undefined symbol: lua_gettop"

2. I have a page that connects to a websocket.  The websocket is controlled by a Lua script under Civetweb; the Lua script in turn runs some routines in a C module and returns the data via the websocket to the webpage.  I get this error when I try to open that page: "init failed: runtime error: error loading module 'test1' from file './test1.so':
        liblua.so.5.4: cannot open shared object file: No such file or directory"

For the second problem, liblua.so.5.4 is in the current working directory, and according to the path and cpath statements, it should be picked up.  But it seems to be related to the first issue, since both cases involve certain symbols or Lua itself not being available to the C shared libraries.  What am I doing wrong here?

Thanks!

**Comment by bel2125** [comment]
Since Lua 5.4 is pretty new I did not test it with this version, but I can explain how it works for Lua 5.2 and Lua 5.3 ... and later come back to Lua 5.4.

If you are building on a Linux system (maybe a Debian based distribution), you may wish to use the Lua library already included in your distribution (e.g., liblua.so.5.2.4 installed with apt-get install liblua5.2-0). To do so, you need to build using "make WITH_LUA_SHARED=1 WITH_LUA_VERSION=502" - 502 is the default, so you could skip this, but WITH_LUA_SHARED is not default. Without this flag, CivetWeb brings it's own Lua environment. When setting this flag, CivetWeb uses the Lua library of the system - you can choose, but probably this is what you want when you are asking for libraries from LuaRocks. Using WITH_LUA_SHARED, you can add Lua C libraries into the standard search directory for Lua C libraries, /usr/lib/lua/5.2/ or whatever.

Most likely you did not use the "WITH_LUA_SHARED" flag, so CivetWeb is linked with it's internal Lua interpreter, while another library might be linked to the Lua system library. This my cause this kind of error.

Since Lua5.4 is pretty new, so probably there is no liblua5.4 system package available yet (or maybe it is in the most recent version, but I'm usually using the long term stable versions). If it is not available, you probably should still use WITH_LUA_SHARED to use a liblua5.4 built by you. Then the C library you are building (luasockets) must use the same library.

I have no experience with "vert", so I don't know if this has any influence. I did never need it, since you can have different Lua versions installed side by side on Debian even without "vert".

**Comment by bel2125** [comment]
Was my explanation clear and did it work for you?
Is there anything else I can do here or can we close this issue?

**Comment by JoshuaPK** [comment]
It did work for me, thank you!
