### ISSUE TITLE
Question: Easy way to get the port clients connect to?

### ISSUE THREAD

**Issue by liurui39660** [civetweb/civetweb#936]
## Description

Hi, I'm using CivetWeb as an embedded server to provide multiple services to other parts of my program. 
I plan to use different ports for different services, but the port info is not directly available in the `mg_request_info`. 
Though the URL returned from `mg_get_request_link` or the `Host` entry in `mg_request_info::http_headers` include the port and I can match the `:` to get the port number, this method is a bit tedious and may not always succeed e.g. if the client connects to the default 80 or 443 port.
So, is there a more convenient and reliable way to get the port number that clients connect to? or would it be possible to allow `mg_set_request_handler` to additionally match the port?

## Pseudocode and Suggestions

```c++
#include <civetweb.h>

int main(int argc, char* argv[]) {
    mg_init_library(MG_FEATURES_DEFAULT);
    mg_callbacks callback{};
    const char* option[] = {
        "listening_ports", "80,81",
        nullptr
    };
    const auto context = mg_start(&callback, nullptr, option); // `context` check is ignored for simplicity
    mg_set_request_handler(context, "/", [](mg_connection* connection, void*) {
        int port = 0; // A naive solution
        const auto request = mg_get_request_info(connection);
        for (int i = 0; i < request->num_headers; i++) {
            if (!mg_strcasecmp(request->http_headers[i].name, "Host")) {
                const auto pos = strchr(request->http_headers[i].value, ':');
                if (pos) {
                    port = atoi(pos + 1);
                } else {
                    port = request->is_ssl ? 443 : 80;
                }
                break;
            }
        }
        mg_send_http_ok(connection, "text/plain", 0);
        return 200;
    }, nullptr);
    mg_set_request_handler(context, "/api", [](mg_connection* connection, void*) {
        const auto port = mg_get_request_info(connection)->request_port; // Proposed suggestion 1
        mg_send_http_ok(connection, "text/plain", 0);
        return 200;
    }, nullptr);
    mg_set_request_handler(context, ":81/proxy", [](mg_connection* connection, void*) { // Proposed suggestion 2
        mg_send_http_ok(connection, "text/plain", 0);
        return 200;
    }, nullptr);
    while (true) {}
    mg_stop(context);
    mg_exit_library();
}
```

## System Info

System: Windows 10 x64
Compiler: MSVC 19.27.29112 from Visual Studio v16.7.6
CivetWeb: 1.12, with SSL, from vcpkg 2020.07, triplet: x64-windows

**Comment by bel2125** [comment]
1) How to get the server port:

It seems you want to access `conn->client.lsa.sin.sin_port`. This is available as `SERVER_PORT` for CGI and as `mg.server_port` for Lua, but in the current C interface, it is only available using `mg_get_request_link`. It is not available in the "request_info" struct, since nobody asked for it ... up to now ;-) Appending this is no big deal - we can do this for the current master version.

2) Some general thoughts on using different port numbers for different services:

I am sure you have your reasons why you want to do this. 
In my designs, I always tried to use as few ports as (reasonably) possible. Different services use different URLs, not different ports. Using different ports will also limit the reuse of connections - one connection could send requests to different URLs (using HTTP/1 keep-alive or HTTP/2), but if a different port is required, the connection has to be closed. The current head version also supports connections/protocols that do not require a "port" as a 16 bit unsigned number, using Unix/Linux Domain Sockets.
I also don't know if there are more missing parts when using ports to identify services, since all applications and tests I'm aware of use different URLs for different services, not ports. These are also some reasons why I would not like to add some kind of port filtering to `mg_set_request_handler`.
One way to that already allows you to use port filtering, protocol filtering, ... would be to use more than one CivetWeb instance in one process. Different instances like `ctx1 = mg_start(&cb, NULL, opt_port_80);  ctx2 = mg_start(&cb, NULL, opt_port_81);` will allow you to use different callbacks for `mg_set_request_handler(ctx1, "/api", callback_port_80); mg_set_request_handler(ctx2, "/api", callback_port_81);`. Both server instances will have their separate set of worker threads in this case. You can use a completely independent set of options for the two instances.

**Comment by liurui39660** [comment]
Thanks for your reply. 

You can assume the program is a local proxy server with a web UI and some other features, that's why I'd like to use different ports. 

Indeed I can use another instance for the proxy part (or use a standalone proxy server application), but this may make the program unnecessarily more complex, as the proxy is not the primary feature. 

Just that using civetweb for this feature might not be the best solution, maybe I should look for other libraries and use civetweb only for the web UI and API.

**Comment by bel2125** [comment]
I can add the "server_port" to request_info. This is easy. If you don't want to use the "work in progress" head version or wait for the next release, you can also add this commit as a patch to the release version.

I just don't want to add port filtering for `mg_set_request_handler` (your solution 2). It would also add complexity to the civetweb core if you register overlapping handlers, some for all ports, some for distinct ports ... then unregister some ... There is also no filtering for other properties, cookies, protocol type/version, etc.  With the server port added to `request_info` you could still do this in the handler function (your solution 1).
