### ISSUE TITLE
Path limit/truncation on Windows with mingw-w64

### ISSUE THREAD

**Issue by endnil** [civetweb/civetweb#937]
While developing an application that uses a CivetWeb form handler to upload files, I found that long paths were being limited/truncated by CivetWeb on Windows.  I traced the problem to [this definition](https://github.com/civetweb/civetweb/blob/2fe6637/src/civetweb.c#L535):

```c
#define W_PATH_MAX ((PATH_MAX + 2) / 3)
```

... which limits paths to just under 90 characters.

`PATH_MAX` and `MAX_PATH` are both `260` when building with mingw-w64 5.0.1.

For my purpose, it was sufficient to change that to:

```c
#define W_PATH_MAX (MAX_PATH)
```

... but I don't know if that is going to work all the time. 

Is this a known limitation?

**Comment by xtne6f** [comment]
I also encountered the same problem in my private MinGW project, so I currently apply [this patch]( https://github.com/xtne6f/civetweb/commit/9efcc67a9a7ba7086cce2a6bbb4152593c7a7a74 ).
May I send a pull request? or please use this as a reference.

**Comment by bel2125** [comment]
Let me try to understand this situation - please tell me if anything written below appears incorrect to you:

The W_PATH_MAX has been introduced in [`Introduce a new constant W_PATH_MAX for wchar_t`](https://github.com/civetweb/civetweb/commit/664d7af6eac17833c55fa18aadb1440bbcc496b0), and it's a number of characters. 
```
#if !defined(PATH_MAX)
#define W_PATH_MAX (MAX_PATH)
/* at most three UTF-8 chars per wchar_t */
#define PATH_MAX (W_PATH_MAX * 3)
#else
#define W_PATH_MAX ((PATH_MAX + 2) / 3)
#endif
```

1) Does it assumes "the number of bytes per character is at most three" - which is not entirely correct - or - "if the character did fit into one uint16_t, it will fit in one, two or three bytes (uint8_t)" - which is correct, but I'm not sure if it fits with the rest of CivetWeb logic. 
Some (rare) Chinese characters such as 𨭎, Adlam characters as 𞤪, mathematical symbols as 𝒞 and emotes use 4 bytes to encode, and you can use them as filenames (already tested, see [test/nonlatin/这...](https://github.com/civetweb/civetweb/blob/master/test/nonlatin/%E8%BF%99%E6%98%AF%E4%B8%80%E4%B8%AA%E7%A4%BA%E4%BE%8B%E6%96%87%E6%9C%AC.html) and [test/nonlatin/𞤪...](https://github.com/civetweb/civetweb/blob/master/test/nonlatin/%F0%9E%A4%80%F0%9E%A4%A3%F0%9E%A4%A4%F0%9E%A4%A2%F0%9E%A4%A5%20%F0%9E%A4%86%F0%9E%A4%B5%F0%9E%A4%A4%F0%9E%A4%A2%F0%9E%A4%AA.txt)). All characters outside the [Base Multilingual Plane (BMP)](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane) will have 4 bytes to encode.
CivetWeb internally encodes everything as UTF-8, a variable length encoding with 1 to 4 bytes for each character. This is perfectly fine for Linux, but the Windows API functions (for file access) do not understand UTF-8. Thus, there is a small conversion layer for Windows to convert UTF-8 to UTF-16 (a variable length encoding with one or two 16 bit words for each character, everything within the BMP uses one word, everything outside two words). As far as I remember: The UTF-16 API allows a file name length of up to 32767 words (minus a few). This is less than 32767 characters, if there are non-BMP characters. However, there is no 260 character limitation if the UTF-16 (wide character) API functions are used (see [here](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation)).
The define `W_PATH_MAX` is used for 16 bit words (`wchar_t wbuf[W_PATH_MAX];`), while `PATH_MAX` is used for bytes (`char buf[PATH_MAX]`); One 16 bit word (one character in the BMP) can not have more than 3 bytes in UTF-8, two 16 bit words (a surrogate pair) will have 4 bytes in UTF-8.
A typical use is `wchar_t wbuf[W_PATH_MAX]; path_to_unicode(..., utf8path, wbuf, ARRAY_SIZE(wbuf));`
If there are 250 non-BMP characters, this would be 1000 bytes in UTF-8 and also 500 elements (1000 bytes) in an uint16_t array with UTF-16 encoding, since all characters would use surrogates.
If there are 250 [Vai](https://en.wikipedia.org/wiki/Vai_(Unicode_block)) characters, this would require 750 bytes in UTF-8 but only 250 elements (500 bytes) in an uint16_t array with UTF-16 encoding. 
If there are 250 [Russian](https://en.wikipedia.org/wiki/Cyrillic_(Unicode_block)) characters, this would require 500 bytes in UTF-8 and 250 elements (500 bytes) in an uint16_t array with UTF-16 encoding. 
If there are 250 English/ASCII/[Basic latin](https://en.wikipedia.org/wiki/Basic_Latin_(Unicode_block)) characters, this would require 250 bytes in UTF-8 and 250 elements (500 bytes) in an uint16_t array with UTF-16 encoding.
The maximum factor of "characters to UTF-8 bytes" is four. The maximum factor of "UTF-16 words to UTF-8 bytes" is three.
(My) Linux uses different PATH_MAX in different header files (hooray!), e.g. 1024 in Xwindows.h and 4096 in limits.h and some comments confusing "number of characters" and "number of bytes in the buffer".
Windows uses 260 for the Multibyte API (we are not using) and 32K UTF-16 uint16_t words for the wide character API (we are using), so worst case would be a limit of 16K characters.

2) #if !defined(PATH_MAX)
-) Linux (GCC or clang):
`#if !defined(PATH_MAX)` will be `false` in Linux, since Linux defines this in limits.h (or somewhere).
The `#define W_PATH_MAX ((PATH_MAX + 2) / 3)` will be set, but Linux does not use it for anything. It is only used in Windows file system access function wrappers. I removed the define and the Linux version still compiles
-) Windows (Visual Studio):
`#if !defined(PATH_MAX)` will be `true`, since the definition is not called PATH_MAX, but MAX_PATH there - its value is 260.
The `#define PATH_MAX` is effectively multiplied by 3, to extend the limit from "256 ASCII characters" to "256 BMP characters" (subtracting some drive letter :\). 
The `#define W_PATH_MAX ((PATH_MAX + 2) / 3)` is not reached and could be removed as well.
-) Windows (MinGW):
This is a system I personally don`t use for production. There are some unit tests, but they probably never tested long file names. Regarding #if !defined(PATH_MAX):

> PATH_MAX and MAX_PATH are both 260 when building with mingw-w64 5.0.1.

So, PATH_MAX is defined, thus `#define W_PATH_MAX ((PATH_MAX + 2) / 3)` will be set to 87 - and this is the only combination actually using the result.

We could drop the entire block above, ignore what Windows defined as MAX_PATH and use:

```
#if defined(_WIN32)
/* Limit to 1000 characters (999 + termination) */
/* Buffer size for 1000 characters in UTF-8: At most four bytes per unicode character */
#define PATH_MAX 4096
/* Buffer size for 1000 characters in UTF-16: At most 2 uint16_t per unicode character */
#define W_PATH_MAX 2048
#endif
```

... I think I need to review this idea tomorrow ... and I would be happy for a second opinion here!

**Comment by xtne6f** [comment]
For example, when we use `WideCharToMultiByte()`, we will often write like this:

```
wchar_t src[W_PATH_MAX];
char dest[PATH_MAX];
WideCharToMultiByte(CP_UTF8, src, dest);
```

The main usage of `W_PATH_MAX` is this. That is why we must keep `PATH_MAX` three times as large as `W_PATH_MAX`.
Then, when we use `MultiByteToWideChar()`, we have to do like this:

```
char src[PATH_MAX];
wchar_t dest[PATH_MAX];
MultiByteToWideChar(CP_UTF8, src, dest);
```

Needless to say, `W_PATH_MAX` is not for `UTF-8 -> wchar_t` conversion.

Then, the 260 path-limitation is basically still enabled for the wide character API even for Windows10.
(It can be disabled on the latter Windows10, but most users would leave it enabled.)
Because if we want to avoid the limitation, we must explicitly insert a "\\\\?\\" prefix for each API call according to [the document]( https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation ).
Therefore, even if we redefine `PATH_MAX` as 4096, the limitation for most users is still 260.

What's unexpected to me was only that MinGW predefines `PATH_MAX`, so I decided to introduce `MG_PATH_MAX` in [this patch]( https://github.com/xtne6f/civetweb/commit/9efcc67a9a7ba7086cce2a6bbb4152593c7a7a74 ).
Though I don't know the re-definition of `PATH_MAX` is legal or not, if you redefine the macro, `#undef PATH_MAX` would be required before `#define PATH_MAX xxx`.

**Comment by bel2125** [comment]
> Then, the 260 path-limitation is basically still enabled for the wide character API even for Windows10.

The problem with most documentation is, they do not clearly distinguish between
- "character" conceptually one element of writing, no matter how you encode it. 
- A unicode character code point (21 bits). 
- a "char" in C ... you can use a char array to store UTF-8 (Linux) or code-page specific multibyte elements (Windows) 
- a "wchar_t" as uint32_t (utf32char_t) with UTF-32 encoding in Linux and uint16_t (utf16char_t) UTF-16 multiword element (store either one or one half unicode character code point)
 
So I'm not sure what exactly is limited by 260 when using the Windows wide character API. Probalby the number of uint16_t UTF-16 multiword element - I don't know it the Windows API would care about broken surrogate. My factor of two between W_PATH_MAX and PATH_MAX above was a conclusion from the concept of a "unicode code point character" limit.
I will do some tests.

**Comment by bel2125** [comment]
1) Latin using fopen

```C
	char pname[1024];
	int i;

	/* Create some long name */
	memset(pname, 'x', sizeof(pname));
	for (i = 0; i < sizeof(pname); i+=10) {
		pname[i] = '0' + (i/10)%10;
	}
	memcpy(pname, "C:\\tmp\\x\\", 9);

	for (i = 1023; i > 10; i--) {
		pname[i] = 0;
		FILE * f = fopen(pname, "w");
		if (f) {
			fprintf(f, "OK @ %i bytes\n", i);
			fclose(f);
			break;
		}
	}
```
==> "OK @ 259 bytes"
Filename is "C:\tmp\x\x1xxxxxxxxx2xxxxxxxxx3xxxxxxxxx4xxxxxxxxx5xxxxxxxxx6xxxxxxxxx7xxxxxxxxx8xxxxxxxxx9xxxxxxxxx0xxxxxxxxx1xxxxxxxxx2xxxxxxxxx3xxxxxxxxx4xxxxxxxxx5xxxxxxxxx6xxxxxxxxx7xxxxxxxxx8xxxxxxxxx9xxxxxxxxx0xxxxxxxxx1xxxxxxxxx2xxxxxxxxx3xxxxxxxxx4xxxxxxxxx5xxxxxxxx"

2) Latin using _wfopen
```C
	char pname[1024];
	wchar_t wbuf[32768];
	int i;

	/* Create some long name */
	memset(pname, 'y', sizeof(pname));
	for (i = 0; i < sizeof(pname); i+=10) {
		pname[i] = '0' + (i/10)%10;
	}
	memcpy(pname, "C:\\tmp\\x\\", 9);

	for (i = 1023; i > 10; i--) {
		pname[i] = 0;

		MultiByteToWideChar(CP_UTF8, 0, pname, -1, wbuf, 32768);
		FILE * f = _wfopen(wbuf, L"w");
		if (f) {
			fprintf(f, "OK @ %i bytes\n", i);
			fclose(f);
			break;
		}
	}
```
==> "OK @ 259 bytes"
Filename is "C:\tmp\x\y1yyyyyyyyy2yyyyyyyyy3yyyyyyyyy4yyyyyyyyy5yyyyyyyyy6yyyyyyyyy7yyyyyyyyy8yyyyyyyyy9yyyyyyyyy0yyyyyyyyy1yyyyyyyyy2yyyyyyyyy3yyyyyyyyy4yyyyyyyyy5yyyyyyyyy6yyyyyyyyy7yyyyyyyyy8yyyyyyyyy9yyyyyyyyy0yyyyyyyyy1yyyyyyyyy2yyyyyyyyy3yyyyyyyyy4yyyyyyyyy5yyyyyyyy"

3) Р (looks like Latin P but is Cyrillic u+00000420, requiring two bytes in UTF-8) using _wfopen

```C
	char pname[1024];
	wchar_t wbuf[32768];
	int i;

	/* Create some long name */
	memset(pname, 'y', sizeof(pname));
	for (i = 0; i < sizeof(pname); i+=10) {
		pname[i] = '0' + (i/10)%10;
	}
	memcpy(pname, "C:\\tmp\\x\\", 9);

	for (i = 10; i < sizeof(pname); i += 2) {
		pname[i + 0] = 0xd0;
		pname[i + 1] = 0xa0;
	}

	for (i = 1023; i > 10; i--) {
		pname[i] = 0;

		MultiByteToWideChar(CP_UTF8, 0, pname, -1, wbuf, 32768);
		FILE * f = _wfopen(wbuf, L"w");
		if (f) {
			fprintf(f, "OK @ %i bytes\n", i);
			fclose(f);
			break;
		}
	}
```
==> "OK @ 508 bytes". 
Filename is "C:\tmp\x\yРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРРР", 10 Latin characters + 249 Cyrillic Р 
wbuf[257] =1056
wbuf[258] =1056
wbuf[259] =0

4) ꖩ (a Vai character ... looking like a water tap symbol ... whatever it means ... it requires 3 bytes in UTF-8) using _wfopen
 
```C
	char pname[1024];
	wchar_t wbuf[32768];
	int i;

	/* Create some long name */
	memset(pname, 'y', sizeof(pname));
	for (i = 0; i < sizeof(pname); i+=10) {
		pname[i] = '0' + (i/10)%10;
	}
	memcpy(pname, "C:\\tmp\\x\\", 9);

	for (i = 10; i < sizeof(pname); i += 3) {
		pname[i + 0] = 0xea;
		pname[i + 1] = 0x96;
		pname[i + 2] = 0xa9;
	}

	for (i = 1023; i > 10; i--) {
		pname[i] = 0;

		MultiByteToWideChar(CP_UTF8, 0, pname, -1, wbuf, 32768);
		FILE * f = _wfopen(wbuf, L"w");
		if (f) {
			fprintf(f, "OK @ %i bytes\n", i);
			fclose(f);
			break;
		}
	}
```
==> "OK @ 757 bytes"
The filename is "C:\tmp\x\yꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩꖩ", 10 Latin characters + 249 ꖩ 
wbuf[257] =42409
wbuf[258] =42409
wbuf[259] =0

5) 𨭎 (non BMP) using _wfopen

(Whatever 𨭎 actually means.)

```C
	char pname[1024];
	wchar_t wbuf[32768];
	int i;

	/* Create some long name */
	memset(pname, 'y', sizeof(pname));
	for (i = 0; i < sizeof(pname); i+=10) {
		pname[i] = '0' + (i/10)%10;
	}
	memcpy(pname, "C:\\tmp\\x\\", 9);

	for (i = 10; i < sizeof(pname); i += 4) {
		pname[i + 0] = 0xf0;
		pname[i + 1] = 0xa8;
		pname[i + 2] = 0xad;
		pname[i + 3] = 0x8e;
	}

	for (i = 1023; i > 10; i--) {
		pname[i] = 0;

		MultiByteToWideChar(CP_UTF8, 0, pname, -1, wbuf, 32768);
		FILE * f = _wfopen(wbuf, L"w");
		if (f) {
			fprintf(f, "OK @ %i bytes\n", i);
			fclose(f);
			break;
		}
	}
```
==> "OK @ 509 bytes" = 509 bytes from initial byte buffer pname
Pathname here is "C:\tmp\x\y𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎�", 10 Latin characters + 124 times 𨭎 + one broken character �
The broken character is [the u+fffd replacement character](https://www.fileformat.info/info/unicode/char/fffd/index.htm) in `wbuf[258]`.
wbuf[254]=55394
wbuf[255]=57166
wbuf[256]=55394
wbuf[257]=57166
wbuf[258]=65533
wbuf[259]=0

6) Same as 5, but changing the loop
`for (i = 10; i < sizeof(pname); i += 4) {` --> `for (i = 9; i < sizeof(pname); i += 4) {`
==> "OK @ 509 bytes"
Filename is "C:\tmp\x\𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎𨭎", 9 Latin characters + 125 𨭎, this time no broken character
wbuf[255]=55394
wbuf[256]=57166
wbuf[257]=55394
wbuf[258]=57166
wbuf[259]=0

By the way, NotePad++ cannot open any of these files when using right click and "Open with Notepad++".

So it seems the API limit is actually uint16_t array elements, not unicode characters.

Probably the Windows wchar_t file API uses just UCS-2 and does not care about any UTF-16 surrogates - I can check this using _wfopen with a bunch of broken surrogates and see what happens.

**Comment by xtne6f** [comment]
Windows NT 3.1 (the origin of Unicode API set) was released in 1993, then surrogate pair was introduced in Unicode 2.0 (1996). So I think it is natural that the limitation is based on UCS-2 (uint16_t array elements).

**Comment by bel2125** [comment]
I tried some million names starting with "C:\tmp\x\" followed by
```C
		wbuf[9] = 0xD000 + rand() % 0xFFF;
		wbuf[10] = 0xD000 + rand() % 0xFFF;
		wbuf[11] = 0xD000 + rand() % 0xFFF;
		wbuf[12] = 0;
```
This generates millions of invalid surrogates.
Indeed the API does not care.

Conclusion: The limit is 259 UCS-2 characters.

**Comment by endnil** [comment]
Thanks for the feedback and detailed analysis, @xtne6f and @bel2125 -- that all makes sense.  Shall I leave the fix to you?

CivetWeb is awesome, thanks for maintaining it!

**Comment by bel2125** [comment]
```C
#if defined(_WIN32)
/* The limit for Windows is 259 UCS-2 characters (plus termination). */
/* PATH_MAX is the char buffer size reuired for 259 BMP characters in UTF-8 encoding. 
 * Every character needs at most three bytes + 1 for null termination.
 * Non-BMP characters would require four bytes per character, but they would require
 * two 16-bit wchar_t and hit another limit later. */
#define PATH_MAX (3*259+1)
/* W_PATH_MAX is the wchar_t buffer size required for 259 UCS-2 characters + null termination */
#define W_PATH_MAX (259+1)
#endif
```

**Comment by endnil** [comment]
f4299db looks good, thank you.

Since those definitions are now specific to `_WIN32`, could one reasonably expect `MAX_PATH` to be defined, and hence replace the literal `260`?  The value is of course very unlikely to change, but it might save some surprises later.

**Comment by xtne6f** [comment]
(This is my personal impression, but..) I feel your source comments at f4299dbdefb9ab84e1eb0f89985961750c6ae003 are too many.

**Comment by bel2125** [comment]
> (This is my personal impression, but..) I feel your source comments at f4299db are too many.

Probably it is.
Initially it was not clear to me, why a buffer of `wchar_t wbuf[N]` corresponds to `char buf[3*N]`, and why MinGW behaves differently. Maybe it's also not clear to others, maybe I have forgotten if I look at the same piece of code in five years.
A short source code comment with a link referencing some GitHub issue comment for more details would have worked as well. Then the insights are not lost, and there is no essay in the source code.

Should we change it?

**Comment by xtne6f** [comment]
As I mentioned above, `PATH_MAX` is already defined in MinGW.
If you redefine it (I DON'T recommend to do it), you should do `#undef PATH_MAX`.

```
civetweb.c:557: warning: "PATH_MAX" redefined
  557 | #define PATH_MAX (3 * 260)
      |
In file included from x86_64-w64-mingw32/10.2.0/include-fixed/limits.h:195,
                 from x86_64-w64-mingw32/10.2.0/include-fixed/syslimits.h:7,
                 from x86_64-w64-mingw32/10.2.0/include-fixed/limits.h:34,
                 from x86_64-w64-mingw32/include/stdlib.h:11,
                 from civetweb.c:324:
x86_64-w64-mingw32/include/limits.h:20: note: this is the location of the previous definition
   20 | #define PATH_MAX 260
      |
```

`MAX_PATH` is not directly related to `PATH_MAX`. I think you can use `MAX_PATH` instead of `260`.

In my personal opinion, unless there is particular reason, library macros such as `PATH_MAX` should not be redefined.
For instance, `PATH_MAX` means the maximum of return size of `realpath()`. If you redefine it, some confusion may occur.

Since source comments are not an encyclopedia, I think we don't need to comment like what we can find by searching/googling.
If you have something to mention in detail, I recommend that you use commit comments.
(Documents and header files should have different policies.)

**Comment by xtne6f** [comment]
Oh, thank you for you commit 1f712c0ec75e8577996e65a3b6624455e55c5d54 .

**Comment by bel2125** [comment]
I removed the comment and replaced it with a reference to this issue:

```C

/* The Microsoft Visual Studio SDK defines MAX_PATH, but not PATH_MAX.
 * Linux defines PATH_MAX but not MAX_PATH. MinGW defines both.
 * Linux uses UTF-8 filenames, and (typically) defines PATH_MAX as 4096
 * (see https://eklitzke.org/path-max-is-tricky).
 * Windows cannot handle UTF-8 directly but uses UCS-2 (UTF-16 without checking
 * surrogate pairs in the file API).
 * CivetWeb internally uses UTF-8 on every system, thus it can use direct 
 * file API calls in Linux, but needs to convert all filen names for Windows.
 *
 * Windows has an internal limit of 259 UCS-2 characters (plus termination).
 *
 * PATH_MAX is used in CivetWeb as char[] buffer size for UTF-8 name
 * representations. Every character in the BMP (Basic Multilingual Plane)
 * encoded as UTF-8 requires 1, 2 or 3 bytes. A BMP character encoded as
 * UTF-16 always requires one 16-bit word. A character outside the BMP
 * requires 4 bytes in UTF-8 and two 16-bit words in UTF-16 (a surrogate
 * pair).
 * Thus, a 3*259+1 bytes buffer for UTF-8 encoded text will allways be
 * sufficent to hold a 295+1 word UTF-16 encoded text.
 * We do not need 4*259+1 bytes for the UTF-8 text buffer, since none BMP
 * characters would require two words in UTF-16 and hit the UCS-2 length
 * limit of the Windows file API.
 *
 * As a conclusion: For Windows we define W_PATH_MAX to 260 (259 BMP 
 * characters encoded in 16 bit wchar_t) and PATH_MAX to 260*3 (256
 * BMP characters encoded in 8 bit char).
 * For MinGW PATH_MAX needs to be undefined first. 
 */
```

It was absolutely not easy to find this information by googling, and there is not one place but it is a summary of several sources and experiments - and there are also wrong some references out there. Collecting and verifying this information took me quire some time.

The [AppVeyor build 1914](https://ci.appveyor.com/project/civetweb/civetweb/builds/36319943) just finished, and it works for Visual Studio and MinGW, as well as the [TravisCI build 2081](https://travis-ci.org/github/civetweb/civetweb/builds/743749525) for Linux and MacOS (there seems to be an unrelated issue in the experimental AppVeyor Ubuntu build). 

From my understanding, we need to redefine PATH_MAX for MinGW, since it would be 260 and we need it to be 780.

**Comment by xtne6f** [comment]
>Alternatively, we could get rid of PATH_MAX entirely and use UTF8_PATH_MAX (like W_PATH_MAX) instead.

I like this kind of solution. I feel `UTF8_PATH_MAX` you suggested is more clear than `PATH_MAX`. We can clarify that the purpose of the macro is to store UTF-8(converted) path, then we should be able to prevent some misuses (such as the current implementation of `spawn_process()`).
However, I'll leave it to your choice. Redefining `PATH_MAX` is a simple solution. I think one of the virtues of Civetweb is simplicity.

Although it's a trivial matter (no need to fix), is `#ifdef PATH_MAX` before `#undef PATH_MAX` needed?
I believe there are no compilers that complain something even if we "undef" an undefined macro.

**Comment by bel2125** [comment]
What do you think: Shall we close this issue, or is there anything (urgent) left to do?

**Comment by bel2125** [comment]
Sorry, I did not see your comment before (did not refresh the page before commenting myself).

> Although it's a trivial matter (no need to fix), is #ifdef PATH_MAX before #undef PATH_MAX needed?
> I believe there are no compilers that complain something even if we "undef" an undefined macro.

I'm almost sure I have already seen this complaint by some compiler.


> I feel UTF8_PATH_MAX you suggested is more clear than PATH_MAX.

Then we should probably do this.

**Comment by bel2125** [comment]
I changed PATH_MAX into UTF8_PATH_MAX and UTF16_PATH_MAX. I think it will take half a day from now, until the AppVeyor build chain has done all builds and unit tests on all outstanding commits ... so, let's see tomorrow.

**Comment by bel2125** [comment]
We did a lot in this issue: research on character encoding, API limits, SDK defines, documentation, code readability improvements ... by the way, we also solved the original issue.

I think we can close this issue now.

**Comment by xtne6f** [comment]
7bb01edef3f22dc606389ff8b481be0c2300745f seems to have completely solved this issue. Thank you.
