### ISSUE TITLE
Any plan to support OpenSSL 1.1.1 which supports TLS 1.3

### ISSUE THREAD

**Issue by ganeshkamath89** [civetweb/civetweb#938]
OpenSSL 1.1 has recently not had any updates, 
Supported until 2019-09-11

But OpenSSL 1.1.1 release is happening frequently. Also OpenSSL 1.1.1 has support:
Supported until 2023-09-11 (Long Term Support)

This is as per Wikipedia page: https://en.wikipedia.org/wiki/OpenSSL

So I am requesting that the OpenSSL change to 1.1.1 be considered soon.

**Comment by bel2125** [comment]
CivetWeb already supports OpenSSL 1.1.1 - I think this is the standard version in Ubuntu 18.04 LTS

OpenSSL has a very strange version numbering system.
1) OpenSSL 0.9.x and 1.0.x use the first API version ... you need to define OPENSSL_API_1_0 to use it
2) OpenSSL 1.1.x (this includes 1.1.0 and 1.1.1) uses the second API version ... you need to define OPENSSL_API_1_1 to use it
3) OpenSSL 3.0 uses the third API version. It seems there is no OpenSSL 2.0. Since OpenSSL 3.0 is still in [alpha state](https://www.openssl.org/blog/blog/2020/10/20/OpenSSL3.0Alpha7/), I did not check it yet

Since you want to use 1.1.1, you need to use the second API version which is OPENSSL_API_1_1  ... please forward any complaints about this version numbering confusion to the OpenSSL developers.

**Comment by ganeshkamath89** [comment]
Thank you. After defining the Proprocessor OPENSSL_API_1_1, it worked for me.
