### ISSUE TITLE
very large VIRT(VSS) size

### ISSUE THREAD

**Issue by laoshaw** [civetweb/civetweb#950]
I just noticed civetweb has 3GB for Virt memory(VSS) while 4MB for RSS, comparatively, lighttpd has 8MB for Virt and 4MB for RSS, why does civetweb need such a large size for VSS?

**Comment by bel2125** [comment]
You are probably using a Linux machine, and not explicitly setting any stack size limit, right?
Could you check "ulimit -s" ... probably it's 8192 (8 MB).
Could you also check your civetweb configuration file for "num_threads". If you did not set it, it's 50.
What did you use to see VSS/RSS ... "top"?

The reason is, civetweb uses separate thread for separate connections. This allows a connection/request handler function to call blocking or lengthy operations without blocking other connections. For each thread the entire stack size (plus one additional page with 4kB at top/bottom) are allocated in VSS but not in RSS. 8 MB * 50 threads = 400 MB.
You can see what it actually mapped in VSS using ``cat /proc/`pidof civetweb`/maps``.

**Comment by bel2125** [comment]
Was my explanation clear, or are there any more questions? Can we close this issue?

The method to reduce the stack size and virtual memory is to set the USE_STACK_SIZE define, e.g., -DUSE_STACK_SIZE=16384

**Comment by laoshaw** [comment]
Yes Thanks!
