### ISSUE TITLE
mg_callbacks struct being destroyed at the end in Windows

### ISSUE THREAD

**Issue by ifekonja** [civetweb/civetweb#968]
Last entry "init_connection" is sometimes initialised with 0xcccccccccccc
Which causes the crash under Windows 10, using as source code bound in app.
As workaround , I have added one more entry:
	int (*dummy_function_to_destroy)();

**Comment by bel2125** [comment]
I think this can only occur, if the header file (civetweb.h) used to compile the application using a civetweb DLL does not match with the header used when compiling this DLL - either because the headers are taken from different civetweb versions, or they use different preprocessor settings (`#define MG_EXPERIMENTAL_INTERFACES`, `MG_LEGACY_INTERFACES` ... depending on the version).

**Comment by ifekonja** [comment]
Yes, thanks, I have moved all #defines to civetweb.h and it works now.

**Comment by bel2125** [comment]
ok.
So, can we close this issue?

**Comment by ifekonja** [comment]
Yes, thanks

V sre., 17. feb. 2021 15:52 je oseba bel2125 <notifications@github.com>
napisala:
