### ISSUE TITLE
Integrating with other threading models

### ISSUE THREAD

**Issue by mjs476** [civetweb/civetweb#972]
Our C++ application is single-threaded and uses Linux poll() to respond to external events. We would like to integrate civetweb into this poll() call. What would be the recommended way to do this?

I see civetweb has its own threads and threading model, and notably it has a thread-per-request model, which means it might be safe to have a CivetHandler forward the request to our poll() thread and then block until our poll() thread constructs the response and notifies the CivetHandler thread. Does this sound reasonable? Is there some more efficient way?

Thanks!

**Comment by bel2125** [comment]
Yes, civetweb uses one thread for each connection - if you enable keep_alive, you can reuse a connection for multiple requests, so you don't need a thread for each request, but the conclusion remains the same: "which means it might be safe to have a CivetHandler forward the request to our poll() thread and then block until our poll() thread constructs the response and notifies the CivetHandler thread."

In fact that's a main advantage of having one thread for each connection (or request): You can block in a request handler without blocking any other connection.

> Is there some more efficient way?

Hard to say without any knowledge on your specific application and without discussing what "efficient" means for you. It is a safe to do so from the architectural point of view - so it's "efficient" from the point of view that there is basically no technical risk in doing so, and it's also efficient from the required development time. Could you optimize something in order to use less memory, CPU, ... - that depends on details of your use case. You might still do some optimizations by fine-tuning the configuration (setting num_threads, timeouts, queue sizes, ...). 
You should also check in advance if you want to use the full C API or the C++ wrapper (CivetServer/CivetHandler) which only offers a small subset of the available features.

**Comment by bel2125** [comment]
Its synchronous per connection with a fixed thread pool, and an additional waiting queue in case all threads are busy.
So it has advantages of both threading models: You can block in a couple of threads, but you don't need to create a new thread for every connection (or worse: for every request).

If you have a lot of blocking calls, you must have a larger num_thread configuration (size of the thread pool). If you have no blocking requests, you might use a low num_threads. e.g. the number of available CPU cores. In an "almost all calls don't block" best might be to choose around twice the number of CPU cores. If you use a lot of long lasting connections, e.g. websockets, you must use a higher number of threads. That's fine tuning.

You don't need a different API for these two scenarios, only different configurations (basically numbers in a text file read at start time). But you cannot configure that civetweb will only use one thread. There are always at least two: a master and an apprentice ... I mean worker ;-)
Since browsers tend to open several connections to the same site to load faster, using less than 5 thread seems to have a negative impact on performance. Using more than around 50000 threads may require some kernel parameter modification (but I tried and it worked) ... there is quite some space between. Usually 50 is a good choice to start - unless you are at a small embedded device where you need to save space right from the start.
If you use a low number of threads in the fixed thread pool, you should use a larger queue size. If all your request handler are fast ("non blocking" would be a too strong requirement), you are close to scenario 2.

---

By the way: Using # followed by a number will generate a reference to an issue or a reference to a pull request. So # 1 references "large file support" and # 2 some windows dll import/export definitions.

**Comment by mjs476** [comment]
Got it, that makes sense, and it's a good way of looking at it. Thanks for the detailed response.
