### ISSUE TITLE
error conn->request_info.client_cert

### ISSUE THREAD

**Issue by pavel-pimenov** [civetweb/civetweb#989]
V506 [CWE-562] Pointer to local variable 'client_cert' is stored outside the scope of this variable. 
Such a pointer will become invalid. civetweb.c 18855

https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L18852-L18856

**Comment by bel2125** [comment]
I think this is a false positive. 
I checked all PVS Studio warnings again middle of March 2021, since I'm planning a release in the next couple of days: https://github.com/civetweb/civetweb/issues/597#issuecomment-803581667


FALSE POSITIVE | General Analysis | civetweb-c-library | civetweb.c:18894 | Low | V506 | CWE-562 | Pointer to local variable 'client_cert' is stored outside the scope of this variable. Such a pointer will become invalid.
-- | -- | -- | -- | -- | -- | -- | --


The pointer stored here:
https://github.com/civetweb/civetweb/blob/365b38931037dcc42f7812bcf111ad9be41026d4/src/civetweb.c#L18852-L18856

Will become invalid some lines later in the same function:
https://github.com/civetweb/civetweb/blob/365b38931037dcc42f7812bcf111ad9be41026d4/src/civetweb.c#L18881-L18896

It is not used outside the `if (sslize(conn, SSL_accept, NULL)) {` block in this function. So this should be save.

Do you think I missed something here?
